'use strict';

/**
 * Nerd edition question bank.
 *
 * Same format and same six board slots as questions.js - every category is
 * re-themed:
 *
 *   0 Science Fiction             (was Geography)
 *   1 Computer Science & Tech     (was Entertainment)
 *   2 Mythology & Folklore        (was History)
 *   3 Anime & Manga               (was Arts & Literature)
 *   4 Machine Learning            (was Science & Nature)
 *   5 Video Games                 (was Sports & Leisure)
 *
 * Nothing is shared with the classic bank any more - only the build helper.
 * House rules for this edition: Computer Science means algorithms and data
 * structures, not industry gossip; the easy ML tier assumes an undergrad
 * course and the hard tier a graduate seminar; and both anime tiers assume
 * an actual fan - the easy tier here is what the hard tier used to be.
 */

const { build } = require('./questions');

// --------------------------------------------------------------------------
// EASY - the stuff any regular of the internet has absorbed by osmosis.
// --------------------------------------------------------------------------
const EASY_NERD = [
  // --------------------------------------------------------- Science Fiction
  { c: 0, q: "Who is revealed to be Luke Skywalker's father?", a: ["Darth Vader", "Obi-Wan Kenobi", "Emperor Palpatine", "Qui-Gon Jinn"] },
  { c: 0, q: "What is the name of Han Solo's ship?", a: ["The Millennium Falcon", "The Star Destroyer", "The Ebon Hawk", "The Outrider"] },
  { c: 0, q: "Which captain commands the USS Enterprise in the original Star Trek?", a: ["James T. Kirk", "Jean-Luc Picard", "Christopher Pike", "Benjamin Sisko"] },
  { c: 0, q: "What is the Doctor's time machine called in Doctor Who?", a: ["The TARDIS", "The Vortex", "The Gallifrey", "The Chronosphere"] },
  { c: 0, q: "In The Matrix, which pill does Neo take to see the truth?", a: ["The red pill", "The blue pill", "The green pill", "The white pill"] },
  { c: 0, q: "Which catchphrase belongs to the Terminator?", a: ["\"I'll be back\"", "\"Beam me up\"", "\"Exterminate!\"", "\"Resistance is futile\""] },
  { c: 0, q: "Which AI controls the ship Discovery One in 2001: A Space Odyssey?", a: ["HAL 9000", "Skynet", "GERTY", "Deep Thought"] },
  { c: 0, q: "What does E.T. famously want to do?", a: ["Phone home", "Fly home", "Hide forever", "Meet the president"] },
  { c: 0, q: "In Jurassic Park, dinosaur DNA is recovered from what?", a: ["Mosquitoes preserved in amber", "Frozen dinosaur eggs", "Fossilised bones", "Cave paintings"] },
  { c: 0, q: "Which car is the time machine in Back to the Future?", a: ["A DeLorean", "A Mustang", "A Corvette", "A Beetle"] },
  { c: 0, q: "On which desert planet is Dune set?", a: ["Arrakis", "Tatooine", "Vulcan", "Klendathu"] },
  { c: 0, q: "What valuable substance is harvested on Arrakis in Dune?", a: ["The spice", "The ore", "The nectar", "The crystal"] },
  { c: 0, q: "Who is always watching in George Orwell's 1984?", a: ["Big Brother", "The Warden", "The Overseer", "Father State"] },
  { c: 0, q: "In The Hitchhiker's Guide to the Galaxy, what is the answer to life, the universe and everything?", a: ["42", "7", "100", "3.14"] },
  { c: 0, q: "Which planet do the invaders come from in H.G. Wells's The War of the Worlds?", a: ["Mars", "Venus", "Jupiter", "The Moon"] },
  { c: 0, q: "Who wrote Frankenstein?", a: ["Mary Shelley", "Bram Stoker", "H.G. Wells", "Jules Verne"] },
  { c: 0, q: "Which captain commands the Nautilus in 20,000 Leagues Under the Sea?", a: ["Nemo", "Ahab", "Hook", "Flint"] },
  { c: 0, q: "What weapon does a Jedi carry?", a: ["A lightsaber", "A phaser", "A blaster", "A sonic sword"] },
  { c: 0, q: "Which small green Jedi Master trains Luke on Dagobah?", a: ["Yoda", "Mace Windu", "Grogu", "Obi-Wan"] },
  { c: 0, q: "Mr. Spock is half human and half what?", a: ["Vulcan", "Klingon", "Romulan", "Android"] },
  { c: 0, q: "In Blade Runner, what are the artificial humans called?", a: ["Replicants", "Cylons", "Synths", "Terminators"] },
  { c: 0, q: "Who is the heroine of the Alien films?", a: ["Ellen Ripley", "Sarah Connor", "Leia Organa", "Trinity"] },
  { c: 0, q: "On which moon is Avatar set?", a: ["Pandora", "Endor", "Titan", "Europa"] },
  { c: 0, q: "Who volunteers as tribute in The Hunger Games?", a: ["Katniss Everdeen", "Primrose Everdeen", "Hermione Granger", "Tris Prior"] },
  { c: 0, q: "Which author wrote The Time Machine and The Invisible Man?", a: ["H.G. Wells", "Jules Verne", "Isaac Asimov", "Arthur C. Clarke"] },
  { c: 0, q: "Who devised the Three Laws of Robotics?", a: ["Isaac Asimov", "Arthur C. Clarke", "Robert Heinlein", "Philip K. Dick"] },
  { c: 0, q: "What speed must the DeLorean reach to travel through time?", a: ["88 mph", "100 mph", "60 mph", "120 mph"] },
  { c: 0, q: "What is the Empire's moon-sized battle station called in Star Wars?", a: ["The Death Star", "The Star Forge", "The Executor", "The Eclipse"] },
  { c: 0, q: "What species is Chewbacca?", a: ["A Wookiee", "An Ewok", "A Rodian", "A Trandoshan"] },
  { c: 0, q: "Which two droids appear in every main Star Wars film?", a: ["R2-D2 and C-3PO", "BB-8 and D-O", "K-2SO and L3-37", "IG-88 and HK-47"] },
  { c: 0, q: "What is the mysterious energy field that gives Jedi their power?", a: ["The Force", "The Source", "The Aura", "The Current"] },
  { c: 0, q: "Which Doctor Who villains shout \"Exterminate!\"?", a: ["The Daleks", "The Cybermen", "The Sontarans", "The Weeping Angels"] },
  { c: 0, q: "In Ready Player One, what is the virtual world called?", a: ["The OASIS", "The Metaverse", "The Grid", "The Construct"] },
  { c: 0, q: "Which Christopher Nolan film sends astronauts through a wormhole to save humanity?", a: ["Interstellar", "Inception", "Tenet", "Gravity"] },
  { c: 0, q: "Which Pixar robot is left cleaning an abandoned Earth?", a: ["WALL-E", "EVE", "Baymax", "Johnny 5"] },
  { c: 0, q: "In The Martian, which crop does Mark Watney farm on Mars?", a: ["Potatoes", "Wheat", "Soybeans", "Corn"] },
  { c: 0, q: "Who leads the Autobots in Transformers?", a: ["Optimus Prime", "Megatron", "Bumblebee", "Starscream"] },
  { c: 0, q: "Which warlike Star Trek species has ridged foreheads and a warrior code?", a: ["Klingons", "Vulcans", "Ferengi", "Borg"] },
  { c: 0, q: "What is Superman's home planet?", a: ["Krypton", "Vulcan", "Xandar", "Oa"] },
  { c: 0, q: "What is the name of Marty McFly's scientist friend?", a: ["Doc Brown", "Professor X", "Dr. Strange", "Mr. Fusion"] },

  // -------------------------------------- Computer Science & Technology
  { c: 1, q: "What does CPU stand for?", a: ["Central Processing Unit", "Computer Power Unit", "Central Program Utility", "Core Processing Unit"] },
  { c: 1, q: "What does HTML stand for?", a: ["HyperText Markup Language", "High Transfer Machine Language", "Hyperlink Text Management Layer", "Home Tool Markup Language"] },
  { c: 1, q: "How many bits are in a byte?", a: ["8", "4", "16", "32"] },
  { c: 1, q: "What does RAM stand for?", a: ["Random Access Memory", "Rapid Application Memory", "Read Access Module", "Runtime Allocation Map"] },
  { c: 1, q: "What is the binary number 1010 in decimal?", a: ["10", "8", "12", "20"] },
  { c: 1, q: "Which programming language was named after the comedy troupe Monty Python?", a: ["Python", "Ruby", "Perl", "Cobra"] },
  { c: 1, q: "What does URL stand for?", a: ["Uniform Resource Locator", "Universal Reference Link", "User Registry Location", "Unified Retrieval Language"] },
  { c: 1, q: "Which language is used to style web pages?", a: ["CSS", "HTML", "SQL", "XML"] },
  { c: 1, q: "Which operating system kernel did Linus Torvalds create?", a: ["Linux", "Unix", "BSD", "Minix"] },
  { c: 1, q: "What is malicious software that encrypts your files and demands payment called?", a: ["Ransomware", "Adware", "Spyware", "Firmware"] },
  { c: 1, q: "What does GPU stand for?", a: ["Graphics Processing Unit", "General Purpose Unit", "Graphical Peripheral Unit", "Grid Processing Unit"] },
  { c: 1, q: "Which version control system, created by Linus Torvalds, is the industry standard?", a: ["Git", "Subversion", "Mercurial", "CVS"] },
  { c: 1, q: "Which protocol shows a padlock in the browser because the traffic is encrypted?", a: ["HTTPS", "HTTP", "FTP", "SMTP"] },
  { c: 1, q: "Which language runs natively in a web browser to make pages interactive?", a: ["JavaScript", "Java", "Python", "C#"] },
  { c: 1, q: "What does PDF stand for?", a: ["Portable Document Format", "Printed Document File", "Public Data Format", "Page Description File"] },
  { c: 1, q: "Which type of drive stores data with no moving parts?", a: ["An SSD", "A hard disk drive", "A floppy drive", "An optical drive"] },
  { c: 1, q: "Which short-range wireless technology connects headphones to a phone?", a: ["Bluetooth", "Wi-Fi", "NFC", "Infrared"] },
  { c: 1, q: "Which numbering system uses only the digits 0 and 1?", a: ["Binary", "Octal", "Decimal", "Hexadecimal"] },
  { c: 1, q: "What is unsolicited bulk email called?", a: ["Spam", "Phishing", "Ham", "Malware"] },
  { c: 1, q: "What is an error in a computer program commonly called?", a: ["A bug", "A glitchlet", "A fault line", "A crashlet"] },
  { c: 1, q: "What does VPN stand for?", a: ["Virtual Private Network", "Verified Public Node", "Variable Packet Network", "Virtual Proxy Name"] },
  { c: 1, q: "What does the IP in \"IP address\" stand for?", a: ["Internet Protocol", "Internet Provider", "Internal Path", "Indexed Packet"] },
  { c: 1, q: "Which device forwards traffic between your home network and the internet?", a: ["A router", "A monitor", "A scanner", "A modem cable"] },
  { c: 1, q: "What does OS stand for in computing?", a: ["Operating System", "Open Source", "Output Stream", "Object Store"] },
  { c: 1, q: "What does USB stand for?", a: ["Universal Serial Bus", "United System Bus", "Universal Storage Block", "Unified Signal Bridge"] },
  { c: 1, q: "Roughly how many megabytes are in a gigabyte?", a: ["1024", "100", "512", "2048"] },
  { c: 1, q: "What is the popular name for a program that automatically visits and indexes web pages?", a: ["A web crawler", "A daemon", "A cookie", "A macro"] },
  { c: 1, q: "Which component of a computer keeps data when the power is switched off?", a: ["The hard drive", "The RAM", "The CPU", "The cache"] },
  { c: 1, q: "What does AI stand for?", a: ["Artificial Intelligence", "Automated Inference", "Applied Informatics", "Algorithmic Iteration"] },
  { c: 1, q: "Which data structure works first-in, first-out?", a: ["A queue", "A stack", "A tree", "A graph"] },
  { c: 1, q: "In most programming languages, what is the index of the first element of an array?", a: ["0", "1", "-1", "It depends on the array's length"] },
  { c: 1, q: "What is the worst-case time complexity of scanning an unsorted list one element at a time?", a: ["O(n)", "O(1)", "O(log n)", "O(n²)"] },
  { c: 1, q: "Which data structure maps keys to values for fast lookup?", a: ["A hash table", "A stack", "A queue", "A linked list"] },
  { c: 1, q: "What is the maximum number of children a node can have in a binary tree?", a: ["Two", "One", "Four", "Eight"] },
  { c: 1, q: "What is a tree node with no children called?", a: ["A leaf", "A root", "A branch", "A stump"] },
  { c: 1, q: "Which simple sorting algorithm repeatedly swaps adjacent elements that are out of order?", a: ["Bubble sort", "Merge sort", "Quicksort", "Radix sort"] },
  { c: 1, q: "Which notation describes how an algorithm's running time grows with input size?", a: ["Big-O notation", "Scientific notation", "Polish notation", "Two's complement"] },
  { c: 1, q: "In a singly linked list, what does each node store along with its value?", a: ["A pointer to the next node", "The length of the list", "A pointer to the head", "Its own index"] },
  { c: 1, q: "What is an algorithm that simply tries every possible option called?", a: ["Brute force", "Divide and conquer", "Greedy", "Backtracking"] },
  { c: 1, q: "Which search algorithm repeatedly halves a sorted list to find a target?", a: ["Binary search", "Linear search", "Depth-first search", "Interpolation search"] },

  // ------------------------------------------------- Mythology & Folklore
  { c: 2, q: "Who is the king of the Greek gods?", a: ["Zeus", "Poseidon", "Apollo", "Ares"] },
  { c: 2, q: "Which Greek god rules the sea?", a: ["Poseidon", "Hades", "Hermes", "Hephaestus"] },
  { c: 2, q: "Who is the Greek god of the underworld?", a: ["Hades", "Zeus", "Dionysus", "Cronus"] },
  { c: 2, q: "Which Norse god wields the hammer Mjolnir?", a: ["Thor", "Odin", "Loki", "Baldr"] },
  { c: 2, q: "Who is the trickster god of Norse mythology?", a: ["Loki", "Thor", "Heimdall", "Freyr"] },
  { c: 2, q: "Which one-eyed god rules Asgard?", a: ["Odin", "Thor", "Tyr", "Njord"] },
  { c: 2, q: "Which Greek hero completed twelve labours?", a: ["Heracles", "Perseus", "Theseus", "Jason"] },
  { c: 2, q: "Which Gorgon's gaze turned people to stone?", a: ["Medusa", "Scylla", "Charybdis", "Circe"] },
  { c: 2, q: "What creature, half man and half bull, was kept in the Labyrinth?", a: ["The Minotaur", "The Centaur", "The Satyr", "The Cyclops"] },
  { c: 2, q: "Which Egyptian god has the head of a jackal?", a: ["Anubis", "Horus", "Ra", "Sobek"] },
  { c: 2, q: "Which Egyptian sun god sails across the sky in a boat?", a: ["Ra", "Osiris", "Thoth", "Ptah"] },
  { c: 2, q: "Which mythical bird bursts into flame and is reborn from its ashes?", a: ["The phoenix", "The griffin", "The roc", "The harpy"] },
  { c: 2, q: "What three-headed dog guards the Greek underworld?", a: ["Cerberus", "Orthrus", "Fenrir", "Chimera"] },
  { c: 2, q: "Which hero's only weak point was his heel?", a: ["Achilles", "Hector", "Odysseus", "Agamemnon"] },
  { c: 2, q: "Which wooden trick ended the Trojan War?", a: ["The Trojan Horse", "The Golden Fleece", "The Wooden Bull", "The Siege Tower"] },
  { c: 2, q: "Who flew too close to the sun on wings of wax and feathers?", a: ["Icarus", "Daedalus", "Hermes", "Phaethon"] },
  { c: 2, q: "Whose box, once opened, released all the evils of the world?", a: ["Pandora's", "Persephone's", "Ariadne's", "Cassandra's"] },
  { c: 2, q: "Which king turned everything he touched to gold?", a: ["Midas", "Croesus", "Minos", "Tantalus"] },
  { c: 2, q: "On which mountain do the Greek gods live?", a: ["Mount Olympus", "Mount Ida", "Mount Parnassus", "Mount Etna"] },
  { c: 2, q: "Where do Norse warriors who die in battle feast with Odin?", a: ["Valhalla", "Helheim", "Alfheim", "Vanaheim"] },
  { c: 2, q: "What is the Norse doomsday battle called?", a: ["Ragnarok", "Fimbulwinter", "Ginnungagap", "Yggdrasil"] },
  { c: 2, q: "Which Greek goddess of wisdom sprang fully armed from Zeus's head?", a: ["Athena", "Hera", "Artemis", "Demeter"] },
  { c: 2, q: "Who is the Greek goddess of love?", a: ["Aphrodite", "Athena", "Hestia", "Hecate"] },
  { c: 2, q: "Which Roman god of love shoots arrows to make people fall in love?", a: ["Cupid", "Mars", "Mercury", "Janus"] },
  { c: 2, q: "What is King Arthur's sword called?", a: ["Excalibur", "Durendal", "Gram", "Joyeuse"] },
  { c: 2, q: "Which wizard advises King Arthur?", a: ["Merlin", "Gandalf", "Taliesin", "Mordred"] },
  { c: 2, q: "Which English folk hero robbed the rich to give to the poor?", a: ["Robin Hood", "King Arthur", "Beowulf", "Dick Turpin"] },
  { c: 2, q: "Which giant sea monster of Scandinavian legend drags ships beneath the waves?", a: ["The Kraken", "The Leviathan", "Jormungandr", "Charybdis"] },
  { c: 2, q: "What creature is a woman above the waist and a fish below?", a: ["A mermaid", "A siren", "A selkie", "A naiad"] },
  { c: 2, q: "Under what moon is a werewolf said to transform?", a: ["A full moon", "A new moon", "A harvest moon", "A blood moon"] },
  { c: 2, q: "Which Irish fairy hides a pot of gold at the end of the rainbow?", a: ["A leprechaun", "A banshee", "A pooka", "A clurichaun"] },
  { c: 2, q: "What spirit grants wishes when its lamp is rubbed?", a: ["A genie", "A ghoul", "An imp", "A sprite"] },
  { c: 2, q: "Which messenger god wears winged sandals?", a: ["Hermes", "Apollo", "Ares", "Dionysus"] },
  { c: 2, q: "Who is the Greek god of the sun, music and prophecy?", a: ["Apollo", "Helios", "Hermes", "Pan"] },
  { c: 2, q: "Which hero beheaded Medusa using a mirrored shield?", a: ["Perseus", "Heracles", "Theseus", "Bellerophon"] },
  { c: 2, q: "Which monkey hero with a magic staff stars in Journey to the West?", a: ["Sun Wukong", "Nezha", "Erlang Shen", "Zhu Bajie"] },
  { c: 2, q: "What creature in Greek myth is half man, half horse?", a: ["A centaur", "A satyr", "A minotaur", "A faun"] },
  { c: 2, q: "Which food is traditionally said to ward off vampires?", a: ["Garlic", "Salt", "Rosemary", "Onions"] },
  { c: 2, q: "Which ship did Jason sail in search of the Golden Fleece?", a: ["The Argo", "The Odyssey", "The Calypso", "The Hesperus"] },
  { c: 2, q: "Who is the Egyptian goddess of magic and wife of Osiris?", a: ["Isis", "Nephthys", "Hathor", "Bastet"] },

  // ------------------------------------------------------- Anime & Manga
  { c: 3, q: "Which studio animated the first three seasons of Attack on Titan?", a: ["Wit Studio", "MAPPA", "Ufotable", "Bones"] },
  { c: 3, q: "Who directed Cowboy Bebop?", a: ["Shinichiro Watanabe", "Hideaki Anno", "Mamoru Oshii", "Satoshi Kon"] },
  { c: 3, q: "What is the name of Guts's enormous sword in Berserk?", a: ["The Dragonslayer", "The Godhand", "Zangetsu", "The Behelit"] },
  { c: 3, q: "Which mangaka created Berserk?", a: ["Kentaro Miura", "Naoki Urasawa", "Takehiko Inoue", "Yukito Kishiro"] },
  { c: 3, q: "In Neon Genesis Evangelion, what are the monstrous enemies called?", a: ["Angels", "Titans", "Espers", "Demons"] },
  { c: 3, q: "Which Makoto Shinkai film features two teenagers swapping bodies?", a: ["Your Name", "Weathering with You", "5 Centimetres per Second", "Suzume"] },
  { c: 3, q: "Who created the manga Ghost in the Shell?", a: ["Masamune Shirow", "Katsuhiro Otomo", "Yoshiyuki Sadamoto", "Tsutomu Nihei"] },
  { c: 3, q: "Which studio produced the Demon Slayer anime?", a: ["Ufotable", "MAPPA", "Bones", "A-1 Pictures"] },
  { c: 3, q: "What is Luffy's Devil Fruit called?", a: ["The Gum-Gum Fruit", "The Flame-Flame Fruit", "The Chop-Chop Fruit", "The Op-Op Fruit"] },
  { c: 3, q: "Which is the best-selling manga series of all time?", a: ["One Piece", "Dragon Ball", "Naruto", "Golgo 13"] },
  { c: 3, q: "Which co-founder of Studio Ghibli directed Grave of the Fireflies?", a: ["Isao Takahata", "Hayao Miyazaki", "Toshio Suzuki", "Goro Miyazaki"] },
  { c: 3, q: "What is the name of Shinji's mecha in Neon Genesis Evangelion?", a: ["Unit-01", "Unit-00", "Unit-02", "Unit-03"] },
  { c: 3, q: "Who is the Fourth Hokage in Naruto?", a: ["Minato Namikaze", "Hiruzen Sarutobi", "Tobirama Senju", "Tsunade"] },
  { c: 3, q: "Which anime follows Kirito trapped in a virtual reality MMO?", a: ["Sword Art Online", "Log Horizon", "Overlord", "No Game No Life"] },
  { c: 3, q: "Which Naoki Urasawa manga follows a surgeon hunting a killer he once saved?", a: ["Monster", "20th Century Boys", "Pluto", "Billy Bat"] },
  { c: 3, q: "In JoJo's Bizarre Adventure, what are the manifested powers called?", a: ["Stands", "Ripples", "Quirks", "Personas"] },
  { c: 3, q: "What is the name of Jotaro Kujo's Stand?", a: ["Star Platinum", "The World", "Crazy Diamond", "Gold Experience"] },
  { c: 3, q: "Who directed the 1995 film Ghost in the Shell?", a: ["Mamoru Oshii", "Satoshi Kon", "Katsuhiro Otomo", "Rintaro"] },
  { c: 3, q: "Which studio produced K-On! and Violet Evergarden?", a: ["Kyoto Animation", "P.A. Works", "Shaft", "J.C. Staff"] },
  { c: 3, q: "In Code Geass, what is Lelouch's power called?", a: ["Geass", "Nen", "Sharingan", "Cursed Energy"] },
  { c: 3, q: "Who created the manga Sailor Moon?", a: ["Naoko Takeuchi", "Rumiko Takahashi", "CLAMP", "Ai Yazawa"] },
  { c: 3, q: "Who wrote and illustrated Chainsaw Man?", a: ["Tatsuki Fujimoto", "Gege Akutami", "Koyoharu Gotouge", "Yuji Kaku"] },
  { c: 3, q: "What is the name of Denji's devil-dog companion in Chainsaw Man?", a: ["Pochita", "Power", "Beam", "Meowy"] },
  { c: 3, q: "Who is the protagonist of Vinland Saga?", a: ["Thorfinn", "Askeladd", "Canute", "Thors"] },
  { c: 3, q: "Which anime film won the Academy Award for Best Animated Feature in 2003?", a: ["Spirited Away", "Princess Mononoke", "Howl's Moving Castle", "The Cat Returns"] },
  { c: 3, q: "What is the organisation Shinji's father commands in Evangelion?", a: ["NERV", "SEELE", "WILLE", "GEHIRN"] },
  { c: 3, q: "What is the name of Ichigo's zanpakuto in Bleach?", a: ["Zangetsu", "Senbonzakura", "Hyorinmaru", "Sode no Shirayuki"] },
  { c: 3, q: "Which criminal organisation in Naruto wears black cloaks with red clouds?", a: ["The Akatsuki", "The Anbu", "The Sound Four", "The Sannin"] },
  { c: 3, q: "Which mangaka created Astro Boy and is known as the god of manga?", a: ["Osamu Tezuka", "Go Nagai", "Shotaro Ishinomori", "Leiji Matsumoto"] },
  { c: 3, q: "Which demographic label describes manga aimed at young girls?", a: ["Shojo", "Shonen", "Seinen", "Josei"] },
  { c: 3, q: "Which demographic label describes manga aimed at adult men?", a: ["Seinen", "Shonen", "Shojo", "Kodomomuke"] },
  { c: 3, q: "Which swordsman is Zoro's ultimate target in One Piece?", a: ["Dracule Mihawk", "Shanks", "Kaido", "Sanji"] },
  { c: 3, q: "Which studio animated the first season of Jujutsu Kaisen?", a: ["MAPPA", "Ufotable", "Wit Studio", "Madhouse"] },
  { c: 3, q: "What is Mikasa's surname in Attack on Titan?", a: ["Ackerman", "Arlert", "Yeager", "Leonhart"] },
  { c: 3, q: "What is L's full name in Death Note?", a: ["L Lawliet", "L Ryuzaki", "L Coil", "L Deneuve"] },
  { c: 3, q: "Which anime's soundtrack by Yoko Kanno opens with the track \"Tank!\"?", a: ["Cowboy Bebop", "Samurai Champloo", "Wolf's Rain", "Macross Plus"] },
  { c: 3, q: "In which region does Ash begin his journey in the Pokémon anime?", a: ["Kanto", "Johto", "Hoenn", "Sinnoh"] },
  { c: 3, q: "Which earlier Yoshihiro Togashi series preceded Hunter x Hunter?", a: ["Yu Yu Hakusho", "Rurouni Kenshin", "Flame of Recca", "Shaman King"] },
  { c: 3, q: "Who is the demon king in Demon Slayer?", a: ["Muzan Kibutsuji", "Akaza", "Kokushibo", "Doma"] },
  { c: 3, q: "Which breathing style does Tanjiro first learn?", a: ["Water Breathing", "Sun Breathing", "Thunder Breathing", "Flame Breathing"] },

  // ------------------------------------------------------ Machine Learning
  { c: 4, q: "Which type of machine learning trains on labelled examples?", a: ["Supervised learning", "Unsupervised learning", "Reinforcement learning", "Self-play"] },
  { c: 4, q: "Which type of machine learning finds structure in unlabelled data?", a: ["Unsupervised learning", "Supervised learning", "Imitation learning", "Active learning"] },
  { c: 4, q: "What is it called when a model memorises its training data but fails on new data?", a: ["Overfitting", "Underfitting", "Regularisation", "Convergence"] },
  { c: 4, q: "Which algorithm iteratively updates parameters in the direction that reduces the loss?", a: ["Gradient descent", "Simulated annealing", "Grid search", "Beam search"] },
  { c: 4, q: "Which hyperparameter controls the step size of gradient descent?", a: ["The learning rate", "The batch size", "The momentum", "The dropout rate"] },
  { c: 4, q: "What range of values does the sigmoid function output?", a: ["Between 0 and 1", "Between -1 and 1", "Any real number", "Only 0 or 1"] },
  { c: 4, q: "What does the ReLU activation output for a negative input?", a: ["Zero", "The input unchanged", "One", "The input's absolute value"] },
  { c: 4, q: "Which algorithm groups data into k clusters around moving centroids?", a: ["k-means", "k-nearest neighbours", "Naive Bayes", "Linear regression"] },
  { c: 4, q: "Which classifier labels a point by a majority vote of the closest training examples?", a: ["k-nearest neighbours", "k-means", "A decision stump", "A perceptron"] },
  { c: 4, q: "What is one complete pass through the training set called?", a: ["An epoch", "A batch", "An iteration", "A fold"] },
  { c: 4, q: "Despite its name, which \"regression\" model is used for classification?", a: ["Logistic regression", "Linear regression", "Ridge regression", "Polynomial regression"] },
  { c: 4, q: "Which loss function is the default choice for regression problems?", a: ["Mean squared error", "Cross-entropy", "Hinge loss", "Focal loss"] },
  { c: 4, q: "Which function turns a vector of raw scores into a probability distribution?", a: ["Softmax", "ReLU", "Tanh", "Argmax"] },
  { c: 4, q: "A random forest is an ensemble of which model?", a: ["Decision trees", "Perceptrons", "SVMs", "Linear regressions"] },
  { c: 4, q: "Which algorithm propagates error gradients backwards through a neural network?", a: ["Backpropagation", "Forward chaining", "Belief propagation", "Boosting"] },
  { c: 4, q: "Why is a test set kept separate from training data?", a: ["To measure performance on unseen data", "To speed up training", "To store the best weights", "To balance the classes"] },
  { c: 4, q: "What are the tunable numbers inside a neural network called?", a: ["Weights", "Tokens", "Features", "Labels"] },
  { c: 4, q: "Which technique randomly deactivates neurons during training to reduce overfitting?", a: ["Dropout", "Pruning", "Pooling", "Padding"] },
  { c: 4, q: "Which architecture built on convolutions is the classic choice for images?", a: ["A convolutional neural network", "A recurrent neural network", "A decision tree", "A Boltzmann machine"] },
  { c: 4, q: "Which metric is the fraction of predicted positives that are actually positive?", a: ["Precision", "Recall", "Accuracy", "Specificity"] },
  { c: 4, q: "Which metric is the fraction of actual positives that the model finds?", a: ["Recall", "Precision", "F1 score", "AUC"] },
  { c: 4, q: "What is the table comparing predicted classes against true classes called?", a: ["A confusion matrix", "A correlation matrix", "A contingency plan", "A covariance matrix"] },
  { c: 4, q: "A model too simple to capture the pattern in its training data is said to be what?", a: ["Underfitting", "Overfitting", "Diverging", "Saturating"] },
  { c: 4, q: "Which encoding represents a category as a binary vector with a single 1?", a: ["One-hot encoding", "Label encoding", "Hashing", "Byte-pair encoding"] },
  { c: 4, q: "Which kind of learning trains an agent through rewards and penalties?", a: ["Reinforcement learning", "Supervised learning", "Transfer learning", "Contrastive learning"] },
  { c: 4, q: "Which classic dataset of 70,000 handwritten digits is the \"hello world\" of ML?", a: ["MNIST", "ImageNet", "CIFAR-10", "Iris"] },
  { c: 4, q: "What essential property does an activation function add to a neural network?", a: ["Non-linearity", "Stability", "Sparsity", "Symmetry"] },
  { c: 4, q: "Which 1958 model is a single artificial neuron - the simplest neural network?", a: ["The perceptron", "The Hopfield network", "The autoencoder", "The transformer"] },
  { c: 4, q: "What is an input variable that a model learns from called?", a: ["A feature", "A label", "A weight", "A gradient"] },
  { c: 4, q: "What is the quantity a supervised model tries to predict called?", a: ["The label", "The feature", "The bias", "The residual"] },
  { c: 4, q: "Which regularisation penalises the sum of absolute weights, driving some to exactly zero?", a: ["L1 (lasso)", "L2 (ridge)", "Dropout", "Early stopping"] },
  { c: 4, q: "Which regularisation penalises the sum of squared weights?", a: ["L2 (ridge)", "L1 (lasso)", "Batch norm", "Data augmentation"] },
  { c: 4, q: "Which classifier finds the separating hyperplane with the maximum margin?", a: ["A support vector machine", "Naive Bayes", "A random forest", "k-nearest neighbours"] },
  { c: 4, q: "Which technique projects data onto the directions of maximum variance?", a: ["Principal component analysis", "k-means", "Gradient boosting", "Batch normalisation"] },
  { c: 4, q: "Which loss function is standard for training classifiers that output probabilities?", a: ["Cross-entropy", "Mean squared error", "Huber loss", "Triplet loss"] },
  { c: 4, q: "Which curve plots true positive rate against false positive rate?", a: ["The ROC curve", "The learning curve", "The loss curve", "The calibration curve"] },
  { c: 4, q: "Which held-out split is used to tune hyperparameters during development?", a: ["The validation set", "The test set", "The training set", "The holdout label"] },
  { c: 4, q: "What is the subset of training examples processed in one gradient update called?", a: ["A mini-batch", "An epoch", "A fold", "A shard"] },
  { c: 4, q: "Which classifier naively assumes all features are independent given the class?", a: ["Naive Bayes", "Logistic regression", "A decision tree", "An SVM"] },
  { c: 4, q: "Which trade-off pits a model's systematic error against its sensitivity to the training sample?", a: ["The bias-variance trade-off", "The precision-recall trade-off", "The speed-accuracy trade-off", "The explore-exploit trade-off"] },

  // --------------------------------------------------------- Video Games
  { c: 5, q: "Which moustachioed plumber is Nintendo's mascot?", a: ["Mario", "Luigi", "Wario", "Toad"] },
  { c: 5, q: "What is the name of the green-clad hero of The Legend of Zelda?", a: ["Link", "Zelda", "Ganon", "Navi"] },
  { c: 5, q: "Which company makes the Xbox?", a: ["Microsoft", "Sony", "Nintendo", "Sega"] },
  { c: 5, q: "Which Minecraft mob hisses and then explodes?", a: ["The creeper", "The enderman", "The zombie", "The blaze"] },
  { c: 5, q: "Which is the best-selling video game of all time?", a: ["Minecraft", "Tetris", "Grand Theft Auto V", "Wii Sports"] },
  { c: 5, q: "Which blue hedgehog is Sega's mascot?", a: ["Sonic", "Knuckles", "Tails", "Shadow"] },
  { c: 5, q: "Which battle royale game is known for letting players build structures?", a: ["Fortnite", "PUBG", "Apex Legends", "Warzone"] },
  { c: 5, q: "What does FPS stand for as a game genre?", a: ["First-person shooter", "Frames per second", "Free-play strategy", "Fantasy party sim"] },
  { c: 5, q: "Which company created the PlayStation?", a: ["Sony", "Microsoft", "Nintendo", "Atari"] },
  { c: 5, q: "Which series stars the armoured soldier Master Chief?", a: ["Halo", "Doom", "Gears of War", "Destiny"] },
  { c: 5, q: "Which series stars the archaeologist Lara Croft?", a: ["Tomb Raider", "Uncharted", "Indiana Jones", "Far Cry"] },
  { c: 5, q: "What does Sonic collect as he runs?", a: ["Rings", "Coins", "Stars", "Gems"] },
  { c: 5, q: "In which kingdom is The Legend of Zelda set?", a: ["Hyrule", "Termina", "Gerudo", "Eldia"] },
  { c: 5, q: "In Among Us, what is the traitor called?", a: ["The impostor", "The saboteur", "The mole", "The infected"] },
  { c: 5, q: "Which farming game was made almost single-handedly by Eric Barone?", a: ["Stardew Valley", "Harvest Moon", "Farming Simulator", "My Time at Portia"] },
  { c: 5, q: "Which 1972 arcade game was a simple table-tennis simulation?", a: ["Pong", "Breakout", "Space Invaders", "Asteroids"] },
  { c: 5, q: "Which city is the setting of Grand Theft Auto V?", a: ["Los Santos", "Liberty City", "Vice City", "San Fierro"] },
  { c: 5, q: "Which handheld console did Nintendo launch in 1989?", a: ["The Game Boy", "The Game Gear", "The Lynx", "The Nintendo DS"] },
  { c: 5, q: "Which life-simulation series lets you build homes and run families' lives?", a: ["The Sims", "SimCity", "Animal Crossing", "Second Life"] },
  { c: 5, q: "Which series stars the Spartan-turned-god-killer Kratos?", a: ["God of War", "Devil May Cry", "Bayonetta", "Darksiders"] },
  { c: 5, q: "Which Valve shooter is commonly abbreviated to CS?", a: ["Counter-Strike", "Call of Duty", "Crysis", "Combat Storm"] },
  { c: 5, q: "What is the name of Mario's taller brother?", a: ["Luigi", "Wario", "Waluigi", "Yoshi"] },
  { c: 5, q: "Which 2006 Nintendo console was built around motion controls?", a: ["The Wii", "The GameCube", "The Wii U", "The Switch"] },
  { c: 5, q: "Which raccoon-like character lends you money in Animal Crossing?", a: ["Tom Nook", "Isabelle", "K.K. Slider", "Blathers"] },
  { c: 5, q: "Which stealth series stars Solid Snake?", a: ["Metal Gear", "Splinter Cell", "Hitman", "Thief"] },
  { c: 5, q: "Which puzzle game arms you with a gun that shoots portals?", a: ["Portal", "Antichamber", "The Witness", "Quantum Conundrum"] },
  { c: 5, q: "Which fighting game series features Ryu and Chun-Li?", a: ["Street Fighter", "Tekken", "Mortal Kombat", "Guilty Gear"] },
  { c: 5, q: "What are Pac-Man's four pursuers?", a: ["Ghosts", "Robots", "Blobs", "Aliens"] },
  { c: 5, q: "Which company created Half-Life and the Steam store?", a: ["Valve", "id Software", "Epic Games", "Bungie"] },
  { c: 5, q: "Which is the best-selling home console of all time?", a: ["The PlayStation 2", "The Nintendo Wii", "The Xbox 360", "The PlayStation 4"] },
  { c: 5, q: "Which pink puffball can copy his enemies' abilities?", a: ["Kirby", "Jigglypuff", "Yoshi", "Ness"] },
  { c: 5, q: "Which Minecraft material makes the most durable tools?", a: ["Netherite", "Diamond", "Obsidian", "Iron"] },
  { c: 5, q: "Which open-world series pits Assassins against Templars?", a: ["Assassin's Creed", "Dishonored", "Watch Dogs", "Hitman"] },
  { c: 5, q: "Which mobile game launched birds at pigs with a slingshot?", a: ["Angry Birds", "Cut the Rope", "Fruit Ninja", "Doodle Jump"] },
  { c: 5, q: "Which Blizzard game is a team-based hero shooter?", a: ["Overwatch", "Valorant", "Team Fortress 2", "Paladins"] },
  { c: 5, q: "Which Nintendo series pits characters from many franchises against each other?", a: ["Super Smash Bros.", "Mario Party", "Nintendo Land", "Mario Kart"] },
  { c: 5, q: "Which company developed Fortnite?", a: ["Epic Games", "Riot Games", "Ubisoft", "Activision"] },
  { c: 5, q: "In Tetris, what is the long straight piece nicknamed?", a: ["The I-piece", "The L-piece", "The S-piece", "The T-piece"] },
  { c: 5, q: "Which of these is a starter Pokémon in Red and Blue?", a: ["Charmander", "Zubat", "Snorlax", "Gengar"] },
  { c: 5, q: "Which item in Mario Kart makes you briefly invincible?", a: ["The star", "The green shell", "The banana", "The mushroom"] },
];

// --------------------------------------------------------------------------
// HARD - the stuff you only know if this is genuinely your thing.
// --------------------------------------------------------------------------
const HARD_NERD = [
  // --------------------------------------------------------- Science Fiction
  { c: 0, q: "Which mathematician invents psychohistory in Asimov's Foundation?", a: ["Hari Seldon", "Salvor Hardin", "R. Daneel Olivaw", "The Mule"] },
  { c: 0, q: "In Dune, what Fremen name does Paul Atreides take?", a: ["Muad'Dib", "Shai-Hulud", "Kwisatz Haderach", "Sardaukar"] },
  { c: 0, q: "What do the Bene Gesserit call their prophesied superbeing in Dune?", a: ["The Kwisatz Haderach", "The Lisan al-Gaib", "The Mentat", "The Golden Path"] },
  { c: 0, q: "In Dune, what do the Fremen call the great sandworms?", a: ["Shai-Hulud", "Muad'Dib", "Arrakeen", "The Makers' Wrath"] },
  { c: 0, q: "Which rival house are the sworn enemies of House Atreides?", a: ["House Harkonnen", "House Corrino", "House Ordos", "House Richese"] },
  { c: 0, q: "Which test does the Bene Gesserit Reverend Mother give Paul with a poisoned needle at his neck?", a: ["The gom jabbar", "The water of life", "The spice agony", "The litany of fear"] },
  { c: 0, q: "Which Arthur C. Clarke novel explores a vast cylindrical alien ship passing through the solar system?", a: ["Rendezvous with Rama", "Childhood's End", "The Fountains of Paradise", "2010: Odyssey Two"] },
  { c: 0, q: "What is the ratio of the monolith's dimensions in 2001: A Space Odyssey?", a: ["1:4:9", "1:2:3", "1:3:5", "2:4:8"] },
  { c: 0, q: "Which Philip K. Dick novel became the film Blade Runner?", a: ["Do Androids Dream of Electric Sheep?", "Ubik", "A Scanner Darkly", "Flow My Tears, the Policeman Said"] },
  { c: 0, q: "Which empathy test identifies replicants in Blade Runner?", a: ["The Voight-Kampff test", "The Turing test", "The Rorschach test", "The Bene Gesserit test"] },
  { c: 0, q: "Which corporation builds the replicants in Blade Runner?", a: ["The Tyrell Corporation", "Weyland-Yutani", "Cyberdyne Systems", "Omni Consumer Products"] },
  { c: 0, q: "Which replicant delivers the \"tears in rain\" monologue?", a: ["Roy Batty", "Rick Deckard", "Leon Kowalski", "Rachael"] },
  { c: 0, q: "Which Philip K. Dick novel imagines the Axis powers having won World War II?", a: ["The Man in the High Castle", "VALIS", "Ubik", "Time Out of Joint"] },
  { c: 0, q: "Which 1984 novel by William Gibson launched the cyberpunk genre?", a: ["Neuromancer", "Snow Crash", "Count Zero", "Do Androids Dream of Electric Sheep?"] },
  { c: 0, q: "Which AI orchestrates the heist at the heart of Neuromancer?", a: ["Wintermute", "Neuromancer", "Dixie Flatline", "Armitage"] },
  { c: 0, q: "In Snow Crash, what is Hiro Protagonist's day job in the real world?", a: ["Delivering pizza", "Hacking banks", "Teaching swordfighting", "Driving a taxi"] },
  { c: 0, q: "Which Neal Stephenson novel popularised the term \"metaverse\"?", a: ["Snow Crash", "Cryptonomicon", "The Diamond Age", "Seveneves"] },
  { c: 0, q: "Which Ursula K. Le Guin novel is set on Gethen, a planet whose people have no fixed sex?", a: ["The Left Hand of Darkness", "The Dispossessed", "The Lathe of Heaven", "The Word for World Is Forest"] },
  { c: 0, q: "What is the instantaneous communication device in Le Guin's Hainish novels called?", a: ["The ansible", "The subwave", "The tachyon relay", "The hyperlink"] },
  { c: 0, q: "Which Ted Chiang story was adapted into the film Arrival?", a: ["Story of Your Life", "Exhalation", "Tower of Babylon", "Understand"] },
  { c: 0, q: "In The Three-Body Problem, what is the alien civilisation called?", a: ["The Trisolarans", "The Heptapods", "The Overlords", "The Formics"] },
  { c: 0, q: "Which idea from Liu Cixin's trilogy explains the Fermi paradox as universal hiding?", a: ["The dark forest", "The great filter", "The zoo hypothesis", "The quiet war"] },
  { c: 0, q: "Which metal creature impales victims on a tree of thorns in Dan Simmons's Hyperion?", a: ["The Shrike", "The Ouster", "The Templar", "The Bikura"] },
  { c: 0, q: "What are the insectoid aliens of Ender's Game called?", a: ["The Formics", "The Arachnids", "The Trisolarans", "The Xenomorphs"] },
  { c: 0, q: "In which novel does Billy Pilgrim come \"unstuck in time\"?", a: ["Slaughterhouse-Five", "Cat's Cradle", "The Sirens of Titan", "Catch-22"] },
  { c: 0, q: "On which planet is Billy Pilgrim exhibited in a zoo?", a: ["Tralfamadore", "Titan", "Trantor", "Tschai"] },
  { c: 0, q: "What does the title of Fahrenheit 451 refer to?", a: ["The temperature at which book paper ignites", "The number of banned books", "The firemen's radio code", "The year the story is set"] },
  { c: 0, q: "Which drug keeps the citizens of Brave New World content?", a: ["Soma", "Melange", "Substance D", "Prozium"] },
  { c: 0, q: "What is the invented teen slang of A Clockwork Orange called?", a: ["Nadsat", "Newspeak", "Simlish", "Lunarglish"] },
  { c: 0, q: "Which Stanislaw Lem novel features a planet covered by a sentient ocean?", a: ["Solaris", "The Invincible", "Eden", "Fiasco"] },
  { c: 0, q: "Which Strugatsky brothers novel inspired Tarkovsky's film Stalker?", a: ["Roadside Picnic", "Hard to Be a God", "The Doomed City", "Monday Begins on Saturday"] },
  { c: 0, q: "In The Expanse, what is the alien substance discovered on Phoebe?", a: ["The protomolecule", "The catalyst", "The seed", "The strain"] },
  { c: 0, q: "What do James Holden and his crew name their salvaged gunship in The Expanse?", a: ["The Rocinante", "The Canterbury", "The Donnager", "The Behemoth"] },
  { c: 0, q: "Which phrase do Colonial officers and crew affirm with in Battlestar Galactica?", a: ["\"So say we all\"", "\"By your command\"", "\"All this has happened before\"", "\"Fly true\""] },
  { c: 0, q: "Which two ancient races fight a proxy war through younger species in Babylon 5?", a: ["The Shadows and the Vorlons", "The Minbari and the Centauri", "The Narn and the Drazi", "The First Ones and the Rangers"] },
  { c: 0, q: "What is the registry number of the original USS Enterprise?", a: ["NCC-1701", "NCC-1864", "NX-2000", "NCC-74656"] },
  { c: 0, q: "Which Starfleet Academy test presents cadets with a no-win scenario?", a: ["The Kobayashi Maru", "The Prime Directive", "The Omega Directive", "The Vulcan Kahs-wan"] },
  { c: 0, q: "Which furry creatures breed out of control aboard the Enterprise?", a: ["Tribbles", "Ewoks", "Mogwai", "Porgs"] },
  { c: 0, q: "What name does Captain Picard bear while assimilated by the Borg?", a: ["Locutus", "Hugh", "The Vindicator", "Seven of Nine"] },
  { c: 0, q: "Which command ordered the clone troopers to turn on the Jedi?", a: ["Order 66", "Order 99", "Protocol 13", "Directive 7"] },
  { c: 0, q: "In how many parsecs did Han Solo claim the Falcon made the Kessel Run?", a: ["Less than 12", "Less than 5", "Less than 20", "Exactly 14"] },
  { c: 0, q: "What is Boba Fett's ship called in the original trilogy era?", a: ["Slave I", "Razor Crest", "The Fang", "Firespray Prime"] },
  { c: 0, q: "On which moon does the Nostromo crew find the derelict alien ship?", a: ["LV-426", "LV-223", "Fiorina 161", "Acheron Prime"] },
  { c: 0, q: "Which corporation keeps sending crews after the xenomorph in the Alien films?", a: ["Weyland-Yutani", "Tyrell", "Cyberdyne", "InGen"] },
  { c: 0, q: "What is the Nostromo's shipboard computer called?", a: ["MOTHER", "HAL", "FATHER", "ALICE"] },
  { c: 0, q: "The phrase \"Klaatu barada nikto\" comes from which 1951 film?", a: ["The Day the Earth Stood Still", "Forbidden Planet", "The Thing from Another World", "When Worlds Collide"] },
  { c: 0, q: "Which 1927 Fritz Lang film features the robot double of a woman named Maria?", a: ["Metropolis", "M", "Woman in the Moon", "Things to Come"] },
  { c: 0, q: "Forbidden Planet loosely adapts which Shakespeare play?", a: ["The Tempest", "Hamlet", "Macbeth", "A Midsummer Night's Dream"] },
  { c: 0, q: "What is the dark secret of Soylent Green?", a: ["It is made of people", "It causes sterility", "It is alien in origin", "It is a placebo"] },
  { c: 0, q: "In Logan's Run, at what age are citizens ritually killed?", a: ["30", "21", "40", "50"] },
  { c: 0, q: "Which 1938 radio drama caused panic with fake news bulletins of a Martian invasion?", a: ["The War of the Worlds", "The Shadow", "Flash Gordon", "Buck Rogers"] },
  { c: 0, q: "Whose Mars trilogy is titled Red Mars, Green Mars and Blue Mars?", a: ["Kim Stanley Robinson", "Ben Bova", "Andy Weir", "Ray Bradbury"] },
  { c: 0, q: "In Iain M. Banks's Culture novels, what are the godlike AIs that run the ships called?", a: ["Minds", "Cores", "Mainframes", "Overseers"] },
  { c: 0, q: "Which Octavia Butler novel pulls its narrator back in time to an antebellum plantation?", a: ["Kindred", "Dawn", "Parable of the Sower", "Wild Seed"] },
  { c: 0, q: "In Project Hail Mary, what does Ryland Grace name his alien companion?", a: ["Rocky", "Sandy", "Spidey", "Ridley"] },

  // -------------------------------------- Computer Science & Technology
  { c: 1, q: "What is the time complexity of binary search on a sorted array?", a: ["O(log n)", "O(n)", "O(n log n)", "O(1)"] },
  { c: 1, q: "Who is regarded as the first computer programmer for her notes on the Analytical Engine?", a: ["Ada Lovelace", "Grace Hopper", "Hedy Lamarr", "Joan Clarke"] },
  { c: 1, q: "In databases, what does the A in ACID stand for?", a: ["Atomicity", "Availability", "Access", "Alignment"] },
  { c: 1, q: "Which data structure works last-in, first-out?", a: ["A stack", "A queue", "A heap", "A trie"] },
  { c: 1, q: "Who proposed the 1950 test for whether a machine can think?", a: ["Alan Turing", "John von Neumann", "Claude Shannon", "Marvin Minsky"] },
  { c: 1, q: "What is the default port for HTTPS?", a: ["443", "80", "8080", "22"] },
  { c: 1, q: "Which transport protocol is connectionless and does not guarantee delivery?", a: ["UDP", "TCP", "ICMP", "FTP"] },
  { c: 1, q: "Who created the C programming language?", a: ["Dennis Ritchie", "Ken Thompson", "Brian Kernighan", "Bjarne Stroustrup"] },
  { c: 1, q: "Who created C++?", a: ["Bjarne Stroustrup", "James Gosling", "Guido van Rossum", "Anders Hejlsberg"] },
  { c: 1, q: "What does REST stand for in web APIs?", a: ["Representational State Transfer", "Remote Execution Service Transport", "Resource State Table", "Reliable Stateless Transfer"] },
  { c: 1, q: "Roughly how many addresses does IPv4 provide?", a: ["4.3 billion", "65 thousand", "18 quintillion", "340 undecillion"] },
  { c: 1, q: "Which hash function was broken in practice by the 2017 \"SHAttered\" collision attack?", a: ["SHA-1", "SHA-256", "bcrypt", "AES"] },
  { c: 1, q: "Who invented the World Wide Web?", a: ["Tim Berners-Lee", "Vint Cerf", "Marc Andreessen", "Robert Kahn"] },
  { c: 1, q: "Which sorting algorithm does Python's built-in sort use?", a: ["Timsort", "Quicksort", "Heapsort", "Introsort"] },
  { c: 1, q: "What is a function that calls itself called?", a: ["Recursive", "Reentrant", "Idempotent", "Polymorphic"] },
  { c: 1, q: "At which layer of the OSI model does TCP operate?", a: ["The transport layer", "The network layer", "The session layer", "The data link layer"] },
  { c: 1, q: "What does RAID stand for?", a: ["Redundant Array of Independent Disks", "Rapid Access Indexed Drive", "Replicated Array of Internal Devices", "Random Allocation of Indexed Data"] },
  { c: 1, q: "Who wrote The Art of Computer Programming?", a: ["Donald Knuth", "Edsger Dijkstra", "Niklaus Wirth", "Alan Kay"] },
  { c: 1, q: "Which algorithm finds shortest paths from one source when all edge weights are non-negative?", a: ["Dijkstra's algorithm", "Kruskal's algorithm", "Bellman-Ford", "Prim's algorithm"] },
  { c: 1, q: "What is 0xFF in decimal?", a: ["255", "16", "160", "512"] },
  { c: 1, q: "Which data structure usually backs a priority queue?", a: ["A heap", "A linked list", "A hash table", "A stack"] },
  { c: 1, q: "Which public-key cryptosystem rests on the difficulty of factoring large numbers?", a: ["RSA", "AES", "Diffie-Hellman", "SHA-2"] },
  { c: 1, q: "Which observation predicted that transistor counts would roughly double every two years?", a: ["Moore's Law", "Amdahl's Law", "Metcalfe's Law", "Wirth's Law"] },
  { c: 1, q: "Which program turns source code into machine code before the program is run?", a: ["A compiler", "An interpreter", "A linker", "A debugger"] },
  { c: 1, q: "What does the GIL in CPython stand for?", a: ["Global Interpreter Lock", "General Instruction Layer", "Garbage Isolation List", "Generic Import Loader"] },
  { c: 1, q: "Which two engineers designed the TCP/IP protocol suite?", a: ["Vint Cerf and Robert Kahn", "Tim Berners-Lee and Robert Cailliau", "Ken Thompson and Dennis Ritchie", "Paul Baran and Leonard Kleinrock"] },
  { c: 1, q: "What did Alan Turing prove about the halting problem?", a: ["It is undecidable", "It is NP-complete", "It is solvable in linear time", "It only applies to finite machines"] },
  { c: 1, q: "The Turing Award is the highest honour in which field?", a: ["Computing", "Mathematics", "Physics", "Cryptography"] },
  { c: 1, q: "What is the term for a bug whose outcome depends on the timing of concurrent operations?", a: ["A race condition", "A deadlock", "A memory leak", "An off-by-one error"] },
  { c: 1, q: "Which standard assigns a code point to characters in nearly every writing system?", a: ["Unicode", "ASCII", "ISO-8859-1", "EBCDIC"] },
  { c: 1, q: "What does Amdahl's Law describe?", a: ["The limit of speedup from parallelising a program", "The growth of network value with users", "The doubling of transistor density", "The cost of context switching"] },
  { c: 1, q: "Writing past the end of an allocated array causes which classic vulnerability?", a: ["A buffer overflow", "A SQL injection", "A cross-site script", "A privilege escalation"] },
  { c: 1, q: "What does MVC stand for in software architecture?", a: ["Model-View-Controller", "Multi-Version Concurrency", "Managed Virtual Container", "Modular View Compiler"] },
  { c: 1, q: "Which self-balancing binary search tree was published in 1962 by two Soviet mathematicians?", a: ["The AVL tree", "The red-black tree", "The B-tree", "The splay tree"] },
  { c: 1, q: "Which complexity class contains problems whose solutions can be verified in polynomial time?", a: ["NP", "P", "PSPACE", "EXPTIME"] },
  { c: 1, q: "Which 1993 browser popularised the web with an inline-image graphical interface?", a: ["Mosaic", "Netscape Navigator", "Lynx", "Internet Explorer"] },
  { c: 1, q: "Which protocol carries email between mail servers?", a: ["SMTP", "IMAP", "POP3", "HTTP"] },
  { c: 1, q: "Which hash function does Bitcoin's proof of work rely on?", a: ["SHA-256", "MD5", "Scrypt", "Keccak"] },
  { c: 1, q: "Which sorting algorithm is stable and guarantees O(n log n) in the worst case?", a: ["Merge sort", "Quicksort", "Heapsort", "Shell sort"] },
  { c: 1, q: "Which computer, unveiled in 1946, is often called the first general-purpose electronic computer?", a: ["ENIAC", "Colossus", "UNIVAC", "EDSAC"] },
  { c: 1, q: "In Big-O notation, what is the average time complexity of a hash table lookup?", a: ["O(1)", "O(log n)", "O(n)", "O(n log n)"] },
  { c: 1, q: "What does DNS do?", a: ["Translates domain names into IP addresses", "Encrypts web traffic", "Routes packets between networks", "Assigns local IP addresses"] },
  { c: 1, q: "Which Dutch computer scientist wrote \"Go To Statement Considered Harmful\"?", a: ["Edsger Dijkstra", "Niklaus Wirth", "Guido van Rossum", "Andrew Tanenbaum"] },
  { c: 1, q: "Which language, first released in 2015, uses ownership and borrowing for memory safety?", a: ["Rust", "Go", "Swift", "Zig"] },
  { c: 1, q: "What is the term for an algorithm's guaranteed behaviour on its most unfavourable input?", a: ["Worst-case complexity", "Amortised complexity", "Average-case complexity", "Asymptotic bound"] },
  { c: 1, q: "Which architecture stores program instructions and data in the same memory?", a: ["The von Neumann architecture", "The Harvard architecture", "The dataflow architecture", "The RISC architecture"] },
  { c: 1, q: "What is the worst-case time complexity of quicksort?", a: ["O(n²)", "O(n log n)", "O(n)", "O(2ⁿ)"] },
  { c: 1, q: "Which graph traversal explores level by level using a queue?", a: ["Breadth-first search", "Depth-first search", "Dijkstra's algorithm", "A* search"] },
  { c: 1, q: "Which technique solves problems by storing the answers to overlapping subproblems?", a: ["Dynamic programming", "Divide and conquer", "Greedy search", "Branch and bound"] },
  { c: 1, q: "Which data structure achieves amortised O(1) appends by doubling its capacity when full?", a: ["A dynamic array", "A linked list", "A binary heap", "A skip list"] },
  { c: 1, q: "Which probabilistic data structure answers set-membership queries with occasional false positives but never false negatives?", a: ["A Bloom filter", "A B-tree", "A count-min sketch", "A red-black tree"] },
  { c: 1, q: "Which algorithm builds a minimum spanning tree by repeatedly adding the cheapest edge that does not create a cycle?", a: ["Kruskal's algorithm", "Prim's algorithm", "Dijkstra's algorithm", "Borůvka's algorithm"] },
  { c: 1, q: "Which single-source shortest-path algorithm copes with negative edge weights?", a: ["Bellman-Ford", "Dijkstra's algorithm", "A* search", "Floyd's cycle detection"] },
  { c: 1, q: "What ordering of a directed acyclic graph lists every node before all nodes that depend on it?", a: ["A topological sort", "An in-order traversal", "A lexicographic sort", "A level ordering"] },
  { c: 1, q: "What is the height of a balanced binary search tree with n nodes, in Big-O terms?", a: ["O(log n)", "O(n)", "O(1)", "O(√n)"] },

  // ------------------------------------------------- Mythology & Folklore
  { c: 2, q: "What is the name of the world tree in Norse mythology?", a: ["Yggdrasil", "Irminsul", "Mimameid", "Laerad"] },
  { c: 2, q: "Which squirrel carries insults up and down the Norse world tree?", a: ["Ratatoskr", "Nidhogg", "Vedrfolnir", "Heidrun"] },
  { c: 2, q: "Which dragon gnaws at the roots of Yggdrasil?", a: ["Nidhogg", "Fafnir", "Jormungandr", "Grendel"] },
  { c: 2, q: "Which Norse god sacrificed his hand so the wolf Fenrir could be bound?", a: ["Tyr", "Thor", "Heimdall", "Vidar"] },
  { c: 2, q: "What is Odin's eight-legged horse called?", a: ["Sleipnir", "Gullfaxi", "Grani", "Svadilfari"] },
  { c: 2, q: "What is the name of the dwarven-forged ribbon that binds Fenrir?", a: ["Gleipnir", "Gungnir", "Draupnir", "Brisingamen"] },
  { c: 2, q: "Who are the three Norse fates who spin destiny beneath the world tree?", a: ["The Norns", "The Valkyries", "The Disir", "The Vanir"] },
  { c: 2, q: "Which serpent lies in the sea encircling Midgard?", a: ["Jormungandr", "Nidhogg", "Fafnir", "Ouroboros"] },
  { c: 2, q: "What was used to kill the Norse god Baldr?", a: ["A dart of mistletoe", "A golden spear", "An iron sword", "A poisoned arrow"] },
  { c: 2, q: "What are Odin's two ravens called?", a: ["Huginn and Muninn", "Geri and Freki", "Skoll and Hati", "Tanngrisnir and Tanngnjostr"] },
  { c: 2, q: "Which primordial realm of Norse myth is the land of ice and mist?", a: ["Niflheim", "Muspelheim", "Jotunheim", "Svartalfheim"] },
  { c: 2, q: "Which fire giant will set the world ablaze at Ragnarok?", a: ["Surtr", "Ymir", "Hrungnir", "Thrym"] },
  { c: 2, q: "Which Greek Titan swallowed his children to escape a prophecy?", a: ["Cronus", "Atlas", "Hyperion", "Oceanus"] },
  { c: 2, q: "Who stole fire from the gods and was chained to a rock as punishment?", a: ["Prometheus", "Epimetheus", "Sisyphus", "Atlas"] },
  { c: 2, q: "Which river of the Greek underworld causes forgetfulness?", a: ["The Lethe", "The Styx", "The Acheron", "The Cocytus"] },
  { c: 2, q: "Who ferries the dead across the rivers of the Greek underworld?", a: ["Charon", "Hermes", "Thanatos", "Hypnos"] },
  { c: 2, q: "Which three goddesses spin, measure and cut the thread of life in Greek myth?", a: ["The Moirai", "The Erinyes", "The Charites", "The Horae"] },
  { c: 2, q: "Eating which fruit bound Persephone to the underworld?", a: ["The pomegranate", "The fig", "The apple", "The quince"] },
  { c: 2, q: "Which musician nearly rescued Eurydice from Hades but looked back too soon?", a: ["Orpheus", "Apollo", "Pan", "Arion"] },
  { c: 2, q: "Which hero tamed Pegasus and slew the Chimera?", a: ["Bellerophon", "Perseus", "Theseus", "Cadmus"] },
  { c: 2, q: "What was the name of the hundred-eyed giant who served Hera?", a: ["Argus", "Briareus", "Typhon", "Polyphemus"] },
  { c: 2, q: "Which Greek primordial deity personifies the sky?", a: ["Uranus", "Gaia", "Erebus", "Tartarus"] },
  { c: 2, q: "Which Egyptian god murdered and dismembered his brother Osiris?", a: ["Set", "Horus", "Anubis", "Sobek"] },
  { c: 2, q: "Against what is the heart of the dead weighed in Egyptian myth?", a: ["The feather of Ma'at", "A golden scarab", "The eye of Horus", "A grain of sand"] },
  { c: 2, q: "Which Egyptian demoness devours hearts that fail the weighing?", a: ["Ammit", "Sekhmet", "Serqet", "Taweret"] },
  { c: 2, q: "Which Egyptian god of writing has the head of an ibis?", a: ["Thoth", "Ptah", "Khnum", "Montu"] },
  { c: 2, q: "What is the group of nine great deities of Heliopolis called?", a: ["The Ennead", "The Ogdoad", "The Triad", "The Duat"] },
  { c: 2, q: "In the Epic of Gilgamesh, who is Gilgamesh's wild-man companion?", a: ["Enkidu", "Utnapishtim", "Humbaba", "Shamash"] },
  { c: 2, q: "Which Babylonian god slew the sea dragon Tiamat to create the world?", a: ["Marduk", "Enlil", "Anu", "Nergal"] },
  { c: 2, q: "What steals the plant of immortality from Gilgamesh while he bathes?", a: ["A snake", "An eagle", "A scorpion-man", "A fish"] },
  { c: 2, q: "Which Irish hero single-handedly defended Ulster in the Cattle Raid of Cooley?", a: ["Cú Chulainn", "Fionn mac Cumhaill", "Oisín", "Lugh"] },
  { c: 2, q: "Which supernatural race of Irish myth retreated into the hollow hills?", a: ["The Tuatha Dé Danann", "The Fomorians", "The Fir Bolg", "The Milesians"] },
  { c: 2, q: "Which wailing spirit of Irish folklore foretells a death in the family?", a: ["The banshee", "The pooka", "The dullahan", "The changeling"] },
  { c: 2, q: "In Scottish and Irish folklore, which seal-people shed their skins to walk on land?", a: ["Selkies", "Kelpies", "Merrows", "Finfolk"] },
  { c: 2, q: "Which shape-shifting water horse of Scottish folklore drowns those who ride it?", a: ["The kelpie", "The selkie", "The brownie", "The redcap"] },
  { c: 2, q: "Which witch of Slavic folklore lives in a hut that stands on chicken legs?", a: ["Baba Yaga", "Morana", "Rusalka", "Vasilisa"] },
  { c: 2, q: "Where does Koschei the Deathless hide his death in Slavic folklore?", a: ["In a needle inside an egg", "In his sword", "Under his throne", "In a raven's heart"] },
  { c: 2, q: "Which household spirit of Slavic folklore protects the family home?", a: ["The domovoi", "The leshy", "The vodyanoy", "The bannik"] },
  { c: 2, q: "Which fox spirit of Japanese folklore grows additional tails as it ages?", a: ["The kitsune", "The tanuki", "The bakeneko", "The tengu"] },
  { c: 2, q: "Which Japanese river imp carries water in a dish on its head?", a: ["The kappa", "The oni", "The tengu", "The yuki-onna"] },
  { c: 2, q: "Which Japanese sun goddess hid in a cave and plunged the world into darkness?", a: ["Amaterasu", "Izanami", "Uzume", "Benzaiten"] },
  { c: 2, q: "Which Japanese storm god slew the eight-headed serpent Yamata no Orochi?", a: ["Susanoo", "Tsukuyomi", "Raijin", "Hachiman"] },
  { c: 2, q: "In Chinese myth, which goddess repaired the broken sky with five-coloured stones?", a: ["Nüwa", "Chang'e", "Xiwangmu", "Guanyin"] },
  { c: 2, q: "Which Chinese moon goddess floated to the moon after drinking an elixir of immortality?", a: ["Chang'e", "Nüwa", "Mazu", "He Xiangu"] },
  { c: 2, q: "Which feathered serpent god was worshipped by the Aztecs?", a: ["Quetzalcoatl", "Tezcatlipoca", "Tlaloc", "Xipe Totec"] },
  { c: 2, q: "Which Aztec god of war and the sun guided the founding of Tenochtitlan?", a: ["Huitzilopochtli", "Quetzalcoatl", "Mictlantecuhtli", "Xochipilli"] },
  { c: 2, q: "Which Maya text tells of the Hero Twins Hunahpu and Xbalanque?", a: ["The Popol Vuh", "The Chilam Balam", "The Dresden Codex", "The Florentine Codex"] },
  { c: 2, q: "Which Polynesian trickster hero snared the sun to slow its passage across the sky?", a: ["Maui", "Tane", "Tangaroa", "Rongo"] },
  { c: 2, q: "Which West African and Caribbean trickster takes the form of a spider?", a: ["Anansi", "Eshu", "Br'er Rabbit", "Legba"] },
  { c: 2, q: "In Jewish folklore, what clay being was animated to protect the Prague ghetto?", a: ["The golem", "The dybbuk", "The seraph", "The nephil"] },
  { c: 2, q: "Which ghostly procession of huntsmen rides the night sky in European folklore?", a: ["The Wild Hunt", "The Danse Macabre", "The Furious Host of Rome", "The Sluagh"] },
  { c: 2, q: "Which horned companion of St Nicholas punishes naughty children in Alpine folklore?", a: ["Krampus", "Knecht Ruprecht", "Belsnickel", "Perchta"] },
  { c: 2, q: "Which weeping ghost of Latin American folklore wanders waterways mourning her drowned children?", a: ["La Llorona", "La Catrina", "El Cucuy", "La Siguanaba"] },
  { c: 2, q: "Which cannibal spirit of Algonquian folklore embodies insatiable hunger and winter?", a: ["The wendigo", "The skinwalker", "The sasquatch", "The thunderbird"] },
  { c: 2, q: "In Arthurian legend, which enchantress is the Lady of the Lake?", a: ["Nimue", "Morgan le Fay", "Guinevere", "Elaine of Corbenic"] },

  // ------------------------------------------------------- Anime & Manga
  { c: 3, q: "Which studio did Hideaki Anno found after leaving Gainax?", a: ["Studio Khara", "Studio Trigger", "Studio 4°C", "Science Saru"] },
  { c: 3, q: "Which Satoshi Kon film traces a retiring actress through the roles of her career?", a: ["Millennium Actress", "Perfect Blue", "Paprika", "Tokyo Godfathers"] },
  { c: 3, q: "In which magazine did Hayao Miyazaki serialise the Nausicaä manga?", a: ["Animage", "Newtype", "Animedia", "OUT"] },
  { c: 3, q: "What was the first film produced by Studio Ghibli after its founding?", a: ["Castle in the Sky", "Nausicaä of the Valley of the Wind", "My Neighbour Totoro", "Grave of the Fireflies"] },
  { c: 3, q: "What is Griffith's name after his rebirth as a member of the God Hand?", a: ["Femto", "Void", "Slan", "Conrad"] },
  { c: 3, q: "Which JoJo part takes place in the town of Morioh in 1999?", a: ["Diamond Is Unbreakable", "Golden Wind", "Stardust Crusaders", "Stone Ocean"] },
  { c: 3, q: "What is the name of Gol D. Roger's pirate ship?", a: ["The Oro Jackson", "The Moby Dick", "The Red Force", "The Going Merry"] },
  { c: 3, q: "Who served as Gol D. Roger's first mate?", a: ["Silvers Rayleigh", "Crocus", "Shanks", "Buggy"] },
  { c: 3, q: "In Hunter x Hunter, what is the name of the Chimera Ant King?", a: ["Meruem", "Neferpitou", "Shaiapouf", "Menthuthuyoupi"] },
  { c: 3, q: "What weapon does Netero use to finally kill the Chimera Ant King?", a: ["A Poor Man's Rose bomb", "The Zero Hand", "The Hundred-Type Guanyin Bodhisattva", "A Nen-erasing seal"] },
  { c: 3, q: "What is the name of Kurapika's massacred clan?", a: ["The Kurta", "The Zoldyck", "The Freecss", "The Nostrade"] },
  { c: 3, q: "In Evangelion, what is the name of the spear that can pierce an AT Field?", a: ["The Lance of Longinus", "The Sword of Damocles", "The Blade of Gungnir", "The Spear of Ascalon"] },
  { c: 3, q: "Which shadowy committee secretly directs NERV in Evangelion?", a: ["SEELE", "GEHIRN", "WILLE", "The Marduk Institute"] },
  { c: 3, q: "Who directed the 1985 art film Angel's Egg?", a: ["Mamoru Oshii", "Rintaro", "Gisaburo Sugii", "Osamu Dezaki"] },
  { c: 3, q: "Royal Space Force: The Wings of Honneamise was the debut film of which studio?", a: ["Gainax", "Madhouse", "Production I.G", "Sunrise"] },
  { c: 3, q: "In Legend of the Galactic Heroes, who commands the Free Planets Alliance's 13th Fleet?", a: ["Yang Wen-li", "Reinhard von Lohengramm", "Siegfried Kircheis", "Paul von Oberstein"] },
  { c: 3, q: "Which Leiji Matsumoto series follows young Tetsuro aboard a train through space?", a: ["Galaxy Express 999", "Space Battleship Yamato", "Captain Harlock", "Queen Emeraldas"] },
  { c: 3, q: "What is the name of the virtual world in Summer Wars?", a: ["OZ", "U", "ALfheim", "The Wired"] },
  { c: 3, q: "Who directed The Girl Who Leapt Through Time and Wolf Children?", a: ["Mamoru Hosoda", "Makoto Shinkai", "Masaaki Yuasa", "Naoko Yamada"] },
  { c: 3, q: "Which Masaaki Yuasa series adapts Taiyo Matsumoto's manga about competitive table tennis?", a: ["Ping Pong the Animation", "The Tatami Galaxy", "Devilman Crybaby", "Kaiba"] },
  { c: 3, q: "In Serial Experiments Lain, what is the global communications network called?", a: ["The Wired", "The Grid", "OZ", "The Sprawl"] },
  { c: 3, q: "Which mangaka created both Urusei Yatsura and Inuyasha?", a: ["Rumiko Takahashi", "Naoko Takeuchi", "Riyoko Ikeda", "Moto Hagio"] },
  { c: 3, q: "The mangaka collective CLAMP consists of how many members?", a: ["Four", "Two", "Three", "Five"] },
  { c: 3, q: "Hunter x Hunter creator Yoshihiro Togashi is married to which mangaka?", a: ["Naoko Takeuchi", "Rumiko Takahashi", "Hiromu Arakawa", "Ai Yazawa"] },
  { c: 3, q: "What bounty is on Vash the Stampede's head in Trigun?", a: ["$$60 billion", "$$1 million", "$$30 billion", "$$100 billion"] },
  { c: 3, q: "Takehiko Inoue's Vagabond retells the life of which swordsman?", a: ["Miyamoto Musashi", "Sasaki Kojiro", "Yagyu Jubei", "Oda Nobunaga"] },
  { c: 3, q: "Which studio produced Frieren: Beyond Journey's End?", a: ["Madhouse", "MAPPA", "Bones", "Wit Studio"] },
  { c: 3, q: "In Attack on Titan, who was the original Founding Titan and ancestor of all Eldians?", a: ["Ymir Fritz", "Karl Fritz", "Rod Reiss", "Dina Fritz"] },
  { c: 3, q: "In Attack on Titan, what is the dimension connecting all Eldians called?", a: ["Paths", "The Coordinate", "The Rumbling", "The Walls"] },
  { c: 3, q: "In Death Note, at which orphanage were Near and Mello raised?", a: ["Wammy's House", "Whitby House", "The Yagami Institute", "Quillsh Hall"] },
  { c: 3, q: "What alias does Rintaro Okabe grandly style himself with in Steins;Gate?", a: ["Hououin Kyouma", "Makise Kyouma", "John Titor", "Faris NyanNyan"] },
  { c: 3, q: "Which company created the Fate franchise and Tsukihime?", a: ["Type-Moon", "Key", "Nitroplus", "07th Expansion"] },
  { c: 3, q: "Which studio is known for the distinctive head-tilts of the Monogatari series?", a: ["Shaft", "Trigger", "Silver Link", "A-1 Pictures"] },
  { c: 3, q: "Who wrote both Puella Magi Madoka Magica and Psycho-Pass?", a: ["Gen Urobuchi", "Mari Okada", "Jun Maeda", "Kinoko Nasu"] },
  { c: 3, q: "In Madoka Magica, what do magical girls become when they fall into despair?", a: ["Witches", "Wraiths", "Familiars", "Incubators"] },
  { c: 3, q: "What is the weapon carried by inspectors in Psycho-Pass that reads crime coefficients?", a: ["The Dominator", "The Executor", "The Sibyl", "The Arbiter"] },
  { c: 3, q: "In Re:Zero, what is Subaru's ability called?", a: ["Return by Death", "Checkpoint", "Authority of Sloth", "Time Leap"] },
  { c: 3, q: "Which Go Nagai character is revealed to be Satan in Devilman?", a: ["Ryo Asuka", "Akira Fudo", "Miki Makimura", "Sirene"] },
  { c: 3, q: "Riyoko Ikeda's The Rose of Versailles is set during which historical period?", a: ["The French Revolution", "The Napoleonic Wars", "The Renaissance", "The Belle Époque"] },
  { c: 3, q: "Which 1963 series was the first half-hour television anime?", a: ["Astro Boy", "Gigantor", "Speed Racer", "Kimba the White Lion"] },
  { c: 3, q: "In FLCL, what does Haruko ride?", a: ["A Vespa scooter", "A Harley-Davidson", "A bicycle", "A skateboard"] },
  { c: 3, q: "Which studio co-produced FLCL with Gainax?", a: ["Production I.G", "Madhouse", "Sunrise", "Pierrot"] },
  { c: 3, q: "In Made in Abyss, what kind of being is Nanachi?", a: ["A Hollow", "A Cave Raider", "A Praying Skeleton", "An Interference Unit"] },
  { c: 3, q: "Which CG studio animated Land of the Lustrous and Beastars?", a: ["Orange", "Polygon Pictures", "Sanzigen", "Khara"] },
  { c: 3, q: "What is the Japanese term for a key animation drawing?", a: ["Genga", "Douga", "Settei", "Eizou"] },
  { c: 3, q: "Which magazine has serialised Berserk?", a: ["Young Animal", "Weekly Shonen Jump", "Big Comic Spirits", "Monthly Shonen Gangan"] },
  { c: 3, q: "Which Nen category does Gon Freecss belong to?", a: ["Enhancement", "Transmutation", "Emission", "Manipulation"] },
  { c: 3, q: "What is Spike Spiegel's ship called in Cowboy Bebop?", a: ["The Swordfish II", "The Red Tail", "The Hammerhead", "The Bebop"] },
  { c: 3, q: "In Death Note, what does the shinigami eye deal cost?", a: ["Half of the user's remaining lifespan", "The user's memories", "The user's name", "A year of the user's life"] },
  { c: 3, q: "Which mangaka drew Death Note from Tsugumi Ohba's scripts?", a: ["Takeshi Obata", "Tite Kubo", "Hiromu Arakawa", "Yusuke Murata"] },
  { c: 3, q: "What breed of dog is Ein in Cowboy Bebop?", a: ["A Welsh Corgi", "A Shiba Inu", "An Akita", "A Beagle"] },
  { c: 3, q: "Who composed the soundtracks for both Attack on Titan and Kill la Kill?", a: ["Hiroyuki Sawano", "Yuki Kajiura", "Kenji Kawai", "Yoko Kanno"] },
  { c: 3, q: "Which composer scored the 1995 Ghost in the Shell film with its haunting choral chant?", a: ["Kenji Kawai", "Joe Hisaishi", "Yoko Kanno", "Susumu Hirasawa"] },
  { c: 3, q: "Which composer was Satoshi Kon's regular collaborator, scoring Paprika and Paranoia Agent?", a: ["Susumu Hirasawa", "Kenji Kawai", "Yoko Shimomura", "Michiru Oshima"] },
  { c: 3, q: "Which Kyoto Animation film adapts the manga about the deaf girl Shoko Nishimiya?", a: ["A Silent Voice", "Liz and the Blue Bird", "K-On! the Movie", "Violet Evergarden: the Movie"] },

  // ------------------------------------------------------ Machine Learning
  { c: 4, q: "What is the VC dimension of a linear classifier in d dimensions, including a bias term?", a: ["d + 1", "d", "2d", "d²"] },
  { c: 4, q: "Which theorem states that no learning algorithm beats any other when averaged over all possible problems?", a: ["The No Free Lunch theorem", "The universal approximation theorem", "The representer theorem", "Cover's theorem"] },
  { c: 4, q: "Which lemma guarantees that random projections nearly preserve pairwise distances?", a: ["Johnson-Lindenstrauss", "Borel-Cantelli", "Neyman-Pearson", "Fatou's lemma"] },
  { c: 4, q: "In variational autoencoders, which trick lets gradients flow through the sampling step?", a: ["The reparameterization trick", "The kernel trick", "Straight-through estimation", "Gumbel-max sampling"] },
  { c: 4, q: "What objective do variational autoencoders maximise?", a: ["The evidence lower bound", "The likelihood ratio", "The mutual information", "The posterior mode"] },
  { c: 4, q: "Variational inference minimises which divergence, measured from the approximation to the true posterior?", a: ["KL(q‖p)", "KL(p‖q)", "Total variation", "Hellinger distance"] },
  { c: 4, q: "Which property does KL divergence lack that prevents it from being a true metric?", a: ["Symmetry", "Non-negativity", "Convexity", "Boundedness"] },
  { c: 4, q: "At optimality, the original GAN objective implicitly minimises which divergence?", a: ["Jensen-Shannon", "Kullback-Leibler", "Wasserstein", "Chi-squared"] },
  { c: 4, q: "What failure mode makes a GAN generator produce only a few distinct outputs?", a: ["Mode collapse", "Posterior collapse", "Gradient explosion", "Catastrophic forgetting"] },
  { c: 4, q: "The Wasserstein GAN replaces the JS divergence with which distance?", a: ["The earth mover's distance", "The Mahalanobis distance", "The Hamming distance", "The cosine distance"] },
  { c: 4, q: "Which constraint must a WGAN critic satisfy, often enforced with a gradient penalty?", a: ["1-Lipschitz continuity", "Orthogonality", "Unit norm weights", "Monotonicity"] },
  { c: 4, q: "In scaled dot-product attention, what is the query-key dot product divided by?", a: ["The square root of the key dimension", "The sequence length", "The number of heads", "The embedding dimension"] },
  { c: 4, q: "Which normalisation is used inside transformer blocks?", a: ["Layer normalisation", "Batch normalisation", "Instance normalisation", "Group normalisation"] },
  { c: 4, q: "What do the sinusoidal signals added to embeddings in the original transformer encode?", a: ["Token positions", "Token frequencies", "Attention weights", "Segment boundaries"] },
  { c: 4, q: "Which 2017 paper introduced the transformer architecture?", a: ["Attention Is All You Need", "Deep Residual Learning", "Sequence to Sequence Learning", "Neural Machine Translation by Jointly Learning to Align"] },
  { c: 4, q: "The Adam optimiser combines momentum with which other adaptive method?", a: ["RMSProp", "AdaGrad", "Nesterov descent", "L-BFGS"] },
  { c: 4, q: "Why does Adam apply bias correction to its moment estimates?", a: ["They are initialised at zero and biased early in training", "They overflow without it", "It enforces a learning-rate schedule", "It guarantees convergence"] },
  { c: 4, q: "Which LSTM gate decides what to erase from the cell state?", a: ["The forget gate", "The input gate", "The output gate", "The reset gate"] },
  { c: 4, q: "Residual connections were introduced in ResNet to combat which problem in very deep networks?", a: ["Degradation of training accuracy with depth", "Overfitting", "Exploding memory use", "Dead neurons"] },
  { c: 4, q: "Which theorem says a network with one hidden layer can approximate any continuous function on a compact set?", a: ["The universal approximation theorem", "The No Free Lunch theorem", "The Nyquist theorem", "The Perceptron convergence theorem"] },
  { c: 4, q: "Who introduced the PAC (probably approximately correct) learning framework?", a: ["Leslie Valiant", "Vladimir Vapnik", "Judea Pearl", "Michael Jordan"] },
  { c: 4, q: "Which complexity measure bounds generalisation via a hypothesis class's correlation with random noise?", a: ["Rademacher complexity", "Kolmogorov complexity", "Cyclomatic complexity", "Sample complexity"] },
  { c: 4, q: "What does the EM algorithm guarantee about the data likelihood at each iteration?", a: ["It never decreases", "It strictly increases", "It converges to the global optimum", "It stays constant"] },
  { c: 4, q: "In a Gaussian process, what does the kernel function define?", a: ["The covariance between function values", "The mean prediction", "The observation noise", "The number of basis functions"] },
  { c: 4, q: "Which theorem justifies writing the optimal solution as a kernel expansion over the training points?", a: ["The representer theorem", "Mercer's theorem", "The kernel trick", "Cover's theorem"] },
  { c: 4, q: "What condition must a kernel satisfy to correspond to an inner product in some feature space?", a: ["Positive semi-definiteness", "Differentiability", "Translation invariance", "Boundedness"] },
  { c: 4, q: "What is the conjugate prior of the Bernoulli likelihood?", a: ["The Beta distribution", "The Gaussian distribution", "The Gamma distribution", "The Dirichlet distribution"] },
  { c: 4, q: "In a Bayesian network, what is the minimal set of nodes that renders a node independent of all others?", a: ["Its Markov blanket", "Its parents", "Its children", "Its ancestors"] },
  { c: 4, q: "Which MCMC method samples each variable in turn from its full conditional distribution?", a: ["Gibbs sampling", "Metropolis-Hastings", "Rejection sampling", "Importance sampling"] },
  { c: 4, q: "Which MCMC method simulates physical dynamics with auxiliary momentum to propose distant states?", a: ["Hamiltonian Monte Carlo", "Gibbs sampling", "Slice sampling", "Simulated annealing"] },
  { c: 4, q: "Which RL algorithm learns action values off-policy using a max over next-state actions?", a: ["Q-learning", "SARSA", "REINFORCE", "Actor-critic"] },
  { c: 4, q: "What is the main practical drawback of the REINFORCE policy-gradient estimator?", a: ["High variance", "High bias", "It requires a model of the environment", "It only works for discrete actions"] },
  { c: 4, q: "Subtracting which quantity from returns reduces policy-gradient variance without adding bias?", a: ["A state-value baseline", "The entropy bonus", "The discount factor", "The advantage clip"] },
  { c: 4, q: "Which equation expresses a state's value as immediate reward plus discounted successor value?", a: ["The Bellman equation", "The Fokker-Planck equation", "The Nernst equation", "The Chapman-Kolmogorov equation"] },
  { c: 4, q: "Which phenomenon shows test error falling a second time as models grow past the interpolation threshold?", a: ["Double descent", "Grokking", "Mode connectivity", "Catastrophic forgetting"] },
  { c: 4, q: "Which hypothesis claims dense networks contain sparse subnetworks that train to full accuracy alone?", a: ["The lottery ticket hypothesis", "The manifold hypothesis", "The linear representation hypothesis", "The scaling hypothesis"] },
  { c: 4, q: "In the infinite-width limit, gradient-descent training of a network is equivalent to regression with which kernel?", a: ["The neural tangent kernel", "The RBF kernel", "The Fisher kernel", "The arc-cosine kernel"] },
  { c: 4, q: "Which contrastive objective, used by SimCLR, is a softmax over similarities against negative pairs?", a: ["InfoNCE", "Triplet loss", "Hinge loss", "Barlow Twins"] },
  { c: 4, q: "Which pretraining objective does BERT use alongside next-sentence prediction?", a: ["Masked language modelling", "Autoregressive prediction", "Denoising diffusion", "Contrastive alignment"] },
  { c: 4, q: "Which fine-tuning method learns low-rank update matrices while freezing the base weights?", a: ["LoRA", "Prefix tuning", "Distillation", "Quantisation-aware training"] },
  { c: 4, q: "In RLHF, what model converts human preference data into a training signal for the policy?", a: ["A reward model", "A critic network", "A world model", "A discriminator"] },
  { c: 4, q: "Which RL algorithm with a clipped surrogate objective is the standard choice in RLHF?", a: ["PPO", "TRPO", "DDPG", "A3C"] },
  { c: 4, q: "The Chinchilla scaling laws recommend roughly how many training tokens per model parameter?", a: ["About 20", "About 2", "About 200", "About 2000"] },
  { c: 4, q: "In DDPM-style diffusion models, what does the network usually learn to predict at each step?", a: ["The noise that was added", "The clean image directly", "The variance schedule", "The class label"] },
  { c: 4, q: "Training a diffusion model is equivalent to which score-based technique?", a: ["Denoising score matching", "Contrastive divergence", "Noise contrastive estimation", "Maximum mean discrepancy"] },
  { c: 4, q: "Which t-SNE hyperparameter loosely sets the effective number of neighbours per point?", a: ["Perplexity", "Momentum", "Learning rate", "Early exaggeration"] },
  { c: 4, q: "Spectral clustering partitions data using the eigenvectors of which matrix?", a: ["The graph Laplacian", "The Gram matrix", "The Hessian", "The confusion matrix"] },
  { c: 4, q: "Which bandit algorithm adds a visit-count exploration bonus, embodying optimism under uncertainty?", a: ["UCB", "Epsilon-greedy", "Softmax exploration", "Gradient bandit"] },
  { c: 4, q: "Which bandit strategy chooses actions by sampling from the posterior over their rewards?", a: ["Thompson sampling", "UCB", "Epsilon-greedy", "Boltzmann exploration"] },
  { c: 4, q: "Which loss down-weights easy examples to focus training on hard ones in dense detection?", a: ["Focal loss", "Hinge loss", "Huber loss", "Dice loss"] },
  { c: 4, q: "XGBoost fits each new tree using which information from the loss function?", a: ["First and second derivatives", "Only the residuals", "The raw labels", "Feature importances"] },
  { c: 4, q: "Which game-theoretic method attributes a prediction to features by their average marginal contribution?", a: ["Shapley values", "LIME", "Saliency maps", "Integrated gradients"] },
  { c: 4, q: "In very high dimensions, what happens to the ratio between nearest and farthest neighbour distances?", a: ["It approaches one", "It approaches zero", "It grows without bound", "It oscillates"] },
  { c: 4, q: "Interpreting dropout at test time as sampling yields an approximation to what?", a: ["Bayesian model uncertainty", "Ensemble distillation", "Data augmentation", "Weight decay"] },
  { c: 4, q: "What does the temperature parameter of a softmax control?", a: ["The sharpness of the output distribution", "The gradient magnitude", "The vocabulary size", "The sampling seed"] },

  // --------------------------------------------------------- Video Games
  { c: 5, q: "Which Atari game was famously buried in a New Mexico landfill after flopping?", a: ["E.T. the Extra-Terrestrial", "Pac-Man", "Pitfall!", "Adventure"] },
  { c: 5, q: "Who created Mario and The Legend of Zelda?", a: ["Shigeru Miyamoto", "Satoru Iwata", "Gunpei Yokoi", "Hiroshi Yamauchi"] },
  { c: 5, q: "Which game engine is made by Epic Games?", a: ["Unreal Engine", "Unity", "CryEngine", "Source"] },
  { c: 5, q: "Which studio released Doom in 1993?", a: ["id Software", "3D Realms", "Epic MegaGames", "Valve"] },
  { c: 5, q: "Who composed the music for Super Mario Bros. and The Legend of Zelda?", a: ["Koji Kondo", "Nobuo Uematsu", "Yoko Shimomura", "Yuzo Koshiro"] },
  { c: 5, q: "Which was Sega's final home console?", a: ["The Dreamcast", "The Saturn", "The Mega Drive", "The Game Gear"] },
  { c: 5, q: "What was Mario originally called in Donkey Kong?", a: ["Jumpman", "Mr. Video", "Kong Man", "Pauline's Hero"] },
  { c: 5, q: "Which studio developed The Witcher 3?", a: ["CD Projekt Red", "Bethesda", "BioWare", "Larian"] },
  { c: 5, q: "In Dark Souls, what do you spend to level up?", a: ["Souls", "Blood echoes", "Runes", "Embers"] },
  { c: 5, q: "Which studio developed Elden Ring?", a: ["FromSoftware", "Team Ninja", "Platinum Games", "Atlus"] },
  { c: 5, q: "Which novelist built the background world of Elden Ring with Hidetaka Miyazaki?", a: ["George R. R. Martin", "Neil Gaiman", "Brandon Sanderson", "Patrick Rothfuss"] },
  { c: 5, q: "Which 1998 Nintendo 64 game is routinely called one of the greatest ever made?", a: ["The Legend of Zelda: Ocarina of Time", "GoldenEye 007", "Banjo-Kazooie", "Perfect Dark"] },
  { c: 5, q: "Which was the best-selling game on the SNES?", a: ["Super Mario World", "Super Mario Kart", "Donkey Kong Country", "The Legend of Zelda: A Link to the Past"] },
  { c: 5, q: "Brendan Greene, the creator of PUBG, is better known by which handle?", a: ["PlayerUnknown", "Bluehole", "Battle Royale", "Irish Gamer"] },
  { c: 5, q: "Which processor powered the PlayStation 3?", a: ["The Cell", "The Emotion Engine", "The Xenon", "The Jaguar"] },
  { c: 5, q: "Which studio makes the Grand Theft Auto series?", a: ["Rockstar", "Take-Two Interactive", "Ubisoft", "2K Czech"] },
  { c: 5, q: "What does the name Sega come from?", a: ["Service Games", "Sensational Gaming", "Segasonic", "Seiko Games"] },
  { c: 5, q: "Which game is set in the underwater city of Rapture?", a: ["BioShock", "BioShock Infinite", "SOMA", "Subnautica"] },
  { c: 5, q: "Which game is set in the floating city of Columbia?", a: ["BioShock Infinite", "BioShock 2", "Dishonored", "Skies of Arcadia"] },
  { c: 5, q: "Which Final Fantasy game introduced Cloud Strife?", a: ["Final Fantasy VII", "Final Fantasy VI", "Final Fantasy VIII", "Final Fantasy X"] },
  { c: 5, q: "Who composed the music for the early Final Fantasy games?", a: ["Nobuo Uematsu", "Yasunori Mitsuda", "Koji Kondo", "Motoi Sakuraba"] },
  { c: 5, q: "What is the name of the murderous AI in Portal?", a: ["GLaDOS", "SHODAN", "Wheatley", "AM"] },
  { c: 5, q: "Which series features the Umbrella Corporation?", a: ["Resident Evil", "Silent Hill", "Dead Space", "The Evil Within"] },
  { c: 5, q: "Which Nintendo handheld introduced a second, touch-sensitive screen?", a: ["The Nintendo DS", "The Game Boy Advance", "The 3DS", "The Virtual Boy"] },
  { c: 5, q: "Which Blizzard MMORPG launched in 2004?", a: ["World of Warcraft", "Diablo II", "EverQuest", "Guild Wars"] },
  { c: 5, q: "Which 1985 game is credited with reviving the American console market?", a: ["Super Mario Bros.", "Duck Hunt", "Donkey Kong", "Tetris"] },
  { c: 5, q: "What was Sony's first handheld console?", a: ["The PlayStation Portable", "The PlayStation Vita", "The PocketStation", "The PSX"] },
  { c: 5, q: "Which 2019 Hideo Kojima game stars Norman Reedus as a courier?", a: ["Death Stranding", "Metal Gear Solid V", "Days Gone", "Control"] },
  { c: 5, q: "Which Capcom character is nicknamed the Blue Bomber?", a: ["Mega Man", "Mega Man X", "Zero", "Proto Man"] },
  { c: 5, q: "Who created Tetris in 1984?", a: ["Alexey Pajitnov", "Vladimir Pokhilko", "Henk Rogers", "Nikolai Belikov"] },
  { c: 5, q: "In speedrunning, what does an \"any%\" run mean?", a: ["Reaching the end as fast as possible, ignoring completion", "Collecting every item in the game", "Playing without taking damage", "Running with no save files"] },
  { c: 5, q: "Which game series stars the physicist Gordon Freeman?", a: ["Half-Life", "Portal", "Doom", "Quake"] },
  { c: 5, q: "Which racing simulator series is Sony's flagship?", a: ["Gran Turismo", "Forza Motorsport", "Project CARS", "Assetto Corsa"] },
  { c: 5, q: "Which series stars the monster hunter Geralt of Rivia?", a: ["The Witcher", "Dragon Age", "Kingdom Come: Deliverance", "Elex"] },
  { c: 5, q: "Who created Undertale almost single-handedly?", a: ["Toby Fox", "Edmund McMillen", "Jonathan Blow", "Lucas Pope"] },
  { c: 5, q: "Which fictional company runs the test chambers in Portal?", a: ["Aperture Science", "Black Mesa", "Umbrella", "Abstergo"] },
  { c: 5, q: "What is the player character called in Skyrim?", a: ["The Dragonborn", "The Nerevarine", "The Champion of Cyrodiil", "The Vestige"] },
  { c: 5, q: "Which console was Bloodborne released for exclusively?", a: ["The PlayStation 4", "The Xbox One", "The PlayStation 3", "The PC"] },
  { c: 5, q: "Which 2018 Rockstar game stars Arthur Morgan?", a: ["Red Dead Redemption 2", "Red Dead Redemption", "Grand Theft Auto V", "Bully"] },
  { c: 5, q: "Which 1996 game pioneered analogue control in 3D platforming?", a: ["Super Mario 64", "Crash Bandicoot", "Tomb Raider", "Spyro the Dragon"] },
  { c: 5, q: "Which esports title holds the tournament called The International?", a: ["Dota 2", "League of Legends", "Counter-Strike", "StarCraft II"] },
  { c: 5, q: "In League of Legends, what structure must a team destroy to win?", a: ["The Nexus", "The Ancient", "The Throne", "The Core"] },
  { c: 5, q: "Which Nintendo series stars the bounty hunter Samus Aran?", a: ["Metroid", "F-Zero", "Star Fox", "Kid Icarus"] },
  { c: 5, q: "The roguelike genre is named after which 1980 game?", a: ["Rogue", "NetHack", "Angband", "Moria"] },
  { c: 5, q: "Which Swedish developer created Minecraft?", a: ["Markus \"Notch\" Persson", "Jens Bergensten", "Daniel Rosenfeld", "Carl Manneh"] },
  { c: 5, q: "Which company bought Mojang in 2014?", a: ["Microsoft", "Sony", "Tencent", "Valve"] },
  { c: 5, q: "Which is the best-selling handheld console of all time?", a: ["The Nintendo DS", "The Game Boy", "The PlayStation Portable", "The Game Boy Advance"] },
  { c: 5, q: "What is Ryu's signature projectile attack in Street Fighter called?", a: ["The Hadouken", "The Shoryuken", "The Tatsumaki", "The Sonic Boom"] },
  { c: 5, q: "Who is the antagonist of The Legend of Zelda: Breath of the Wild?", a: ["Calamity Ganon", "Ganondorf", "Vaati", "Zant"] },
  { c: 5, q: "What does MMORPG stand for?", a: ["Massively multiplayer online role-playing game", "Multi-mode online role-playing game", "Massive multiplayer offline RPG", "Multiplayer mission-oriented RPG"] },
  { c: 5, q: "The Sega Genesis was sold under which name outside North America?", a: ["The Mega Drive", "The Master System", "The Saturn", "The Mark III"] },
  { c: 5, q: "Which game won the first Game of the Year at The Game Awards in 2014?", a: ["Dragon Age: Inquisition", "Middle-earth: Shadow of Mordor", "Bayonetta 2", "Hearthstone"] },
  { c: 5, q: "Which studio developed Hollow Knight?", a: ["Team Cherry", "Motion Twin", "Supergiant Games", "Moon Studios"] },
  { c: 5, q: "Which company developed the original Sonic the Hedgehog?", a: ["Sonic Team", "Sega Technical Institute", "Yuji Naka Games", "Sega AM2"] },
  { c: 5, q: "Which 2016 game by id Software rebooted a classic shooter with a chainsaw and glory kills?", a: ["Doom", "Quake Champions", "Wolfenstein: The New Order", "Rage 2"] },
];

const ALL = build(EASY_NERD, HARD_NERD, 'questions-nerd.js');

module.exports = ALL;
module.exports.EASY = EASY_NERD;
module.exports.HARD = HARD_NERD;
