'use strict';

/**
 * Nerd edition question bank.
 *
 * Same format and same six board slots as questions.js - only four of the
 * categories are re-themed:
 *
 *   0 Religions of the World      (was Geography)
 *   1 Computer Science & Tech     (was Entertainment)
 *   2 History                     unchanged - carried over from questions.js
 *   3 Anime & Manga               (was Arts & Literature)
 *   4 Science & Nature            unchanged - carried over from questions.js
 *   5 Video Games                 (was Sports & Leisure)
 *
 * The two carried-over categories are pulled straight out of the classic bank
 * rather than copied, so a History question keeps the same wording, the same id
 * and therefore the same player ratings in both editions. Edit them there.
 */

const classic = require('./questions');

// Board slots the nerd edition leaves alone.
const CARRIED_OVER = new Set([2, 4]);

// --------------------------------------------------------------------------
// EASY - the stuff any regular of the internet has absorbed by osmosis.
// --------------------------------------------------------------------------
const EASY_NERD = [
  // ------------------------------------------------- Religions of the World
  { c: 0, q: "Which book is the holy scripture of Islam?", a: ["The Quran", "The Torah", "The Vedas", "The Tripitaka"] },
  { c: 0, q: "In which city is the Kaaba, the building Muslims face in prayer?", a: ["Mecca", "Medina", "Jerusalem", "Cairo"] },
  { c: 0, q: "Which festival of lights do Hindus celebrate in autumn?", a: ["Diwali", "Holi", "Pongal", "Onam"] },
  { c: 0, q: "Buddhism grew from the teachings of which figure?", a: ["Siddhartha Gautama", "Confucius", "Laozi", "Mahavira"] },
  { c: 0, q: "How many Pillars of Islam are there?", a: ["Five", "Three", "Six", "Seven"] },
  { c: 0, q: "Which is the holiest day of the Jewish year?", a: ["Yom Kippur", "Rosh Hashanah", "Purim", "Hanukkah"] },
  { c: 0, q: "Followers of which religion worship in a gurdwara?", a: ["Sikhism", "Jainism", "Hinduism", "Buddhism"] },
  { c: 0, q: "The Vatican is the headquarters of which church?", a: ["The Roman Catholic Church", "The Eastern Orthodox Church", "The Anglican Church", "The Lutheran Church"] },
  { c: 0, q: "During which month do Muslims fast from dawn to sunset?", a: ["Ramadan", "Muharram", "Shawwal", "Rajab"] },
  { c: 0, q: "Which Hindu festival is celebrated by throwing coloured powder?", a: ["Holi", "Diwali", "Navratri", "Raksha Bandhan"] },
  { c: 0, q: "Which river do Hindus regard as the most sacred?", a: ["The Ganges", "The Indus", "The Godavari", "The Brahmaputra"] },
  { c: 0, q: "In Buddhism, what is the release from the cycle of rebirth called?", a: ["Nirvana", "Samsara", "Karma", "Maya"] },
  { c: 0, q: "Sikhism was founded in which region of South Asia?", a: ["The Punjab", "Bengal", "Gujarat", "Kerala"] },
  { c: 0, q: "What is the annual Muslim pilgrimage to Mecca called?", a: ["The Hajj", "The Shahada", "The Zakat", "The Sawm"] },
  { c: 0, q: "On which day of the week does the Jewish Sabbath fall?", a: ["Saturday", "Sunday", "Friday", "Monday"] },
  { c: 0, q: "What title is held by the spiritual leader of Tibetan Buddhism?", a: ["The Dalai Lama", "The Patriarch", "The Mahant", "The Bhikkhu"] },
  { c: 0, q: "Which Christian festival celebrates the resurrection of Jesus?", a: ["Easter", "Christmas", "Advent", "Epiphany"] },
  { c: 0, q: "Which religion has the most followers worldwide?", a: ["Christianity", "Islam", "Hinduism", "Buddhism"] },
  { c: 0, q: "Shinto is the indigenous religion of which country?", a: ["Japan", "China", "Korea", "Vietnam"] },
  { c: 0, q: "What is a Jewish house of worship called?", a: ["A synagogue", "A basilica", "A gurdwara", "A vihara"] },
  { c: 0, q: "Which Hindu god is depicted with the head of an elephant?", a: ["Ganesha", "Hanuman", "Vishnu", "Indra"] },
  { c: 0, q: "Which religion teaches the Four Noble Truths?", a: ["Buddhism", "Hinduism", "Taoism", "Jainism"] },
  { c: 0, q: "Which Christian rite of initiation is performed with water?", a: ["Baptism", "Confirmation", "Ordination", "Anointing"] },
  { c: 0, q: "Which book is the holy scripture of Sikhism?", a: ["The Guru Granth Sahib", "The Vedas", "The Tripitaka", "The Avesta"] },
  { c: 0, q: "What is the skullcap worn by many Jewish men called?", a: ["A kippah", "A turban", "A keffiyeh", "A mitre"] },
  { c: 0, q: "Which prophet is said to have received the Quran?", a: ["Muhammad", "Moses", "Abraham", "Jesus"] },
  { c: 0, q: "On which mountain is Moses said to have received the Ten Commandments?", a: ["Mount Sinai", "Mount Zion", "Mount Ararat", "Mount Carmel"] },
  { c: 0, q: "What is an Islamic house of worship called?", a: ["A mosque", "A temple", "A chapel", "A shrine"] },
  { c: 0, q: "Which festival marks the end of Ramadan?", a: ["Eid al-Fitr", "Eid al-Adha", "Muharram", "Mawlid"] },
  { c: 0, q: "In the Hindu trimurti, which god is the Preserver?", a: ["Vishnu", "Shiva", "Brahma", "Agni"] },
  { c: 0, q: "Which Jewish festival is known as the Festival of Lights?", a: ["Hanukkah", "Purim", "Sukkot", "Shavuot"] },
  { c: 0, q: "The Star of David is a symbol of which religion?", a: ["Judaism", "Islam", "Christianity", "Hinduism"] },
  { c: 0, q: "Which country has the largest Muslim population?", a: ["Indonesia", "Pakistan", "Saudi Arabia", "Egypt"] },
  { c: 0, q: "What is the person who leads prayers in a mosque called?", a: ["An imam", "A rabbi", "A deacon", "A monk"] },
  { c: 0, q: "Which religion is famous for its strict practice of non-violence towards all living things?", a: ["Jainism", "Shinto", "Taoism", "Zoroastrianism"] },
  { c: 0, q: "The Western Wall in Jerusalem is a place of prayer for which religion?", a: ["Judaism", "Islam", "Hinduism", "Buddhism"] },
  { c: 0, q: "Which religion was founded by Guru Nanak?", a: ["Sikhism", "Jainism", "Buddhism", "Hinduism"] },
  { c: 0, q: "In Christianity, who are the three persons of the Trinity?", a: ["The Father, the Son and the Holy Spirit", "God, Mary and Jesus", "The Father, the Son and the Church", "Peter, Paul and John"] },
  { c: 0, q: "What is the Buddha's body of teaching called?", a: ["The Dharma", "The Sangha", "The Karma", "The Nirvana"] },
  { c: 0, q: "Which religion's followers celebrate Vesak, marking the Buddha's birth?", a: ["Buddhism", "Hinduism", "Shinto", "Sikhism"] },

  // -------------------------------------- Computer Science & Technology
  { c: 1, q: "What does CPU stand for?", a: ["Central Processing Unit", "Computer Power Unit", "Central Program Utility", "Core Processing Unit"] },
  { c: 1, q: "What does HTML stand for?", a: ["HyperText Markup Language", "High Transfer Machine Language", "Hyperlink Text Management Layer", "Home Tool Markup Language"] },
  { c: 1, q: "How many bits are in a byte?", a: ["8", "4", "16", "32"] },
  { c: 1, q: "Which company created the iPhone?", a: ["Apple", "Samsung", "Nokia", "Microsoft"] },
  { c: 1, q: "What does RAM stand for?", a: ["Random Access Memory", "Rapid Application Memory", "Read Access Module", "Runtime Allocation Map"] },
  { c: 1, q: "Which search engine was founded by Larry Page and Sergey Brin?", a: ["Google", "Yahoo", "Bing", "Ask Jeeves"] },
  { c: 1, q: "What is the binary number 1010 in decimal?", a: ["10", "8", "12", "20"] },
  { c: 1, q: "Which programming language was named after the comedy troupe Monty Python?", a: ["Python", "Ruby", "Perl", "Cobra"] },
  { c: 1, q: "What does URL stand for?", a: ["Uniform Resource Locator", "Universal Reference Link", "User Registry Location", "Unified Retrieval Language"] },
  { c: 1, q: "Which language is used to style web pages?", a: ["CSS", "HTML", "SQL", "XML"] },
  { c: 1, q: "Which operating system kernel did Linus Torvalds create?", a: ["Linux", "Unix", "BSD", "Minix"] },
  { c: 1, q: "Which company develops the Android operating system?", a: ["Google", "Apple", "Samsung", "Nokia"] },
  { c: 1, q: "What is malicious software that encrypts your files and demands payment called?", a: ["Ransomware", "Adware", "Spyware", "Firmware"] },
  { c: 1, q: "What does GPU stand for?", a: ["Graphics Processing Unit", "General Purpose Unit", "Graphical Peripheral Unit", "Grid Processing Unit"] },
  { c: 1, q: "Which version control system, created by Linus Torvalds, is the industry standard?", a: ["Git", "Subversion", "Mercurial", "CVS"] },
  { c: 1, q: "Which protocol shows a padlock in the browser because the traffic is encrypted?", a: ["HTTPS", "HTTP", "FTP", "SMTP"] },
  { c: 1, q: "Which language runs natively in a web browser to make pages interactive?", a: ["JavaScript", "Java", "Python", "C#"] },
  { c: 1, q: "Who founded Microsoft with Paul Allen?", a: ["Bill Gates", "Steve Ballmer", "Steve Jobs", "Gordon Moore"] },
  { c: 1, q: "What does PDF stand for?", a: ["Portable Document Format", "Printed Document File", "Public Data Format", "Page Description File"] },
  { c: 1, q: "Which type of drive stores data with no moving parts?", a: ["An SSD", "A hard disk drive", "A floppy drive", "An optical drive"] },
  { c: 1, q: "Which short-range wireless technology connects headphones to a phone?", a: ["Bluetooth", "Wi-Fi", "NFC", "Infrared"] },
  { c: 1, q: "What is Apple's desktop operating system called?", a: ["macOS", "iOS", "Ubuntu", "Solaris"] },
  { c: 1, q: "Which numbering system uses only the digits 0 and 1?", a: ["Binary", "Octal", "Decimal", "Hexadecimal"] },
  { c: 1, q: "What is unsolicited bulk email called?", a: ["Spam", "Phishing", "Ham", "Malware"] },
  { c: 1, q: "Which free online encyclopedia is written and edited by volunteers?", a: ["Wikipedia", "Britannica", "Quora", "WikiLeaks"] },
  { c: 1, q: "What is an error in a computer program commonly called?", a: ["A bug", "A glitchlet", "A fault line", "A crashlet"] },
  { c: 1, q: "What does VPN stand for?", a: ["Virtual Private Network", "Verified Public Node", "Variable Packet Network", "Virtual Proxy Name"] },
  { c: 1, q: "Which company created ChatGPT?", a: ["OpenAI", "Google", "Meta", "IBM"] },
  { c: 1, q: "What does the IP in \"IP address\" stand for?", a: ["Internet Protocol", "Internet Provider", "Internal Path", "Indexed Packet"] },
  { c: 1, q: "Which device forwards traffic between your home network and the internet?", a: ["A router", "A monitor", "A scanner", "A modem cable"] },
  { c: 1, q: "What does OS stand for in computing?", a: ["Operating System", "Open Source", "Output Stream", "Object Store"] },
  { c: 1, q: "Which key combination copies the selection on Windows?", a: ["Ctrl+C", "Ctrl+V", "Ctrl+X", "Ctrl+P"] },
  { c: 1, q: "Which company makes the Windows operating system?", a: ["Microsoft", "Apple", "IBM", "Oracle"] },
  { c: 1, q: "What does USB stand for?", a: ["Universal Serial Bus", "United System Bus", "Universal Storage Block", "Unified Signal Bridge"] },
  { c: 1, q: "Which social network was co-founded by Mark Zuckerberg?", a: ["Facebook", "Twitter", "MySpace", "LinkedIn"] },
  { c: 1, q: "Roughly how many megabytes are in a gigabyte?", a: ["1024", "100", "512", "2048"] },
  { c: 1, q: "What is the popular name for a program that automatically visits and indexes web pages?", a: ["A web crawler", "A daemon", "A cookie", "A macro"] },
  { c: 1, q: "Which component of a computer keeps data when the power is switched off?", a: ["The hard drive", "The RAM", "The CPU", "The cache"] },
  { c: 1, q: "What does AI stand for?", a: ["Artificial Intelligence", "Automated Inference", "Applied Informatics", "Algorithmic Iteration"] },
  { c: 1, q: "Which company designs the PlayStation and Xbox rival known as the Switch?", a: ["Nintendo", "Sony", "Microsoft", "Sega"] },

  // ------------------------------------------------------- Anime & Manga
  { c: 3, q: "Which anime follows a pirate crew captained by Monkey D. Luffy?", a: ["One Piece", "Fairy Tail", "Black Clover", "Bleach"] },
  { c: 3, q: "In Dragon Ball, what alien race does Goku belong to?", a: ["The Saiyans", "The Namekians", "The Frieza Force", "The Majin"] },
  { c: 3, q: "Which Studio Ghibli film follows a girl called Chihiro trapped in a bathhouse?", a: ["Spirited Away", "Princess Mononoke", "Ponyo", "Kiki's Delivery Service"] },
  { c: 3, q: "Which Pokémon is Ash Ketchum's constant partner in the anime?", a: ["Pikachu", "Charizard", "Bulbasaur", "Eevee"] },
  { c: 3, q: "In which series does humanity live behind enormous walls to hide from man-eating giants?", a: ["Attack on Titan", "Fire Force", "Claymore", "Gantz"] },
  { c: 3, q: "What is the name of the shinigami who drops the notebook in Death Note?", a: ["Ryuk", "Rem", "Sidoh", "Gelus"] },
  { c: 3, q: "Which hidden village is Naruto Uzumaki from?", a: ["The Hidden Leaf", "The Hidden Sand", "The Hidden Mist", "The Hidden Cloud"] },
  { c: 3, q: "Which anime follows the brothers Edward and Alphonse Elric?", a: ["Fullmetal Alchemist", "Soul Eater", "D.Gray-man", "Blue Exorcist"] },
  { c: 3, q: "Which mangaka created Dragon Ball?", a: ["Akira Toriyama", "Eiichiro Oda", "Masashi Kishimoto", "Tite Kubo"] },
  { c: 3, q: "In My Hero Academia, what are superpowers called?", a: ["Quirks", "Stands", "Nen", "Semblances"] },
  { c: 3, q: "Who is the notebook-wielding protagonist of Death Note?", a: ["Light Yagami", "Lelouch Lamperouge", "Shinji Ikari", "Kaneki Ken"] },
  { c: 3, q: "What is Luffy's stated dream in One Piece?", a: ["To become King of the Pirates", "To find his father", "To become the world's strongest swordsman", "To map the whole ocean"] },
  { c: 3, q: "Who is the demon-slaying protagonist of Demon Slayer?", a: ["Tanjiro Kamado", "Zenitsu Agatsuma", "Giyu Tomioka", "Inosuke Hashibira"] },
  { c: 3, q: "Which Ghibli film features a wandering castle on mechanical legs?", a: ["Howl's Moving Castle", "Castle in the Sky", "The Wind Rises", "Arrietty"] },
  { c: 3, q: "Which clan does Sasuke belong to in Naruto?", a: ["The Uchiha", "The Hyuga", "The Senju", "The Nara"] },
  { c: 3, q: "In which series do Gon Freecss and Killua take the licensing exam to become Hunters?", a: ["Hunter x Hunter", "Yu Yu Hakusho", "Toriko", "Magi"] },
  { c: 3, q: "In Demon Slayer, what has happened to Tanjiro's sister Nezuko?", a: ["She has been turned into a demon", "She has lost her memory", "She has been kidnapped by the Corps", "She has become a Hashira"] },
  { c: 3, q: "Which mecha series has Shinji Ikari as its reluctant pilot?", a: ["Neon Genesis Evangelion", "Gurren Lagann", "Code Geass", "Darling in the Franxx"] },
  { c: 3, q: "Which criminal team pursues Pikachu in the Pokémon anime?", a: ["Team Rocket", "Team Magma", "Team Galactic", "Team Plasma"] },
  { c: 3, q: "Which magazine serialises One Piece?", a: ["Weekly Shonen Jump", "Weekly Shonen Magazine", "Young Animal", "Afternoon"] },
  { c: 3, q: "What is the golden-haired transformation in Dragon Ball Z called?", a: ["Super Saiyan", "Ultra Instinct", "Kaio-ken", "Fusion"] },
  { c: 3, q: "What is Ichigo's surname in Bleach?", a: ["Kurosaki", "Kuchiki", "Ishida", "Kurusu"] },
  { c: 3, q: "Which Ghibli film features a giant forest spirit and a bus shaped like a cat?", a: ["My Neighbour Totoro", "Pom Poko", "The Cat Returns", "Whisper of the Heart"] },
  { c: 3, q: "In Jujutsu Kaisen, whose finger does Yuji Itadori swallow?", a: ["Sukuna's", "Mahito's", "Gojo's", "Kenjaku's"] },
  { c: 3, q: "Which anime centres on a card game and a boy called Yugi Muto?", a: ["Yu-Gi-Oh!", "Cardfight!! Vanguard", "Duel Masters", "Beyblade"] },
  { c: 3, q: "Which sports anime follows the volleyball player Shoyo Hinata?", a: ["Haikyu!!", "Kuroko's Basketball", "Slam Dunk", "Blue Lock"] },
  { c: 3, q: "Who is the bald, bored hero of One Punch Man?", a: ["Saitama", "Genos", "Mumen Rider", "King"] },
  { c: 3, q: "Which bounty hunter leads the crew of the Bebop?", a: ["Spike Spiegel", "Jet Black", "Vicious", "Faye Valentine"] },
  { c: 3, q: "What is the Japanese word for comics?", a: ["Manga", "Anime", "Manhwa", "Doujin"] },
  { c: 3, q: "Which long-running anime stars a shrunken detective called Conan Edogawa?", a: ["Detective Conan", "Death Parade", "Erased", "Monster"] },
  { c: 3, q: "Which jutsu lets Naruto create solid copies of himself?", a: ["The Shadow Clone Jutsu", "The Transformation Jutsu", "The Substitution Jutsu", "The Rasengan"] },
  { c: 3, q: "What is Anya's secret ability in Spy x Family?", a: ["Reading minds", "Seeing the future", "Turning invisible", "Talking to animals"] },
  { c: 3, q: "Which 1988 anime film is set in the sprawling Neo-Tokyo?", a: ["Akira", "Metropolis", "Paprika", "Perfect Blue"] },
  { c: 3, q: "How many Pokémon were there in the original generation?", a: ["151", "150", "251", "100"] },
  { c: 3, q: "Which Straw Hat swordsman fights with three swords?", a: ["Zoro", "Sanji", "Usopp", "Brook"] },
  { c: 3, q: "Who mentors Izuku Midoriya in My Hero Academia?", a: ["All Might", "Endeavor", "Aizawa", "Nighteye"] },
  { c: 3, q: "In Attack on Titan, what is the name of the protagonist?", a: ["Eren Yeager", "Armin Arlert", "Jean Kirstein", "Reiner Braun"] },
  { c: 3, q: "What is the fundamental law of alchemy in Fullmetal Alchemist?", a: ["Equivalent exchange", "Conservation of souls", "The law of transmutation", "The rule of three"] },
  { c: 3, q: "Which anime follows Asta, a boy born without magic in a magical kingdom?", a: ["Black Clover", "Fairy Tail", "The Seven Deadly Sins", "Radiant"] },
  { c: 3, q: "What is the nine-tailed fox sealed inside Naruto called?", a: ["Kurama", "Shukaku", "Gyuki", "Matatabi"] },

  // --------------------------------------------------------- Video Games
  { c: 5, q: "Which moustachioed plumber is Nintendo's mascot?", a: ["Mario", "Luigi", "Wario", "Toad"] },
  { c: 5, q: "What is the name of the green-clad hero of The Legend of Zelda?", a: ["Link", "Zelda", "Ganon", "Navi"] },
  { c: 5, q: "Which company makes the Xbox?", a: ["Microsoft", "Sony", "Nintendo", "Sega"] },
  { c: 5, q: "Which Minecraft mob hisses and then explodes?", a: ["The creeper", "The enderman", "The zombie", "The blaze"] },
  { c: 5, q: "Which is the best-selling video game of all time?", a: ["Minecraft", "Tetris", "Grand Theft Auto V", "Wii Sports"] },
  { c: 5, q: "Which blue hedgehog is Sega's mascot?", a: ["Sonic", "Knuckles", "Tails", "Shadow"] },
  { c: 5, q: "Which battle royale game is known for letting players build structures?", a: ["Fortnite", "PUBG", "Apex Legends", "Warzone"] },
  { c: 5, q: "What does FPS stand for as a game genre?", a: ["First-person shooter", "Frames per second", "Free-play strategy", "Fantasy party sim"] },
  { c: 5, q: "Which company created the PlayStation?", a: ["Sony", "Microsoft", "Nintendo", "Atari"] },
  { c: 5, q: "Which series stars the armoured soldier Master Chief?", a: ["Halo", "Doom", "Gears of War", "Destiny"] },
  { c: 5, q: "Which series stars the archaeologist Lara Croft?", a: ["Tomb Raider", "Uncharted", "Indiana Jones", "Far Cry"] },
  { c: 5, q: "What does Sonic collect as he runs?", a: ["Rings", "Coins", "Stars", "Gems"] },
  { c: 5, q: "In which kingdom is The Legend of Zelda set?", a: ["Hyrule", "Termina", "Gerudo", "Eldia"] },
  { c: 5, q: "In Among Us, what is the traitor called?", a: ["The impostor", "The saboteur", "The mole", "The infected"] },
  { c: 5, q: "Which farming game was made almost single-handedly by Eric Barone?", a: ["Stardew Valley", "Harvest Moon", "Farming Simulator", "My Time at Portia"] },
  { c: 5, q: "Which 1972 arcade game was a simple table-tennis simulation?", a: ["Pong", "Breakout", "Space Invaders", "Asteroids"] },
  { c: 5, q: "Which city is the setting of Grand Theft Auto V?", a: ["Los Santos", "Liberty City", "Vice City", "San Fierro"] },
  { c: 5, q: "Which handheld console did Nintendo launch in 1989?", a: ["The Game Boy", "The Game Gear", "The Lynx", "The Nintendo DS"] },
  { c: 5, q: "Which life-simulation series lets you build homes and run families' lives?", a: ["The Sims", "SimCity", "Animal Crossing", "Second Life"] },
  { c: 5, q: "Which series stars the Spartan-turned-god-killer Kratos?", a: ["God of War", "Devil May Cry", "Bayonetta", "Darksiders"] },
  { c: 5, q: "Which Valve shooter is commonly abbreviated to CS?", a: ["Counter-Strike", "Call of Duty", "Crysis", "Combat Storm"] },
  { c: 5, q: "What is the name of Mario's taller brother?", a: ["Luigi", "Wario", "Waluigi", "Yoshi"] },
  { c: 5, q: "Which 2006 Nintendo console was built around motion controls?", a: ["The Wii", "The GameCube", "The Wii U", "The Switch"] },
  { c: 5, q: "Which raccoon-like character lends you money in Animal Crossing?", a: ["Tom Nook", "Isabelle", "K.K. Slider", "Blathers"] },
  { c: 5, q: "Which stealth series stars Solid Snake?", a: ["Metal Gear", "Splinter Cell", "Hitman", "Thief"] },
  { c: 5, q: "Which puzzle game arms you with a gun that shoots portals?", a: ["Portal", "Antichamber", "The Witness", "Quantum Conundrum"] },
  { c: 5, q: "Which fighting game series features Ryu and Chun-Li?", a: ["Street Fighter", "Tekken", "Mortal Kombat", "Guilty Gear"] },
  { c: 5, q: "What are Pac-Man's four pursuers?", a: ["Ghosts", "Robots", "Blobs", "Aliens"] },
  { c: 5, q: "Which company created Half-Life and the Steam store?", a: ["Valve", "id Software", "Epic Games", "Bungie"] },
  { c: 5, q: "Which is the best-selling home console of all time?", a: ["The PlayStation 2", "The Nintendo Wii", "The Xbox 360", "The PlayStation 4"] },
  { c: 5, q: "Which pink puffball can copy his enemies' abilities?", a: ["Kirby", "Jigglypuff", "Yoshi", "Ness"] },
  { c: 5, q: "Which Minecraft material makes the most durable tools?", a: ["Netherite", "Diamond", "Obsidian", "Iron"] },
  { c: 5, q: "Which open-world series pits Assassins against Templars?", a: ["Assassin's Creed", "Dishonored", "Watch Dogs", "Hitman"] },
  { c: 5, q: "Which mobile game launched birds at pigs with a slingshot?", a: ["Angry Birds", "Cut the Rope", "Fruit Ninja", "Doodle Jump"] },
  { c: 5, q: "Which Blizzard game is a team-based hero shooter?", a: ["Overwatch", "Valorant", "Team Fortress 2", "Paladins"] },
  { c: 5, q: "Which Nintendo series pits characters from many franchises against each other?", a: ["Super Smash Bros.", "Mario Party", "Nintendo Land", "Mario Kart"] },
  { c: 5, q: "Which company developed Fortnite?", a: ["Epic Games", "Riot Games", "Ubisoft", "Activision"] },
  { c: 5, q: "In Tetris, what is the long straight piece nicknamed?", a: ["The I-piece", "The L-piece", "The S-piece", "The T-piece"] },
  { c: 5, q: "Which of these is a starter Pokémon in Red and Blue?", a: ["Charmander", "Zubat", "Snorlax", "Gengar"] },
  { c: 5, q: "Which item in Mario Kart makes you briefly invincible?", a: ["The star", "The green shell", "The banana", "The mushroom"] },
];

// --------------------------------------------------------------------------
// HARD - the stuff you only know if this is genuinely your thing.
// --------------------------------------------------------------------------
const HARD_NERD = [
  // ------------------------------------------------- Religions of the World
  { c: 0, q: "What is the holy book of Zoroastrianism?", a: ["The Avesta", "The Kojiki", "The Tripitaka", "The Zohar"] },
  { c: 0, q: "Which branch of Islam is the majority in Iran?", a: ["Shia", "Sunni", "Ibadi", "Ahmadi"] },
  { c: 0, q: "In an Orthodox church, what is the screen of icons before the sanctuary called?", a: ["The iconostasis", "The narthex", "The reredos", "The apse"] },
  { c: 0, q: "Which council of 325 AD produced the first version of the Nicene Creed?", a: ["The First Council of Nicaea", "The Council of Trent", "The Council of Ephesus", "The Synod of Whitby"] },
  { c: 0, q: "Which of the Sikh five Ks is a ceremonial dagger?", a: ["The kirpan", "The kara", "The kanga", "The kachera"] },
  { c: 0, q: "Which Shinto shrine is ritually rebuilt every twenty years?", a: ["The Ise Grand Shrine", "The Meiji Shrine", "Fushimi Inari", "Itsukushima"] },
  { c: 0, q: "In which language is the Theravada Buddhist canon written?", a: ["Pali", "Sanskrit", "Tibetan", "Classical Chinese"] },
  { c: 0, q: "Who founded the Baháʼí Faith?", a: ["Baháʼu'lláh", "The Báb", "Shoghi Effendi", "Abdu'l-Bahá"] },
  { c: 0, q: "What is the compilation of Jewish oral law, redacted around 200 CE, called?", a: ["The Mishnah", "The Midrash", "The Tosefta", "The Zohar"] },
  { c: 0, q: "Which Christian denomination grew out of the preaching of John Wesley?", a: ["Methodism", "Presbyterianism", "Congregationalism", "The Baptists"] },
  { c: 0, q: "Which mystical tradition within Islam produced the whirling dervishes?", a: ["Sufism", "Salafism", "Ibadism", "Zaydism"] },
  { c: 0, q: "The Lotus Sutra is the central text of which Japanese Buddhist school?", a: ["Nichiren", "Shingon", "Zen", "Jodo Shinshu"] },
  { c: 0, q: "What is the Muslim declaration of faith called?", a: ["The Shahada", "The Takbir", "The Basmala", "The Adhan"] },
  { c: 0, q: "The Kitáb-i-Aqdas is the central book of which faith?", a: ["The Baháʼí Faith", "Zoroastrianism", "Jainism", "Sikhism"] },
  { c: 0, q: "Which Ethiopian emperor is revered as a messianic figure by Rastafari?", a: ["Haile Selassie I", "Menelik II", "Tewodros II", "Yohannes IV"] },
  { c: 0, q: "What is the Catholic doctrine that the bread and wine become the body and blood of Christ?", a: ["Transubstantiation", "Consubstantiation", "Predestination", "Sanctification"] },
  { c: 0, q: "Which is the oldest of the four Vedas?", a: ["The Rigveda", "The Samaveda", "The Yajurveda", "The Atharvaveda"] },
  { c: 0, q: "Which text is popularly known in English as the Tibetan Book of the Dead?", a: ["The Bardo Thodol", "The Lotus Sutra", "The Kangyur", "The Diamond Sutra"] },
  { c: 0, q: "Which prophet founded Zoroastrianism?", a: ["Zarathustra", "Mani", "Mazdak", "Cyrus"] },
  { c: 0, q: "Which Christian group is formally called the Religious Society of Friends?", a: ["The Quakers", "The Shakers", "The Amish", "The Mennonites"] },
  { c: 0, q: "What is the Jewish ritual bath called?", a: ["A mikveh", "A bimah", "A mezuzah", "A shofar"] },
  { c: 0, q: "What is a formal legal opinion issued by an Islamic scholar called?", a: ["A fatwa", "A hadith", "A madhhab", "A sunnah"] },
  { c: 0, q: "Which of these is one of the four schools of Sunni jurisprudence?", a: ["Hanafi", "Twelver", "Zaydi", "Ismaili"] },
  { c: 0, q: "Who was the twenty-fourth and last Tirthankara of Jainism?", a: ["Mahavira", "Parshvanatha", "Rishabhanatha", "Neminatha"] },
  { c: 0, q: "Who founded the Church of Jesus Christ of Latter-day Saints?", a: ["Joseph Smith", "Brigham Young", "Ellen White", "Charles Taze Russell"] },
  { c: 0, q: "Which split in 1054 divided the Catholic and Orthodox churches?", a: ["The Great Schism", "The Western Schism", "The Iconoclast Controversy", "The Investiture Contest"] },
  { c: 0, q: "What is the gateway marking the entrance to a Shinto shrine called?", a: ["A torii", "A stupa", "A pagoda", "A dolmen"] },
  { c: 0, q: "How many human Gurus did Sikhism have?", a: ["Ten", "Five", "Seven", "Twelve"] },
  { c: 0, q: "Which Jewish festival commemorates the Exodus from Egypt?", a: ["Passover", "Purim", "Sukkot", "Shavuot"] },
  { c: 0, q: "Which Hindu scripture is a battlefield dialogue between Arjuna and Krishna?", a: ["The Bhagavad Gita", "The Ramayana", "The Rigveda", "The Manusmriti"] },
  { c: 0, q: "Which Chinese tradition is founded on the Tao Te Ching?", a: ["Taoism", "Confucianism", "Legalism", "Mohism"] },
  { c: 0, q: "Which pope convened the Second Vatican Council?", a: ["John XXIII", "Paul VI", "Pius XII", "John Paul II"] },
  { c: 0, q: "The Druze faith is found mainly in which region?", a: ["The Levant", "North Africa", "Central Asia", "The Caucasus"] },
  { c: 0, q: "Which Indian emperor spread Buddhism across his empire in the third century BCE?", a: ["Ashoka", "Chandragupta Maurya", "Kanishka", "Harsha"] },
  { c: 0, q: "What is the body of Jewish dietary law called?", a: ["Kashrut", "Kabbalah", "Kaddish", "Kiddush"] },
  { c: 0, q: "Followers of which religion are known as Parsis in India?", a: ["Zoroastrianism", "Jainism", "Baháʼí", "Judaism"] },
  { c: 0, q: "What is the ritual prayer Muslims perform five times a day called?", a: ["Salat", "Zakat", "Sawm", "Dua"] },
  { c: 0, q: "What are the recorded sayings and deeds of the Prophet Muhammad called?", a: ["Hadith", "Surah", "Tafsir", "Ijma"] },
  { c: 0, q: "Which archbishopric is the senior see of the Church of England?", a: ["Canterbury", "York", "London", "Durham"] },
  { c: 0, q: "What is the Hindu term for the cycle of death and rebirth?", a: ["Samsara", "Moksha", "Ahimsa", "Dharma"] },
  { c: 0, q: "Which Christian season of forty days precedes Easter?", a: ["Lent", "Advent", "Pentecost", "Epiphany"] },
  { c: 0, q: "What is seated meditation called in Zen Buddhism?", a: ["Zazen", "Koan", "Kinhin", "Satori"] },
  { c: 0, q: "The Ethiopian Orthodox Church claims to keep which relic at Axum?", a: ["The Ark of the Covenant", "The True Cross", "The Holy Grail", "The Shroud of Turin"] },
  { c: 0, q: "Which thirteenth-century Persian mystic wrote the Masnavi?", a: ["Rumi", "Hafez", "Saadi", "Omar Khayyam"] },
  { c: 0, q: "Which council of 451 defined Christ as having two natures?", a: ["Chalcedon", "Nicaea", "Constantinople", "Trent"] },
  { c: 0, q: "Which Hindu goddess of learning is honoured at Vasant Panchami?", a: ["Saraswati", "Lakshmi", "Parvati", "Kali"] },
  { c: 0, q: "What is the worldwide community of Muslims called?", a: ["The ummah", "The caliphate", "The jamaat", "The madhhab"] },
  { c: 0, q: "What is the free communal kitchen at a Sikh temple called?", a: ["The langar", "The kirtan", "The seva", "The nishan"] },
  { c: 0, q: "In Mahayana Buddhism, what is a being who delays nirvana to help others called?", a: ["A bodhisattva", "An arhat", "A bhikkhu", "A lama"] },
  { c: 0, q: "The Coptic Orthodox Church originated in which country?", a: ["Egypt", "Ethiopia", "Syria", "Armenia"] },
  { c: 0, q: "Santería blends Yoruba belief with which other religion?", a: ["Catholicism", "Islam", "Protestantism", "Buddhism"] },
  { c: 0, q: "What are the Hebrew scriptures collectively known as in Judaism?", a: ["The Tanakh", "The Talmud", "The Septuagint", "The Haggadah"] },
  { c: 0, q: "Which Japanese Buddhist school was founded by Kukai?", a: ["Shingon", "Nichiren", "Soto Zen", "Tendai"] },
  { c: 0, q: "Which Hindu philosophical school is associated with Adi Shankara?", a: ["Advaita Vedanta", "Samkhya", "Nyaya", "Vaisheshika"] },
  { c: 0, q: "What is the Islamic term for the interpretation and commentary of the Quran?", a: ["Tafsir", "Fiqh", "Sira", "Isnad"] },

  // -------------------------------------- Computer Science & Technology
  { c: 1, q: "What is the time complexity of binary search on a sorted array?", a: ["O(log n)", "O(n)", "O(n log n)", "O(1)"] },
  { c: 1, q: "Who is regarded as the first computer programmer for her notes on the Analytical Engine?", a: ["Ada Lovelace", "Grace Hopper", "Hedy Lamarr", "Joan Clarke"] },
  { c: 1, q: "In databases, what does the A in ACID stand for?", a: ["Atomicity", "Availability", "Access", "Alignment"] },
  { c: 1, q: "Which data structure works last-in, first-out?", a: ["A stack", "A queue", "A heap", "A trie"] },
  { c: 1, q: "Who proposed the 1950 test for whether a machine can think?", a: ["Alan Turing", "John von Neumann", "Claude Shannon", "Marvin Minsky"] },
  { c: 1, q: "What is the default port for HTTPS?", a: ["443", "80", "8080", "22"] },
  { c: 1, q: "Which transport protocol is connectionless and does not guarantee delivery?", a: ["UDP", "TCP", "ICMP", "FTP"] },
  { c: 1, q: "Who created the C programming language?", a: ["Dennis Ritchie", "Ken Thompson", "Brian Kernighan", "Bjarne Stroustrup"] },
  { c: 1, q: "Who created C++?", a: ["Bjarne Stroustrup", "James Gosling", "Guido van Rossum", "Anders Hejlsberg"] },
  { c: 1, q: "What does REST stand for in web APIs?", a: ["Representational State Transfer", "Remote Execution Service Transport", "Resource State Table", "Reliable Stateless Transfer"] },
  { c: 1, q: "At which company was Unix originally developed in 1969?", a: ["Bell Labs", "IBM", "Xerox PARC", "DEC"] },
  { c: 1, q: "Roughly how many addresses does IPv4 provide?", a: ["4.3 billion", "65 thousand", "18 quintillion", "340 undecillion"] },
  { c: 1, q: "Which hash function did Google demonstrate a practical collision for in 2017?", a: ["SHA-1", "SHA-256", "bcrypt", "AES"] },
  { c: 1, q: "Who invented the World Wide Web?", a: ["Tim Berners-Lee", "Vint Cerf", "Marc Andreessen", "Robert Kahn"] },
  { c: 1, q: "Which sorting algorithm does Python's built-in sort use?", a: ["Timsort", "Quicksort", "Heapsort", "Introsort"] },
  { c: 1, q: "What is a function that calls itself called?", a: ["Recursive", "Reentrant", "Idempotent", "Polymorphic"] },
  { c: 1, q: "At which layer of the OSI model does TCP operate?", a: ["The transport layer", "The network layer", "The session layer", "The data link layer"] },
  { c: 1, q: "What does RAID stand for?", a: ["Redundant Array of Independent Disks", "Rapid Access Indexed Drive", "Replicated Array of Internal Devices", "Random Allocation of Indexed Data"] },
  { c: 1, q: "Who wrote The Art of Computer Programming?", a: ["Donald Knuth", "Edsger Dijkstra", "Niklaus Wirth", "Alan Kay"] },
  { c: 1, q: "Which algorithm finds shortest paths from one source when all edge weights are non-negative?", a: ["Dijkstra's algorithm", "Kruskal's algorithm", "Bellman-Ford", "Prim's algorithm"] },
  { c: 1, q: "What is 0xFF in decimal?", a: ["255", "16", "160", "512"] },
  { c: 1, q: "Which company originally developed Java?", a: ["Sun Microsystems", "Oracle", "IBM", "Netscape"] },
  { c: 1, q: "Which data structure usually backs a priority queue?", a: ["A heap", "A linked list", "A hash table", "A stack"] },
  { c: 1, q: "Which public-key cryptosystem rests on the difficulty of factoring large numbers?", a: ["RSA", "AES", "Diffie-Hellman", "SHA-2"] },
  { c: 1, q: "Which observation predicted that transistor counts would roughly double every two years?", a: ["Moore's Law", "Amdahl's Law", "Metcalfe's Law", "Wirth's Law"] },
  { c: 1, q: "Which program turns source code into machine code before the program is run?", a: ["A compiler", "An interpreter", "A linker", "A debugger"] },
  { c: 1, q: "Which document database takes its name from the word \"humongous\"?", a: ["MongoDB", "CouchDB", "Cassandra", "Redis"] },
  { c: 1, q: "What does the GIL in CPython stand for?", a: ["Global Interpreter Lock", "General Instruction Layer", "Garbage Isolation List", "Generic Import Loader"] },
  { c: 1, q: "Which two engineers designed the TCP/IP protocol suite?", a: ["Vint Cerf and Robert Kahn", "Tim Berners-Lee and Robert Cailliau", "Ken Thompson and Dennis Ritchie", "Paul Baran and Leonard Kleinrock"] },
  { c: 1, q: "What did Alan Turing prove about the halting problem?", a: ["It is undecidable", "It is NP-complete", "It is solvable in linear time", "It only applies to finite machines"] },
  { c: 1, q: "The Turing Award is the highest honour in which field?", a: ["Computing", "Mathematics", "Physics", "Cryptography"] },
  { c: 1, q: "What is the term for a bug whose outcome depends on the timing of concurrent operations?", a: ["A race condition", "A deadlock", "A memory leak", "An off-by-one error"] },
  { c: 1, q: "Which standard assigns a code point to characters in nearly every writing system?", a: ["Unicode", "ASCII", "ISO-8859-1", "EBCDIC"] },
  { c: 1, q: "Which British company designs the ARM instruction set?", a: ["Arm Holdings", "Imagination Technologies", "Broadcom", "Raspberry Pi Ltd"] },
  { c: 1, q: "What does Amdahl's Law describe?", a: ["The limit of speedup from parallelising a program", "The growth of network value with users", "The doubling of transistor density", "The cost of context switching"] },
  { c: 1, q: "Writing past the end of an allocated array causes which classic vulnerability?", a: ["A buffer overflow", "A SQL injection", "A cross-site script", "A privilege escalation"] },
  { c: 1, q: "What does MVC stand for in software architecture?", a: ["Model-View-Controller", "Multi-Version Concurrency", "Managed Virtual Container", "Modular View Compiler"] },
  { c: 1, q: "Which language released by Google in 2009 has a gopher as its mascot?", a: ["Go", "Rust", "Dart", "Kotlin"] },
  { c: 1, q: "Who co-founded Apple with Steve Jobs and designed the Apple I?", a: ["Steve Wozniak", "Ronald Wayne", "John Sculley", "Jef Raskin"] },
  { c: 1, q: "Which self-balancing binary search tree was published in 1962 by two Soviet mathematicians?", a: ["The AVL tree", "The red-black tree", "The B-tree", "The splay tree"] },
  { c: 1, q: "Which complexity class contains problems whose solutions can be verified in polynomial time?", a: ["NP", "P", "PSPACE", "EXPTIME"] },
  { c: 1, q: "Which 1993 browser popularised the web with an inline-image graphical interface?", a: ["Mosaic", "Netscape Navigator", "Lynx", "Internet Explorer"] },
  { c: 1, q: "Which protocol carries email between mail servers?", a: ["SMTP", "IMAP", "POP3", "HTTP"] },
  { c: 1, q: "Which hash function does Bitcoin's proof of work rely on?", a: ["SHA-256", "MD5", "Scrypt", "Keccak"] },
  { c: 1, q: "Which company acquired GitHub in 2018?", a: ["Microsoft", "Google", "Atlassian", "IBM"] },
  { c: 1, q: "Which sorting algorithm is stable and guarantees O(n log n) in the worst case?", a: ["Merge sort", "Quicksort", "Heapsort", "Shell sort"] },
  { c: 1, q: "Which computer, unveiled in 1946, is often called the first general-purpose electronic computer?", a: ["ENIAC", "Colossus", "UNIVAC", "EDSAC"] },
  { c: 1, q: "In Big-O notation, what is the average time complexity of a hash table lookup?", a: ["O(1)", "O(log n)", "O(n)", "O(n log n)"] },
  { c: 1, q: "Which company is the world's largest contract manufacturer of semiconductors?", a: ["TSMC", "Intel", "Samsung", "GlobalFoundries"] },
  { c: 1, q: "What does DNS do?", a: ["Translates domain names into IP addresses", "Encrypts web traffic", "Routes packets between networks", "Assigns local IP addresses"] },
  { c: 1, q: "Which paper introduced the transformer architecture behind modern language models?", a: ["Attention Is All You Need", "ImageNet Classification with Deep CNNs", "Playing Atari with Deep Reinforcement Learning", "Generative Adversarial Networks"] },
  { c: 1, q: "Which Dutch computer scientist wrote \"Go To Statement Considered Harmful\"?", a: ["Edsger Dijkstra", "Niklaus Wirth", "Guido van Rossum", "Andrew Tanenbaum"] },
  { c: 1, q: "Which language, first released in 2015, uses ownership and borrowing for memory safety?", a: ["Rust", "Go", "Swift", "Zig"] },
  { c: 1, q: "What is the term for an algorithm's guaranteed behaviour on its most unfavourable input?", a: ["Worst-case complexity", "Amortised complexity", "Average-case complexity", "Asymptotic bound"] },
  { c: 1, q: "Which architecture stores program instructions and data in the same memory?", a: ["The von Neumann architecture", "The Harvard architecture", "The dataflow architecture", "The RISC architecture"] },

  // ------------------------------------------------------- Anime & Manga
  { c: 3, q: "Which studio animated the first three seasons of Attack on Titan?", a: ["Wit Studio", "MAPPA", "Ufotable", "Bones"] },
  { c: 3, q: "Who directed Cowboy Bebop?", a: ["Shinichiro Watanabe", "Hideaki Anno", "Mamoru Oshii", "Satoshi Kon"] },
  { c: 3, q: "What is the name of Guts's enormous sword in Berserk?", a: ["The Dragonslayer", "The Godhand", "Zangetsu", "The Behelit"] },
  { c: 3, q: "Which mangaka created Berserk?", a: ["Kentaro Miura", "Naoki Urasawa", "Takehiko Inoue", "Yukito Kishiro"] },
  { c: 3, q: "In Neon Genesis Evangelion, what are the monstrous enemies called?", a: ["Angels", "Titans", "Espers", "Demons"] },
  { c: 3, q: "Which Makoto Shinkai film features two teenagers swapping bodies?", a: ["Your Name", "Weathering with You", "5 Centimetres per Second", "Suzume"] },
  { c: 3, q: "Who created the manga Ghost in the Shell?", a: ["Masamune Shirow", "Katsuhiro Otomo", "Yoshiyuki Sadamoto", "Tsutomu Nihei"] },
  { c: 3, q: "Which studio produced the Demon Slayer anime?", a: ["Ufotable", "MAPPA", "Bones", "A-1 Pictures"] },
  { c: 3, q: "What is Luffy's Devil Fruit called?", a: ["The Gum-Gum Fruit", "The Flame-Flame Fruit", "The Chop-Chop Fruit", "The Op-Op Fruit"] },
  { c: 3, q: "Which is the best-selling manga series of all time?", a: ["One Piece", "Dragon Ball", "Naruto", "Golgo 13"] },
  { c: 3, q: "Which co-founder of Studio Ghibli directed Grave of the Fireflies?", a: ["Isao Takahata", "Hayao Miyazaki", "Toshio Suzuki", "Goro Miyazaki"] },
  { c: 3, q: "What is the name of Shinji's mecha in Neon Genesis Evangelion?", a: ["Unit-01", "Unit-00", "Unit-02", "Unit-03"] },
  { c: 3, q: "Who is the Fourth Hokage in Naruto?", a: ["Minato Namikaze", "Hiruzen Sarutobi", "Tobirama Senju", "Tsunade"] },
  { c: 3, q: "Which anime follows Kirito trapped in a virtual reality MMO?", a: ["Sword Art Online", "Log Horizon", "Overlord", "No Game No Life"] },
  { c: 3, q: "Which Naoki Urasawa manga follows a surgeon hunting a killer he once saved?", a: ["Monster", "20th Century Boys", "Pluto", "Billy Bat"] },
  { c: 3, q: "In JoJo's Bizarre Adventure, what are the manifested powers called?", a: ["Stands", "Ripples", "Quirks", "Personas"] },
  { c: 3, q: "What is the name of Jotaro Kujo's Stand?", a: ["Star Platinum", "The World", "Crazy Diamond", "Gold Experience"] },
  { c: 3, q: "Who directed the 1995 film Ghost in the Shell?", a: ["Mamoru Oshii", "Satoshi Kon", "Katsuhiro Otomo", "Rintaro"] },
  { c: 3, q: "Which studio produced K-On! and Violet Evergarden?", a: ["Kyoto Animation", "P.A. Works", "Shaft", "J.C. Staff"] },
  { c: 3, q: "In Code Geass, what is Lelouch's power called?", a: ["Geass", "Nen", "Sharingan", "Cursed Energy"] },
  { c: 3, q: "Who created the manga Sailor Moon?", a: ["Naoko Takeuchi", "Rumiko Takahashi", "CLAMP", "Ai Yazawa"] },
  { c: 3, q: "Who wrote and illustrated Chainsaw Man?", a: ["Tatsuki Fujimoto", "Gege Akutami", "Koyoharu Gotouge", "Yuji Kaku"] },
  { c: 3, q: "What is the name of Denji's devil-dog companion in Chainsaw Man?", a: ["Pochita", "Power", "Beam", "Meowy"] },
  { c: 3, q: "Who is the protagonist of Vinland Saga?", a: ["Thorfinn", "Askeladd", "Canute", "Thors"] },
  { c: 3, q: "Which anime film won the Academy Award for Best Animated Feature in 2003?", a: ["Spirited Away", "Princess Mononoke", "Howl's Moving Castle", "The Cat Returns"] },
  { c: 3, q: "What is the organisation Shinji's father commands in Evangelion?", a: ["NERV", "SEELE", "WILLE", "GEHIRN"] },
  { c: 3, q: "What is the name of Ichigo's zanpakuto in Bleach?", a: ["Zangetsu", "Senbonzakura", "Hyorinmaru", "Sode no Shirayuki"] },
  { c: 3, q: "Which criminal organisation in Naruto wears black cloaks with red clouds?", a: ["The Akatsuki", "The Anbu", "The Sound Four", "The Sannin"] },
  { c: 3, q: "Which mangaka created Astro Boy and is known as the god of manga?", a: ["Osamu Tezuka", "Go Nagai", "Shotaro Ishinomori", "Leiji Matsumoto"] },
  { c: 3, q: "Which demographic label describes manga aimed at young girls?", a: ["Shojo", "Shonen", "Seinen", "Josei"] },
  { c: 3, q: "Which demographic label describes manga aimed at adult men?", a: ["Seinen", "Shonen", "Shojo", "Kodomomuke"] },
  { c: 3, q: "Which swordsman is Zoro's ultimate target in One Piece?", a: ["Dracule Mihawk", "Shanks", "Kaido", "Sanji"] },
  { c: 3, q: "Which studio animated the first season of Jujutsu Kaisen?", a: ["MAPPA", "Ufotable", "Wit Studio", "Madhouse"] },
  { c: 3, q: "What is Mikasa's surname in Attack on Titan?", a: ["Ackerman", "Arlert", "Yeager", "Leonhart"] },
  { c: 3, q: "What is L's full name in Death Note?", a: ["L Lawliet", "L Ryuzaki", "L Coil", "L Deneuve"] },
  { c: 3, q: "Which anime's soundtrack by Yoko Kanno opens with the track \"Tank!\"?", a: ["Cowboy Bebop", "Samurai Champloo", "Wolf's Rain", "Macross Plus"] },
  { c: 3, q: "In which region does Ash begin his journey in the Pokémon anime?", a: ["Kanto", "Johto", "Hoenn", "Sinnoh"] },
  { c: 3, q: "Which earlier Yoshihiro Togashi series preceded Hunter x Hunter?", a: ["Yu Yu Hakusho", "Rurouni Kenshin", "Flame of Recca", "Shaman King"] },
  { c: 3, q: "Who is the demon king in Demon Slayer?", a: ["Muzan Kibutsuji", "Akaza", "Kokushibo", "Doma"] },
  { c: 3, q: "Which breathing style does Tanjiro first learn?", a: ["Water Breathing", "Sun Breathing", "Thunder Breathing", "Flame Breathing"] },
  { c: 3, q: "What is All Might's quirk in My Hero Academia called?", a: ["One For All", "All For One", "Overhaul", "Plus Ultra"] },
  { c: 3, q: "Which studio made Kill la Kill and Promare?", a: ["Studio Trigger", "Gainax", "Bones", "Sunrise"] },
  { c: 3, q: "In Fate/stay night, what are the seven summoned Servants competing for?", a: ["The Holy Grail", "The Root", "The Jewelled Sword", "The Sacred Chalice of Camelot"] },
  { c: 3, q: "Which anime follows Senku rebuilding civilisation after humanity is turned to stone?", a: ["Dr. Stone", "Fire Force", "Made in Abyss", "Land of the Lustrous"] },
  { c: 3, q: "What is Mob's real name in Mob Psycho 100?", a: ["Shigeo Kageyama", "Arataka Reigen", "Ritsu Kageyama", "Teruki Hanazawa"] },
  { c: 3, q: "Who wrote the original webcomics for both One Punch Man and Mob Psycho 100?", a: ["ONE", "Yusuke Murata", "Hiro Mashima", "Kohei Horikoshi"] },
  { c: 3, q: "Which Nen category does Gon Freecss belong to?", a: ["Enhancement", "Transmutation", "Emission", "Manipulation"] },
  { c: 3, q: "What is Spike Spiegel's ship called in Cowboy Bebop?", a: ["The Swordfish II", "The Red Tail", "The Hammerhead", "The Bebop"] },
  { c: 3, q: "In Death Note, what does the shinigami eye deal cost?", a: ["Half of the user's remaining lifespan", "The user's memories", "The user's name", "A year of the user's life"] },
  { c: 3, q: "Which 1979 series launched the Gundam franchise?", a: ["Mobile Suit Gundam", "Gundam Wing", "Zeta Gundam", "Gundam SEED"] },
  { c: 3, q: "Which mangaka drew Death Note from Tsugumi Ohba's scripts?", a: ["Takeshi Obata", "Tite Kubo", "Hiromu Arakawa", "Yusuke Murata"] },
  { c: 3, q: "Which manga by Hiromu Arakawa is set in the country of Amestris?", a: ["Fullmetal Alchemist", "Silver Spoon", "Arslan Senki", "Hero Tales"] },
  { c: 3, q: "In Steins;Gate, which everyday appliance is turned into a time machine?", a: ["A microwave", "A television", "A fridge", "A hairdryer"] },
  { c: 3, q: "Which magazine has serialised Berserk?", a: ["Young Animal", "Weekly Shonen Jump", "Big Comic Spirits", "Monthly Shonen Gangan"] },
  { c: 3, q: "In Fist of the North Star, what does Kenshiro say to defeated foes?", a: ["\"You are already dead\"", "\"Prepare yourself\"", "\"This is the end\"", "\"Kneel before me\""] },

  // --------------------------------------------------------- Video Games
  { c: 5, q: "Which Atari game was famously buried in a New Mexico landfill after flopping?", a: ["E.T. the Extra-Terrestrial", "Pac-Man", "Pitfall!", "Adventure"] },
  { c: 5, q: "Who created Mario and The Legend of Zelda?", a: ["Shigeru Miyamoto", "Satoru Iwata", "Gunpei Yokoi", "Hiroshi Yamauchi"] },
  { c: 5, q: "Which game engine is made by Epic Games?", a: ["Unreal Engine", "Unity", "CryEngine", "Source"] },
  { c: 5, q: "Which studio released Doom in 1993?", a: ["id Software", "3D Realms", "Epic MegaGames", "Valve"] },
  { c: 5, q: "Who composed the music for Super Mario Bros. and The Legend of Zelda?", a: ["Koji Kondo", "Nobuo Uematsu", "Yoko Shimomura", "Yuzo Koshiro"] },
  { c: 5, q: "Which was Sega's final home console?", a: ["The Dreamcast", "The Saturn", "The Mega Drive", "The Game Gear"] },
  { c: 5, q: "What was Mario originally called in Donkey Kong?", a: ["Jumpman", "Mr. Video", "Kong Man", "Pauline's Hero"] },
  { c: 5, q: "Which studio developed The Witcher 3?", a: ["CD Projekt Red", "Bethesda", "BioWare", "Larian"] },
  { c: 5, q: "In Dark Souls, what do you spend to level up?", a: ["Souls", "Blood echoes", "Runes", "Embers"] },
  { c: 5, q: "Which studio developed Elden Ring?", a: ["FromSoftware", "Team Ninja", "Platinum Games", "Atlus"] },
  { c: 5, q: "Which novelist built the background world of Elden Ring with Hidetaka Miyazaki?", a: ["George R. R. Martin", "Neil Gaiman", "Brandon Sanderson", "Patrick Rothfuss"] },
  { c: 5, q: "Which 1998 Nintendo 64 game is routinely called one of the greatest ever made?", a: ["The Legend of Zelda: Ocarina of Time", "GoldenEye 007", "Banjo-Kazooie", "Perfect Dark"] },
  { c: 5, q: "Which was the best-selling game on the SNES?", a: ["Super Mario World", "Super Mario Kart", "Donkey Kong Country", "The Legend of Zelda: A Link to the Past"] },
  { c: 5, q: "Brendan Greene, the creator of PUBG, is better known by which handle?", a: ["PlayerUnknown", "Bluehole", "Battle Royale", "Irish Gamer"] },
  { c: 5, q: "Which processor powered the PlayStation 3?", a: ["The Cell", "The Emotion Engine", "The Xenon", "The Jaguar"] },
  { c: 5, q: "Which studio makes the Grand Theft Auto series?", a: ["Rockstar", "Take-Two Interactive", "Ubisoft", "2K Czech"] },
  { c: 5, q: "What does the name Sega come from?", a: ["Service Games", "Sensational Gaming", "Segasonic", "Seiko Games"] },
  { c: 5, q: "Which game is set in the underwater city of Rapture?", a: ["BioShock", "BioShock Infinite", "SOMA", "Subnautica"] },
  { c: 5, q: "Which game is set in the floating city of Columbia?", a: ["BioShock Infinite", "BioShock 2", "Dishonored", "Skies of Arcadia"] },
  { c: 5, q: "Which Final Fantasy game introduced Cloud Strife?", a: ["Final Fantasy VII", "Final Fantasy VI", "Final Fantasy VIII", "Final Fantasy X"] },
  { c: 5, q: "Who composed the music for the early Final Fantasy games?", a: ["Nobuo Uematsu", "Yasunori Mitsuda", "Koji Kondo", "Motoi Sakuraba"] },
  { c: 5, q: "What is the name of the murderous AI in Portal?", a: ["GLaDOS", "SHODAN", "Wheatley", "AM"] },
  { c: 5, q: "Which series features the Umbrella Corporation?", a: ["Resident Evil", "Silent Hill", "Dead Space", "The Evil Within"] },
  { c: 5, q: "Which Nintendo handheld introduced a second, touch-sensitive screen?", a: ["The Nintendo DS", "The Game Boy Advance", "The 3DS", "The Virtual Boy"] },
  { c: 5, q: "Which Blizzard MMORPG launched in 2004?", a: ["World of Warcraft", "Diablo II", "EverQuest", "Guild Wars"] },
  { c: 5, q: "Which 1985 game is credited with reviving the American console market?", a: ["Super Mario Bros.", "Duck Hunt", "Donkey Kong", "Tetris"] },
  { c: 5, q: "What was Sony's first handheld console?", a: ["The PlayStation Portable", "The PlayStation Vita", "The PocketStation", "The PSX"] },
  { c: 5, q: "Which 2019 Hideo Kojima game stars Norman Reedus as a courier?", a: ["Death Stranding", "Metal Gear Solid V", "Days Gone", "Control"] },
  { c: 5, q: "Which Capcom character is nicknamed the Blue Bomber?", a: ["Mega Man", "Mega Man X", "Zero", "Proto Man"] },
  { c: 5, q: "Who created Tetris in 1984?", a: ["Alexey Pajitnov", "Vladimir Pokhilko", "Henk Rogers", "Nikolai Belikov"] },
  { c: 5, q: "In speedrunning, what does an \"any%\" run mean?", a: ["Reaching the end as fast as possible, ignoring completion", "Collecting every item in the game", "Playing without taking damage", "Running with no save files"] },
  { c: 5, q: "Which game series stars the physicist Gordon Freeman?", a: ["Half-Life", "Portal", "Doom", "Quake"] },
  { c: 5, q: "Which racing simulator series is Sony's flagship?", a: ["Gran Turismo", "Forza Motorsport", "Project CARS", "Assetto Corsa"] },
  { c: 5, q: "Which series stars the monster hunter Geralt of Rivia?", a: ["The Witcher", "Dragon Age", "Kingdom Come: Deliverance", "Elex"] },
  { c: 5, q: "Who created Undertale almost single-handedly?", a: ["Toby Fox", "Edmund McMillen", "Jonathan Blow", "Lucas Pope"] },
  { c: 5, q: "Which fictional company runs the test chambers in Portal?", a: ["Aperture Science", "Black Mesa", "Umbrella", "Abstergo"] },
  { c: 5, q: "What is the player character called in Skyrim?", a: ["The Dragonborn", "The Nerevarine", "The Champion of Cyrodiil", "The Vestige"] },
  { c: 5, q: "Which console was Bloodborne released for exclusively?", a: ["The PlayStation 4", "The Xbox One", "The PlayStation 3", "The PC"] },
  { c: 5, q: "Which 2018 Rockstar game stars Arthur Morgan?", a: ["Red Dead Redemption 2", "Red Dead Redemption", "Grand Theft Auto V", "Bully"] },
  { c: 5, q: "Which 1996 game pioneered analogue control in 3D platforming?", a: ["Super Mario 64", "Crash Bandicoot", "Tomb Raider", "Spyro the Dragon"] },
  { c: 5, q: "Which esports title holds the tournament called The International?", a: ["Dota 2", "League of Legends", "Counter-Strike", "StarCraft II"] },
  { c: 5, q: "In League of Legends, what structure must a team destroy to win?", a: ["The Nexus", "The Ancient", "The Throne", "The Core"] },
  { c: 5, q: "Which Nintendo series stars the bounty hunter Samus Aran?", a: ["Metroid", "F-Zero", "Star Fox", "Kid Icarus"] },
  { c: 5, q: "The roguelike genre is named after which 1980 game?", a: ["Rogue", "NetHack", "Angband", "Moria"] },
  { c: 5, q: "Which Swedish developer created Minecraft?", a: ["Markus \"Notch\" Persson", "Jens Bergensten", "Daniel Rosenfeld", "Carl Manneh"] },
  { c: 5, q: "Which company bought Mojang in 2014?", a: ["Microsoft", "Sony", "Tencent", "Valve"] },
  { c: 5, q: "Which is the best-selling handheld console of all time?", a: ["The Nintendo DS", "The Game Boy", "The PlayStation Portable", "The Game Boy Advance"] },
  { c: 5, q: "What is Ryu's signature projectile attack in Street Fighter called?", a: ["The Hadouken", "The Shoryuken", "The Tatsumaki", "The Sonic Boom"] },
  { c: 5, q: "Who is the antagonist of The Legend of Zelda: Breath of the Wild?", a: ["Calamity Ganon", "Ganondorf", "Vaati", "Zant"] },
  { c: 5, q: "What does MMORPG stand for?", a: ["Massively multiplayer online role-playing game", "Multi-mode online role-playing game", "Massive multiplayer offline RPG", "Multiplayer mission-oriented RPG"] },
  { c: 5, q: "The Sega Genesis was sold under which name outside North America?", a: ["The Mega Drive", "The Master System", "The Saturn", "The Mark III"] },
  { c: 5, q: "Which game won the first Game of the Year at The Game Awards in 2014?", a: ["Dragon Age: Inquisition", "Middle-earth: Shadow of Mordor", "Bayonetta 2", "Hearthstone"] },
  { c: 5, q: "Which studio developed Hollow Knight?", a: ["Team Cherry", "Motion Twin", "Supergiant Games", "Moon Studios"] },
  { c: 5, q: "Which company developed the original Sonic the Hedgehog?", a: ["Sonic Team", "Sega Technical Institute", "Yuji Naka Games", "Sega AM2"] },
  { c: 5, q: "Which 2016 game by id Software rebooted a classic shooter with a chainsaw and glory kills?", a: ["Doom", "Quake Champions", "Wolfenstein: The New Order", "Rage 2"] },
];

// The two carried-over categories come straight from the classic arrays, so
// their wording, ids and player ratings stay shared between the editions.
const EASY = [...EASY_NERD, ...classic.EASY.filter((q) => CARRIED_OVER.has(q.c))];
const HARD = [...HARD_NERD, ...classic.HARD.filter((q) => CARRIED_OVER.has(q.c))];

const ALL = classic.build(EASY, HARD, 'questions-nerd.js');

module.exports = ALL;
module.exports.EASY = EASY;
module.exports.HARD = HARD;
