'use strict';

/**
 * Question bank.
 *
 * Format: { c: <category id>, q: "<question>", a: ["correct", "wrong", "wrong", "wrong"] }
 * The first answer is always the correct one; the server shuffles before sending.
 *
 * Categories: 0 Geography | 1 Entertainment | 2 History
 *             3 Arts & Literature | 4 Science & Nature | 5 Sports & Leisure
 *
 * Two difficulty tiers, chosen in the lobby. Add your own by appending to
 * whichever array fits - the difficulty tag is applied automatically at the
 * bottom of this file, so entries in both arrays look identical.
 */

// --------------------------------------------------------------------------
// EASY - general knowledge, most players will get a good share of these.
// --------------------------------------------------------------------------
const EASY = [
  // ---------------------------------------------------------------- Geography
  { c: 0, q: "What is the capital of Australia?", a: ["Canberra", "Sydney", "Melbourne", "Perth"] },
  { c: 0, q: "Which river flows through Cairo?", a: ["The Nile", "The Congo", "The Niger", "The Zambezi"] },
  { c: 0, q: "Which is the largest country in the world by land area?", a: ["Russia", "Canada", "China", "The United States"] },
  { c: 0, q: "Mount Everest sits on the border of Nepal and which other country?", a: ["China", "India", "Bhutan", "Pakistan"] },
  { c: 0, q: "Which US state is nicknamed the Sunshine State?", a: ["Florida", "California", "Arizona", "Hawaii"] },
  { c: 0, q: "Which strait separates Spain from Morocco?", a: ["The Strait of Gibraltar", "The Bosphorus", "The Strait of Hormuz", "The Strait of Malacca"] },
  { c: 0, q: "What is the capital of Canada?", a: ["Ottawa", "Toronto", "Vancouver", "Montreal"] },
  { c: 0, q: "Which is the largest hot desert in the world?", a: ["The Sahara", "The Gobi", "The Kalahari", "The Arabian Desert"] },
  { c: 0, q: "Which is the longest river in South America?", a: ["The Amazon", "The Paraná", "The Orinoco", "The Magdalena"] },
  { c: 0, q: "The fjord-lined city of Bergen is in which country?", a: ["Norway", "Sweden", "Denmark", "Finland"] },
  { c: 0, q: "What is the smallest country in the world by area?", a: ["Vatican City", "Monaco", "Nauru", "San Marino"] },
  { c: 0, q: "Which country is entirely surrounded by South Africa?", a: ["Lesotho", "Eswatini", "Botswana", "Namibia"] },
  { c: 0, q: "Which is the deepest ocean?", a: ["The Pacific", "The Atlantic", "The Indian", "The Arctic"] },
  { c: 0, q: "Istanbul straddles which two continents?", a: ["Europe and Asia", "Asia and Africa", "Europe and Africa", "Europe and the Middle East"] },
  { c: 0, q: "What is the capital of New Zealand?", a: ["Wellington", "Auckland", "Christchurch", "Dunedin"] },
  { c: 0, q: "Which mountain range separates France from Spain?", a: ["The Pyrenees", "The Alps", "The Apennines", "The Carpathians"] },
  { c: 0, q: "Which country's flag features a red maple leaf?", a: ["Canada", "Lebanon", "Japan", "Switzerland"] },
  { c: 0, q: "Lake Baikal, the world's deepest lake, is in which country?", a: ["Russia", "Mongolia", "Kazakhstan", "China"] },
  { c: 0, q: "The Atacama Desert lies mainly in which country?", a: ["Chile", "Peru", "Argentina", "Bolivia"] },
  { c: 0, q: "What is the capital of Brazil?", a: ["Brasília", "Rio de Janeiro", "São Paulo", "Salvador"] },
  { c: 0, q: "Which US state is the largest by area?", a: ["Alaska", "Texas", "California", "Montana"] },
  { c: 0, q: "The Danube empties into which sea?", a: ["The Black Sea", "The Adriatic Sea", "The Baltic Sea", "The Caspian Sea"] },
  { c: 0, q: "Which is the largest island in the world?", a: ["Greenland", "New Guinea", "Borneo", "Madagascar"] },
  { c: 0, q: "Which country is known as the Land of the Rising Sun?", a: ["Japan", "China", "South Korea", "Thailand"] },
  { c: 0, q: "Which European capital sits at the mouth of the River Tagus?", a: ["Lisbon", "Madrid", "Seville", "Barcelona"] },
  { c: 0, q: "The Great Barrier Reef lies off the coast of which Australian state?", a: ["Queensland", "Western Australia", "New South Wales", "Victoria"] },
  { c: 0, q: "Which canal links the Mediterranean Sea to the Red Sea?", a: ["The Suez Canal", "The Panama Canal", "The Kiel Canal", "The Corinth Canal"] },
  { c: 0, q: "Which African country has the largest population?", a: ["Nigeria", "Ethiopia", "Egypt", "South Africa"] },
  { c: 0, q: "Machu Picchu is located in which country?", a: ["Peru", "Bolivia", "Ecuador", "Chile"] },
  { c: 0, q: "Which body of water has the lowest shoreline on Earth?", a: ["The Dead Sea", "The Caspian Sea", "The Great Salt Lake", "Lake Eyre"] },
  { c: 0, q: "Which of these national capitals lies furthest north?", a: ["Reykjavík", "Oslo", "Helsinki", "Stockholm"] },
  { c: 0, q: "The city of Timbuktu is in which country?", a: ["Mali", "Niger", "Chad", "Senegal"] },
  { c: 0, q: "Which two countries share the world's longest international border?", a: ["The US and Canada", "Russia and China", "Argentina and Chile", "Russia and Kazakhstan"] },
  { c: 0, q: "What is the official language of Brazil?", a: ["Portuguese", "Spanish", "French", "Brazilian"] },
  { c: 0, q: "What is the highest mountain in Africa?", a: ["Kilimanjaro", "Mount Kenya", "Mount Elgon", "Mount Toubkal"] },
  { c: 0, q: "The Yucatán Peninsula belongs mostly to which country?", a: ["Mexico", "Belize", "Guatemala", "Honduras"] },
  { c: 0, q: "In which city would you find the Brandenburg Gate?", a: ["Berlin", "Munich", "Vienna", "Hamburg"] },
  { c: 0, q: "Which strait separates Alaska from Russia?", a: ["The Bering Strait", "The Denmark Strait", "The Davis Strait", "The Cook Strait"] },
  { c: 0, q: "Which continent contains the Serengeti?", a: ["Africa", "Asia", "South America", "Australia"] },
  { c: 0, q: "Which country has the most inhabited islands, numbering over 17,000?", a: ["Indonesia", "The Philippines", "Japan", "Greece"] },

  // ----------------------------------------------------------- Entertainment
  { c: 1, q: "Who directed the 1975 film Jaws?", a: ["Steven Spielberg", "George Lucas", "Martin Scorsese", "Francis Ford Coppola"] },
  { c: 1, q: "Who played Jack in the 1997 film Titanic?", a: ["Leonardo DiCaprio", "Brad Pitt", "Matt Damon", "Johnny Depp"] },
  { c: 1, q: "\"Here's Johnny!\" is a famous line from which horror film?", a: ["The Shining", "Psycho", "Halloween", "The Exorcist"] },
  { c: 1, q: "Which band released \"Bohemian Rhapsody\"?", a: ["Queen", "The Rolling Stones", "Pink Floyd", "The Who"] },
  { c: 1, q: "Who played Neo in The Matrix?", a: ["Keanu Reeves", "Tom Cruise", "Will Smith", "Nicolas Cage"] },
  { c: 1, q: "Which Disney film features a lion cub named Simba?", a: ["The Lion King", "The Jungle Book", "Tarzan", "Brother Bear"] },
  { c: 1, q: "Which Michael Jackson album is the best-selling of all time?", a: ["Thriller", "Bad", "Off the Wall", "Dangerous"] },
  { c: 1, q: "Which TV series is set in the town of Hawkins, Indiana?", a: ["Stranger Things", "Twin Peaks", "Riverdale", "The X-Files"] },
  { c: 1, q: "In which sitcom do the characters hang out at Central Perk?", a: ["Friends", "Seinfeld", "How I Met Your Mother", "Cheers"] },
  { c: 1, q: "Which 1994 film won the Academy Award for Best Picture?", a: ["Forrest Gump", "Pulp Fiction", "The Shawshank Redemption", "Four Weddings and a Funeral"] },
  { c: 1, q: "Who is the lead singer of the band U2?", a: ["Bono", "Sting", "Chris Martin", "Michael Stipe"] },
  { c: 1, q: "What is the name of the wizarding school in the Harry Potter films?", a: ["Hogwarts", "Durmstrang", "Beauxbatons", "Ilvermorny"] },
  { c: 1, q: "Which studio produced the 1995 film Toy Story?", a: ["Pixar", "DreamWorks", "Studio Ghibli", "Blue Sky"] },
  { c: 1, q: "Who played Iron Man in the Marvel Cinematic Universe?", a: ["Robert Downey Jr.", "Chris Evans", "Mark Ruffalo", "Chris Hemsworth"] },
  { c: 1, q: "The song \"Defying Gravity\" comes from which musical?", a: ["Wicked", "Hamilton", "Rent", "Chicago"] },
  { c: 1, q: "Which musician wrote and performed \"Purple Rain\"?", a: ["Prince", "David Bowie", "Lenny Kravitz", "Stevie Wonder"] },
  { c: 1, q: "The Iron Throne appears in which television series?", a: ["Game of Thrones", "The Witcher", "Vikings", "Rome"] },
  { c: 1, q: "The Beatles formed in which English city?", a: ["Liverpool", "Manchester", "London", "Birmingham"] },
  { c: 1, q: "Who hosted The Tonight Show for 30 years until 1992?", a: ["Johnny Carson", "David Letterman", "Jay Leno", "Conan O'Brien"] },
  { c: 1, q: "\"I'll be back\" is a catchphrase from which film franchise?", a: ["The Terminator", "Die Hard", "RoboCop", "Rambo"] },
  { c: 1, q: "Who recorded the 1965 song \"Like a Rolling Stone\"?", a: ["Bob Dylan", "Neil Young", "Johnny Cash", "Bruce Springsteen"] },
  { c: 1, q: "Who directed Pulp Fiction?", a: ["Quentin Tarantino", "Robert Rodriguez", "David Fincher", "Guy Ritchie"] },
  { c: 1, q: "Michael Scott is the regional manager in which sitcom?", a: ["The Office", "Parks and Recreation", "30 Rock", "Brooklyn Nine-Nine"] },
  { c: 1, q: "Which singer is known as the Queen of Soul?", a: ["Aretha Franklin", "Diana Ross", "Tina Turner", "Whitney Houston"] },
  { c: 1, q: "Who composed the scores for Star Wars, Jaws and Jurassic Park?", a: ["John Williams", "Hans Zimmer", "Ennio Morricone", "Danny Elfman"] },
  { c: 1, q: "Which Disney princess loses a glass slipper at a ball?", a: ["Cinderella", "Snow White", "Belle", "Aurora"] },
  { c: 1, q: "The pop group ABBA came from which country?", a: ["Sweden", "Norway", "Denmark", "The Netherlands"] },
  { c: 1, q: "Which actor starred as Forrest Gump?", a: ["Tom Hanks", "Kevin Costner", "Robin Williams", "Bill Murray"] },
  { c: 1, q: "\"My Heart Will Go On\" was the theme song to which film?", a: ["Titanic", "The Bodyguard", "Ghost", "Armageddon"] },
  { c: 1, q: "Which series follows a chemistry teacher named Walter White?", a: ["Breaking Bad", "Better Call Saul", "Ozark", "Weeds"] },
  { c: 1, q: "Which rock band's drummer was John Bonham?", a: ["Led Zeppelin", "The Rolling Stones", "Deep Purple", "Black Sabbath"] },
  { c: 1, q: "Who voiced Woody in the Toy Story films?", a: ["Tom Hanks", "Tim Allen", "Billy Crystal", "John Goodman"] },
  { c: 1, q: "The Bollywood film industry is based in which country?", a: ["India", "Pakistan", "Bangladesh", "Nepal"] },
  { c: 1, q: "What is the name of Batman's butler?", a: ["Alfred", "Jarvis", "Lucius", "Bruce"] },
  { c: 1, q: "Which Best Picture winner features the character Hannibal Lecter?", a: ["The Silence of the Lambs", "Se7en", "Zodiac", "American Psycho"] },
  { c: 1, q: "Which band recorded \"Hotel California\"?", a: ["The Eagles", "Fleetwood Mac", "The Doobie Brothers", "Steely Dan"] },
  { c: 1, q: "Who created the character Mickey Mouse?", a: ["Walt Disney", "Chuck Jones", "Hanna and Barbera", "Max Fleischer"] },
  { c: 1, q: "Which film features the song \"Somewhere Over the Rainbow\"?", a: ["The Wizard of Oz", "Mary Poppins", "Singin' in the Rain", "The Sound of Music"] },
  { c: 1, q: "Which anime studio produced Spirited Away?", a: ["Studio Ghibli", "Toei Animation", "Madhouse", "Kyoto Animation"] },
  { c: 1, q: "Who played Captain Jack Sparrow in Pirates of the Caribbean?", a: ["Johnny Depp", "Orlando Bloom", "Geoffrey Rush", "Javier Bardem"] },

  // ----------------------------------------------------------------- History
  { c: 2, q: "In which year did the Second World War end?", a: ["1945", "1944", "1946", "1939"] },
  { c: 2, q: "Who was the first President of the United States?", a: ["George Washington", "Thomas Jefferson", "John Adams", "Benjamin Franklin"] },
  { c: 2, q: "Which empire built Machu Picchu?", a: ["The Inca", "The Aztec", "The Maya", "The Olmec"] },
  { c: 2, q: "In which year did the Berlin Wall fall?", a: ["1989", "1991", "1987", "1993"] },
  { c: 2, q: "Who was the first person to walk on the Moon?", a: ["Neil Armstrong", "Buzz Aldrin", "Yuri Gagarin", "Michael Collins"] },
  { c: 2, q: "Which ocean liner sank on its maiden voyage in 1912?", a: ["The Titanic", "The Lusitania", "The Britannic", "The Andrea Doria"] },
  { c: 2, q: "Who was British Prime Minister for most of the Second World War?", a: ["Winston Churchill", "Neville Chamberlain", "Clement Attlee", "Anthony Eden"] },
  { c: 2, q: "In which year did the French Revolution begin?", a: ["1789", "1776", "1799", "1804"] },
  { c: 2, q: "Who was the principal author of the US Declaration of Independence?", a: ["Thomas Jefferson", "George Washington", "John Adams", "Alexander Hamilton"] },
  { c: 2, q: "Who was assassinated in Dallas, Texas in 1963?", a: ["John F. Kennedy", "Martin Luther King Jr.", "Robert Kennedy", "Malcolm X"] },
  { c: 2, q: "Which queen reigned over Britain from 1837 to 1901?", a: ["Victoria", "Elizabeth I", "Anne", "Mary II"] },
  { c: 2, q: "In which year was the Magna Carta sealed?", a: ["1215", "1066", "1314", "1415"] },
  { c: 2, q: "Hadrian's Wall was built by which empire?", a: ["The Roman Empire", "The Byzantine Empire", "The Holy Roman Empire", "The Norman Kingdom"] },
  { c: 2, q: "Who led India's nonviolent independence movement against British rule?", a: ["Mahatma Gandhi", "Jawaharlal Nehru", "Subhas Chandra Bose", "B. R. Ambedkar"] },
  { c: 2, q: "The Cold War was primarily between the United States and which country?", a: ["The Soviet Union", "China", "Germany", "Cuba"] },
  { c: 2, q: "Whose expedition first circumnavigated the globe?", a: ["Ferdinand Magellan", "Christopher Columbus", "Vasco da Gama", "Francis Drake"] },
  { c: 2, q: "In which year was Pearl Harbor attacked?", a: ["1941", "1939", "1942", "1940"] },
  { c: 2, q: "Who was the first female Prime Minister of the United Kingdom?", a: ["Margaret Thatcher", "Theresa May", "Barbara Castle", "Nancy Astor"] },
  { c: 2, q: "Which ancient civilisation developed cuneiform writing?", a: ["The Sumerians", "The Egyptians", "The Phoenicians", "The Minoans"] },
  { c: 2, q: "Which US president issued the Emancipation Proclamation?", a: ["Abraham Lincoln", "Ulysses S. Grant", "Andrew Johnson", "James Buchanan"] },
  { c: 2, q: "In which year did the Russian Revolution overthrow the Tsar?", a: ["1917", "1905", "1921", "1914"] },
  { c: 2, q: "Which Egyptian queen was allied with Julius Caesar and Mark Antony?", a: ["Cleopatra", "Nefertiti", "Hatshepsut", "Ankhesenamun"] },
  { c: 2, q: "Which country gave the Statue of Liberty to the United States?", a: ["France", "Britain", "Spain", "Italy"] },
  { c: 2, q: "Apartheid was a system of racial segregation in which country?", a: ["South Africa", "Zimbabwe", "Namibia", "Kenya"] },
  { c: 2, q: "Who published the Ninety-five Theses in 1517?", a: ["Martin Luther", "John Calvin", "Henry VIII", "Erasmus"] },
  { c: 2, q: "Which 1815 battle ended Napoleon's rule?", a: ["Waterloo", "Trafalgar", "Austerlitz", "Borodino"] },
  { c: 2, q: "In which year was the Great Fire of London?", a: ["1666", "1605", "1712", "1580"] },
  { c: 2, q: "The Tokugawa shogunate ruled which country?", a: ["Japan", "China", "Korea", "Vietnam"] },
  { c: 2, q: "Who discovered the tomb of Tutankhamun in 1922?", a: ["Howard Carter", "Heinrich Schliemann", "Arthur Evans", "Flinders Petrie"] },
  { c: 2, q: "Which military alliance was founded in 1949?", a: ["NATO", "The Warsaw Pact", "The United Nations", "The League of Nations"] },
  { c: 2, q: "The Hundred Years' War was fought between England and which country?", a: ["France", "Spain", "Scotland", "The Netherlands"] },
  { c: 2, q: "Who was the first Emperor of Rome?", a: ["Augustus", "Julius Caesar", "Nero", "Constantine"] },
  { c: 2, q: "Which South African leader spent 27 years in prison before becoming president?", a: ["Nelson Mandela", "Desmond Tutu", "Steve Biko", "Thabo Mbeki"] },
  { c: 2, q: "In which year was the US Declaration of Independence adopted?", a: ["1776", "1781", "1783", "1774"] },
  { c: 2, q: "In which year did the Boston Tea Party take place?", a: ["1773", "1776", "1765", "1781"] },
  { c: 2, q: "Which pandemic swept Europe in the 14th century?", a: ["The Black Death", "The Spanish Flu", "Cholera", "Smallpox"] },
  { c: 2, q: "Which wall divided a German city until 1989?", a: ["The Berlin Wall", "The Iron Curtain Wall", "The Rhine Wall", "The Elbe Wall"] },
  { c: 2, q: "The Renaissance began in which country?", a: ["Italy", "France", "England", "Germany"] },
  { c: 2, q: "Who was the Macedonian king who conquered the Persian Empire?", a: ["Alexander the Great", "Philip II", "Darius III", "Xerxes"] },
  { c: 2, q: "In which year did the Chernobyl nuclear disaster occur?", a: ["1986", "1979", "1991", "1983"] },

  // ------------------------------------------------------- Arts & Literature
  { c: 3, q: "Who painted the Mona Lisa?", a: ["Leonardo da Vinci", "Michelangelo", "Raphael", "Titian"] },
  { c: 3, q: "Who wrote Romeo and Juliet?", a: ["William Shakespeare", "Christopher Marlowe", "Ben Jonson", "John Webster"] },
  { c: 3, q: "Who wrote Pride and Prejudice?", a: ["Jane Austen", "Emily Brontë", "George Eliot", "Elizabeth Gaskell"] },
  { c: 3, q: "Who painted The Persistence of Memory, with its melting clocks?", a: ["Salvador Dalí", "René Magritte", "Joan Miró", "Max Ernst"] },
  { c: 3, q: "Who wrote the novel 1984?", a: ["George Orwell", "Aldous Huxley", "Ray Bradbury", "H. G. Wells"] },
  { c: 3, q: "Which Russian author wrote War and Peace?", a: ["Leo Tolstoy", "Fyodor Dostoevsky", "Anton Chekhov", "Ivan Turgenev"] },
  { c: 3, q: "Who sculpted the marble statue of David in Florence?", a: ["Michelangelo", "Donatello", "Bernini", "Cellini"] },
  { c: 3, q: "Who wrote The Great Gatsby?", a: ["F. Scott Fitzgerald", "Ernest Hemingway", "John Steinbeck", "William Faulkner"] },
  { c: 3, q: "Who wrote the poem \"The Raven\"?", a: ["Edgar Allan Poe", "Walt Whitman", "Emily Dickinson", "Robert Frost"] },
  { c: 3, q: "Who wrote the Harry Potter novels?", a: ["J. K. Rowling", "Philip Pullman", "Suzanne Collins", "Rick Riordan"] },
  { c: 3, q: "Pablo Picasso co-founded which art movement?", a: ["Cubism", "Surrealism", "Impressionism", "Fauvism"] },
  { c: 3, q: "Which novel opens with the line \"It was the best of times, it was the worst of times\"?", a: ["A Tale of Two Cities", "Great Expectations", "Oliver Twist", "Bleak House"] },
  { c: 3, q: "Who painted The Starry Night?", a: ["Vincent van Gogh", "Claude Monet", "Paul Cézanne", "Paul Gauguin"] },
  { c: 3, q: "Who wrote Don Quixote?", a: ["Miguel de Cervantes", "Lope de Vega", "Federico García Lorca", "Gabriel García Márquez"] },
  { c: 3, q: "Which Greek epic recounts the journey home of Odysseus?", a: ["The Odyssey", "The Iliad", "The Aeneid", "Theogony"] },
  { c: 3, q: "Who wrote The Old Man and the Sea?", a: ["Ernest Hemingway", "John Steinbeck", "Jack London", "Herman Melville"] },
  { c: 3, q: "Michelangelo painted the ceiling of which chapel?", a: ["The Sistine Chapel", "The Pauline Chapel", "The Scrovegni Chapel", "King's College Chapel"] },
  { c: 3, q: "Who wrote Crime and Punishment?", a: ["Fyodor Dostoevsky", "Leo Tolstoy", "Nikolai Gogol", "Maxim Gorky"] },
  { c: 3, q: "Which Norwegian playwright wrote A Doll's House?", a: ["Henrik Ibsen", "August Strindberg", "Knut Hamsun", "Anton Chekhov"] },
  { c: 3, q: "Who wrote To Kill a Mockingbird?", a: ["Harper Lee", "Toni Morrison", "Flannery O'Connor", "Carson McCullers"] },
  { c: 3, q: "Which pop artist is famous for paintings of Campbell's soup cans?", a: ["Andy Warhol", "Roy Lichtenstein", "Jasper Johns", "Robert Rauschenberg"] },
  { c: 3, q: "Who wrote The Lord of the Rings?", a: ["J. R. R. Tolkien", "C. S. Lewis", "Terry Pratchett", "Ursula K. Le Guin"] },
  { c: 3, q: "Which museum houses the Mona Lisa?", a: ["The Louvre", "The Uffizi", "The Prado", "The Hermitage"] },
  { c: 3, q: "Who composed The Four Seasons?", a: ["Antonio Vivaldi", "Johann Sebastian Bach", "George Frideric Handel", "Joseph Haydn"] },
  { c: 3, q: "Which composer wrote the Ninth Symphony containing \"Ode to Joy\"?", a: ["Ludwig van Beethoven", "Wolfgang Amadeus Mozart", "Franz Schubert", "Johannes Brahms"] },
  { c: 3, q: "Who wrote Jane Eyre?", a: ["Charlotte Brontë", "Emily Brontë", "Anne Brontë", "Jane Austen"] },
  { c: 3, q: "Which Dutch master painted The Night Watch?", a: ["Rembrandt", "Vermeer", "Frans Hals", "Jan Steen"] },
  { c: 3, q: "Who wrote The Divine Comedy?", a: ["Dante Alighieri", "Petrarch", "Boccaccio", "Virgil"] },
  { c: 3, q: "Which author created Sherlock Holmes?", a: ["Arthur Conan Doyle", "Agatha Christie", "Wilkie Collins", "G. K. Chesterton"] },
  { c: 3, q: "Who wrote the novel Things Fall Apart?", a: ["Chinua Achebe", "Wole Soyinka", "Ngũgĩ wa Thiong'o", "Ben Okri"] },
  { c: 3, q: "Who painted The Scream?", a: ["Edvard Munch", "Gustav Klimt", "Egon Schiele", "Ernst Ludwig Kirchner"] },
  { c: 3, q: "Who wrote One Hundred Years of Solitude?", a: ["Gabriel García Márquez", "Jorge Luis Borges", "Mario Vargas Llosa", "Isabel Allende"] },
  { c: 3, q: "Who wrote the poem \"Do not go gentle into that good night\"?", a: ["Dylan Thomas", "W. B. Yeats", "T. S. Eliot", "Seamus Heaney"] },
  { c: 3, q: "Who composed the opera The Magic Flute?", a: ["Wolfgang Amadeus Mozart", "Giuseppe Verdi", "Richard Wagner", "Giacomo Puccini"] },
  { c: 3, q: "Who wrote Brave New World?", a: ["Aldous Huxley", "George Orwell", "Yevgeny Zamyatin", "Kurt Vonnegut"] },
  { c: 3, q: "Which Shakespeare play features a Prince of Denmark?", a: ["Hamlet", "Macbeth", "King Lear", "Othello"] },
  { c: 3, q: "Who wrote the novel Beloved?", a: ["Toni Morrison", "Alice Walker", "Maya Angelou", "Zora Neale Hurston"] },
  { c: 3, q: "Which American painter is known for his drip technique?", a: ["Jackson Pollock", "Willem de Kooning", "Mark Rothko", "Franz Kline"] },
  { c: 3, q: "Who wrote The Canterbury Tales?", a: ["Geoffrey Chaucer", "Thomas Malory", "John Milton", "Edmund Spenser"] },
  { c: 3, q: "Which artist painted the Water Lilies series?", a: ["Claude Monet", "Édouard Manet", "Pierre-Auguste Renoir", "Edgar Degas"] },

  // ------------------------------------------------------- Science & Nature
  { c: 4, q: "What is the chemical symbol for gold?", a: ["Au", "Ag", "Go", "Gd"] },
  { c: 4, q: "How many bones are there in the adult human body?", a: ["206", "198", "224", "186"] },
  { c: 4, q: "Which planet is known as the Red Planet?", a: ["Mars", "Venus", "Jupiter", "Mercury"] },
  { c: 4, q: "Which gas do plants absorb from the air for photosynthesis?", a: ["Carbon dioxide", "Oxygen", "Nitrogen", "Methane"] },
  { c: 4, q: "Who developed the theory of general relativity?", a: ["Albert Einstein", "Isaac Newton", "Niels Bohr", "Max Planck"] },
  { c: 4, q: "What is the hardest naturally occurring substance?", a: ["Diamond", "Quartz", "Titanium", "Corundum"] },
  { c: 4, q: "How many chambers does the human heart have?", a: ["Four", "Two", "Three", "Six"] },
  { c: 4, q: "Which is the largest planet in our solar system?", a: ["Jupiter", "Saturn", "Neptune", "Uranus"] },
  { c: 4, q: "Which type of blood cell fights infection?", a: ["White blood cells", "Red blood cells", "Platelets", "Plasma cells"] },
  { c: 4, q: "Roughly how fast does light travel in a vacuum?", a: ["300,000 km per second", "300,000 km per hour", "30,000 km per second", "3 million km per second"] },
  { c: 4, q: "Which element has atomic number 1?", a: ["Hydrogen", "Helium", "Oxygen", "Carbon"] },
  { c: 4, q: "Which organ produces insulin?", a: ["The pancreas", "The liver", "The kidney", "The spleen"] },
  { c: 4, q: "What is the largest mammal on Earth?", a: ["The blue whale", "The African elephant", "The sperm whale", "The giraffe"] },
  { c: 4, q: "Sunlight helps the body produce which vitamin?", a: ["Vitamin D", "Vitamin C", "Vitamin A", "Vitamin B12"] },
  { c: 4, q: "What is the study of fossils called?", a: ["Palaeontology", "Archaeology", "Geology", "Anthropology"] },
  { c: 4, q: "Which gas makes up about 78% of Earth's atmosphere?", a: ["Nitrogen", "Oxygen", "Carbon dioxide", "Argon"] },
  { c: 4, q: "Which organelle is known as the powerhouse of the cell?", a: ["The mitochondrion", "The nucleus", "The ribosome", "The Golgi apparatus"] },
  { c: 4, q: "Who formulated the three laws of motion?", a: ["Isaac Newton", "Galileo Galilei", "Johannes Kepler", "Robert Hooke"] },
  { c: 4, q: "How many legs does a spider have?", a: ["Eight", "Six", "Ten", "Twelve"] },
  { c: 4, q: "What is the chemical symbol for sodium?", a: ["Na", "So", "Sd", "S"] },
  { c: 4, q: "What is the closest star to Earth?", a: ["The Sun", "Proxima Centauri", "Sirius", "Alpha Centauri A"] },
  { c: 4, q: "Which is the fastest land animal?", a: ["The cheetah", "The pronghorn", "The lion", "The greyhound"] },
  { c: 4, q: "What does DNA stand for?", a: ["Deoxyribonucleic acid", "Dinucleic acid", "Deoxyribose nitrate", "Double nucleic acid"] },
  { c: 4, q: "Which planet has the most prominent ring system?", a: ["Saturn", "Jupiter", "Uranus", "Neptune"] },
  { c: 4, q: "At what temperature in Fahrenheit does water freeze?", a: ["32 degrees", "0 degrees", "48 degrees", "12 degrees"] },
  { c: 4, q: "Which metal is liquid at room temperature?", a: ["Mercury", "Lead", "Gallium", "Bromine"] },
  { c: 4, q: "What kind of animal is a Komodo dragon?", a: ["A lizard", "A snake", "A crocodile", "An amphibian"] },
  { c: 4, q: "What is the smallest unit of a chemical element?", a: ["An atom", "A molecule", "A cell", "An electron"] },
  { c: 4, q: "What is the largest organ of the human body?", a: ["The skin", "The liver", "The lungs", "The brain"] },
  { c: 4, q: "Who discovered penicillin?", a: ["Alexander Fleming", "Louis Pasteur", "Joseph Lister", "Edward Jenner"] },
  { c: 4, q: "How many teeth does a typical adult human have?", a: ["32", "28", "36", "30"] },
  { c: 4, q: "What is the approximate pH of pure water?", a: ["7", "1", "10", "14"] },
  { c: 4, q: "Which element is the main component of the Sun?", a: ["Hydrogen", "Helium", "Oxygen", "Iron"] },
  { c: 4, q: "What primarily causes ocean tides on Earth?", a: ["The Moon's gravity", "Wind patterns", "Earth's magnetic field", "Ocean currents"] },
  { c: 4, q: "Which dinosaur's name means \"tyrant lizard king\"?", a: ["Tyrannosaurus rex", "Velociraptor", "Allosaurus", "Spinosaurus"] },
  { c: 4, q: "What is the SI unit of force?", a: ["The newton", "The joule", "The watt", "The pascal"] },
  { c: 4, q: "Which scientist proposed the theory of evolution by natural selection?", a: ["Charles Darwin", "Gregor Mendel", "Jean-Baptiste Lamarck", "Alfred Nobel"] },
  { c: 4, q: "How many planets are in our solar system?", a: ["Eight", "Nine", "Seven", "Ten"] },
  { c: 4, q: "Which insect produces honey?", a: ["The bee", "The wasp", "The ant", "The hornet"] },
  { c: 4, q: "Which part of the plant conducts photosynthesis primarily?", a: ["The leaf", "The root", "The stem", "The flower"] },

  // -------------------------------------------------------- Sports & Leisure
  { c: 5, q: "How many players from each team are on the pitch in a soccer match?", a: ["Eleven", "Ten", "Twelve", "Nine"] },
  { c: 5, q: "Which country hosted the 2016 Summer Olympics?", a: ["Brazil", "China", "Britain", "Greece"] },
  { c: 5, q: "How many points is a touchdown worth in American football?", a: ["Six", "Seven", "Three", "Five"] },
  { c: 5, q: "In tennis, what term is used for a score of zero?", a: ["Love", "Nil", "Duck", "Blank"] },
  { c: 5, q: "Which sport is played with a shuttlecock?", a: ["Badminton", "Squash", "Table tennis", "Racquetball"] },
  { c: 5, q: "How many holes are played in a full round of golf?", a: ["18", "9", "20", "12"] },
  { c: 5, q: "Judo originated in which country?", a: ["Japan", "China", "Korea", "Brazil"] },
  { c: 5, q: "How often are the Summer Olympic Games held?", a: ["Every four years", "Every two years", "Every three years", "Every five years"] },
  { c: 5, q: "What is the maximum standard break in snooker?", a: ["147", "155", "180", "100"] },
  { c: 5, q: "Which sport is known as \"the sweet science\"?", a: ["Boxing", "Fencing", "Wrestling", "Archery"] },
  { c: 5, q: "How many players from each team are on the court in basketball?", a: ["Five", "Six", "Four", "Seven"] },
  { c: 5, q: "Which trophy is awarded to the NHL champion?", a: ["The Stanley Cup", "The Vince Lombardi Trophy", "The Commissioner's Trophy", "The Larry O'Brien Trophy"] },
  { c: 5, q: "The Tour de France is a competition in which sport?", a: ["Cycling", "Running", "Motor racing", "Rowing"] },
  { c: 5, q: "How many rings appear on the Olympic flag?", a: ["Five", "Four", "Six", "Seven"] },
  { c: 5, q: "Which country has won the most FIFA World Cups?", a: ["Brazil", "Germany", "Italy", "Argentina"] },
  { c: 5, q: "In baseball, how many strikes make a strikeout?", a: ["Three", "Two", "Four", "Five"] },
  { c: 5, q: "The terms \"birdie\" and \"eagle\" belong to which sport?", a: ["Golf", "Archery", "Falconry", "Cricket"] },
  { c: 5, q: "What colour jersey does the Tour de France overall leader wear?", a: ["Yellow", "Green", "Polka dot", "White"] },
  { c: 5, q: "How long is a marathon, in miles?", a: ["26.2", "24.8", "30", "20.5"] },
  { c: 5, q: "Taekwondo originated in which country?", a: ["Korea", "Japan", "China", "Thailand"] },
  { c: 5, q: "In chess, which piece moves in an L shape?", a: ["The knight", "The bishop", "The rook", "The queen"] },
  { c: 5, q: "How many squares are there on a chessboard?", a: ["64", "81", "100", "49"] },
  { c: 5, q: "Which sport is played at Wimbledon?", a: ["Tennis", "Cricket", "Golf", "Polo"] },
  { c: 5, q: "Which traditional sport is considered Japan's national sport?", a: ["Sumo wrestling", "Karate", "Baseball", "Kendo"] },
  { c: 5, q: "How many players from each team are on the court in volleyball?", a: ["Six", "Five", "Seven", "Four"] },
  { c: 5, q: "In the standard US Monopoly board, which is the most expensive property?", a: ["Boardwalk", "Park Place", "Marvin Gardens", "Pennsylvania Avenue"] },
  { c: 5, q: "The Ashes series is contested in which sport?", a: ["Cricket", "Rugby", "Rowing", "Lawn bowls"] },
  { c: 5, q: "How many cards are in a standard deck without jokers?", a: ["52", "54", "48", "60"] },
  { c: 5, q: "What is the highest possible hand in standard poker?", a: ["A royal flush", "Four of a kind", "A full house", "A straight flush to the queen"] },
  { c: 5, q: "The America's Cup is a trophy in which sport?", a: ["Sailing", "Golf", "Powerboat racing", "Rowing"] },
  { c: 5, q: "Rugby is generally said to have originated in which country?", a: ["England", "New Zealand", "Wales", "Ireland"] },
  { c: 5, q: "How many minutes are in a standard professional soccer match?", a: ["90", "80", "100", "60"] },
  { c: 5, q: "The Monaco Grand Prix is part of which racing series?", a: ["Formula 1", "NASCAR", "IndyCar", "MotoGP"] },
  { c: 5, q: "What is the highest score possible with three darts?", a: ["180", "150", "201", "170"] },
  { c: 5, q: "Which soccer player wears a different coloured jersey from teammates?", a: ["The goalkeeper", "The captain", "The striker", "The sweeper"] },
  { c: 5, q: "The Super Bowl is the championship game of which sport?", a: ["American football", "Baseball", "Basketball", "Ice hockey"] },
  { c: 5, q: "What is a perfect score in ten-pin bowling?", a: ["300", "270", "200", "350"] },
  { c: 5, q: "Which Olympic sport combines cross-country skiing and rifle shooting?", a: ["Biathlon", "Nordic combined", "Pentathlon", "Skiathlon"] },
  { c: 5, q: "How many players per team take the field in rugby union?", a: ["15", "13", "11", "17"] },
  { c: 5, q: "In which sport would you use a foil, épée or sabre?", a: ["Fencing", "Archery", "Javelin", "Shooting"] },
];

// --------------------------------------------------------------------------
// HARD - pub-quiz-final-round territory. Distractors are deliberately
// plausible, so guessing is a genuine gamble.
// --------------------------------------------------------------------------
const HARD = [
  // ---------------------------------------------------------------- Geography
  { c: 0, q: "Which country has the longest coastline in the world?", a: ["Canada", "Russia", "Indonesia", "Australia"] },
  { c: 0, q: "Which African country was known as Upper Volta until 1984?", a: ["Burkina Faso", "Benin", "Mali", "Niger"] },
  { c: 0, q: "Lake Titicaca straddles the border of Peru and which country?", a: ["Bolivia", "Chile", "Ecuador", "Brazil"] },
  { c: 0, q: "Which sea has no land coastline, being bounded entirely by ocean currents?", a: ["The Sargasso Sea", "The Coral Sea", "The Weddell Sea", "The Andaman Sea"] },
  { c: 0, q: "What is the deepest known point of the ocean called?", a: ["The Challenger Deep", "The Sirena Deep", "The Horizon Deep", "The Meteor Deep"] },
  { c: 0, q: "Mount Erebus, one of the world's southernmost active volcanoes, is on which continent?", a: ["Antarctica", "South America", "Asia", "Africa"] },
  { c: 0, q: "Which river forms much of the border between Texas and Mexico?", a: ["The Rio Grande", "The Colorado", "The Pecos", "The Brazos"] },
  { c: 0, q: "Which strait connects the Aegean Sea to the Sea of Marmara?", a: ["The Dardanelles", "The Bosphorus", "The Strait of Otranto", "The Kerch Strait"] },
  { c: 0, q: "Kaliningrad is an exclave belonging to which country?", a: ["Russia", "Lithuania", "Poland", "Belarus"] },
  { c: 0, q: "What is the highest uninterrupted waterfall in the world?", a: ["Angel Falls", "Victoria Falls", "Niagara Falls", "Iguazu Falls"] },
  { c: 0, q: "Which is the largest inland body of water on Earth?", a: ["The Caspian Sea", "Lake Superior", "The Black Sea", "Lake Baikal"] },
  { c: 0, q: "Ceuta and Melilla are North African enclaves belonging to which country?", a: ["Spain", "France", "Portugal", "Italy"] },
  { c: 0, q: "What is the highest mountain outside of Asia?", a: ["Aconcagua", "Denali", "Kilimanjaro", "Mount Elbrus"] },
  { c: 0, q: "What is the capital of Mongolia?", a: ["Ulaanbaatar", "Astana", "Bishkek", "Tashkent"] },
  { c: 0, q: "Lake Tana, the source of the Blue Nile, is in which country?", a: ["Ethiopia", "Sudan", "Uganda", "Kenya"] },
  { c: 0, q: "The Kuril Islands are disputed between Russia and which country?", a: ["Japan", "China", "South Korea", "The United States"] },
  { c: 0, q: "What is the smallest US state by area?", a: ["Rhode Island", "Delaware", "Connecticut", "New Hampshire"] },
  { c: 0, q: "Victoria Falls lies on the border of Zambia and which country?", a: ["Zimbabwe", "Botswana", "Mozambique", "Namibia"] },
  { c: 0, q: "Which is the largest island in the Mediterranean Sea?", a: ["Sicily", "Sardinia", "Cyprus", "Crete"] },
  { c: 0, q: "Besides Liechtenstein, which is the world's only other doubly landlocked country?", a: ["Uzbekistan", "Mongolia", "Nepal", "Bolivia"] },
  { c: 0, q: "What is the longest mountain range above sea level?", a: ["The Andes", "The Himalayas", "The Rockies", "The Great Dividing Range"] },
  { c: 0, q: "Which US state has the longest coastline?", a: ["Alaska", "Florida", "California", "Maine"] },
  { c: 0, q: "Mount Kosciuszko is the highest peak of which country?", a: ["Australia", "New Zealand", "Papua New Guinea", "Fiji"] },
  { c: 0, q: "Which capital city sits on the Vltava river?", a: ["Prague", "Vienna", "Budapest", "Bratislava"] },
  { c: 0, q: "Which country was formerly known as Siam?", a: ["Thailand", "Cambodia", "Myanmar", "Laos"] },
  { c: 0, q: "The Darién Gap breaks the Pan-American Highway between Panama and which country?", a: ["Colombia", "Costa Rica", "Venezuela", "Ecuador"] },
  { c: 0, q: "Which is the second largest country in South America by area?", a: ["Argentina", "Peru", "Colombia", "Bolivia"] },
  { c: 0, q: "Lake Maracaibo is in which country?", a: ["Venezuela", "Colombia", "Brazil", "Guyana"] },
  { c: 0, q: "Which sea lies between Australia and New Zealand?", a: ["The Tasman Sea", "The Coral Sea", "The Timor Sea", "The Arafura Sea"] },
  { c: 0, q: "Which country has three capital cities?", a: ["South Africa", "Bolivia", "Malaysia", "Sri Lanka"] },
  { c: 0, q: "Which is the longest river in Europe?", a: ["The Volga", "The Danube", "The Rhine", "The Dnieper"] },
  { c: 0, q: "Which inland sea between Kazakhstan and Uzbekistan has largely dried up?", a: ["The Aral Sea", "The Caspian Sea", "Lake Balkhash", "The Dead Sea"] },
  { c: 0, q: "What is the capital of Bhutan?", a: ["Thimphu", "Kathmandu", "Paro", "Punakha"] },
  { c: 0, q: "Which strait separates India from Sri Lanka?", a: ["The Palk Strait", "The Malacca Strait", "The Sunda Strait", "The Gulf of Mannar"] },
  { c: 0, q: "Which country has the world's largest Muslim population?", a: ["Indonesia", "Pakistan", "India", "Saudi Arabia"] },
  { c: 0, q: "Mount Fuji is on which Japanese island?", a: ["Honshu", "Hokkaido", "Kyushu", "Shikoku"] },
  { c: 0, q: "The Danakil Depression, one of the hottest places on Earth, is mainly in which country?", a: ["Ethiopia", "Sudan", "Somalia", "Chad"] },
  { c: 0, q: "Which is the largest lake in Africa by surface area?", a: ["Lake Victoria", "Lake Tanganyika", "Lake Malawi", "Lake Chad"] },
  { c: 0, q: "Which is the largest country lying entirely within Europe?", a: ["Ukraine", "France", "Spain", "Poland"] },
  { c: 0, q: "Which line of latitude passes through central Australia?", a: ["The Tropic of Capricorn", "The Tropic of Cancer", "The Equator", "The Antarctic Circle"] },

  // ----------------------------------------------------------- Entertainment
  { c: 1, q: "Who directed and starred in Citizen Kane?", a: ["Orson Welles", "John Huston", "Frank Capra", "Howard Hawks"] },
  { c: 1, q: "Which film won the very first Academy Award for Best Picture?", a: ["Wings", "Sunrise", "The Broadway Melody", "All Quiet on the Western Front"] },
  { c: 1, q: "Who composed the score for The Good, the Bad and the Ugly?", a: ["Ennio Morricone", "Nino Rota", "Elmer Bernstein", "Jerry Goldsmith"] },
  { c: 1, q: "Which was the first studio album released by The Beatles?", a: ["Please Please Me", "With the Beatles", "A Hard Day's Night", "Rubber Soul"] },
  { c: 1, q: "Who directed Seven Samurai?", a: ["Akira Kurosawa", "Yasujiro Ozu", "Kenji Mizoguchi", "Hayao Miyazaki"] },
  { c: 1, q: "Which actor has won three Best Actor Academy Awards?", a: ["Daniel Day-Lewis", "Jack Nicholson", "Marlon Brando", "Anthony Hopkins"] },
  { c: 1, q: "Who played the young Vito Corleone in The Godfather Part II?", a: ["Robert De Niro", "Al Pacino", "James Caan", "John Cazale"] },
  { c: 1, q: "Travis Bickle is the central character of which film?", a: ["Taxi Driver", "Raging Bull", "Mean Streets", "The King of Comedy"] },
  { c: 1, q: "Who was the lead singer of Joy Division?", a: ["Ian Curtis", "Mark E. Smith", "Bernard Sumner", "Robert Smith"] },
  { c: 1, q: "Which Swedish director made The Seventh Seal?", a: ["Ingmar Bergman", "Lasse Hallström", "Roy Andersson", "Bo Widerberg"] },
  { c: 1, q: "Which Pink Floyd album famously spent over 900 weeks on the Billboard 200?", a: ["The Dark Side of the Moon", "The Wall", "Wish You Were Here", "Animals"] },
  { c: 1, q: "Who composed the music for West Side Story?", a: ["Leonard Bernstein", "Stephen Sondheim", "Richard Rodgers", "Andrew Lloyd Webber"] },
  { c: 1, q: "Which 1927 film is generally regarded as the first feature-length talkie?", a: ["The Jazz Singer", "The Lights of New York", "Don Juan", "The Broadway Melody"] },
  { c: 1, q: "Who directed Apocalypse Now?", a: ["Francis Ford Coppola", "Michael Cimino", "Oliver Stone", "Stanley Kubrick"] },
  { c: 1, q: "Which band released the album OK Computer?", a: ["Radiohead", "Blur", "Oasis", "Pulp"] },
  { c: 1, q: "What is the name of the blade runner played by Harrison Ford?", a: ["Rick Deckard", "Roy Batty", "Gaff", "Eldon Tyrell"] },
  { c: 1, q: "Who created the television series The Wire?", a: ["David Simon", "David Chase", "Vince Gilligan", "Aaron Sorkin"] },
  { c: 1, q: "Who directed 2001: A Space Odyssey?", a: ["Stanley Kubrick", "Ridley Scott", "Steven Spielberg", "Andrei Tarkovsky"] },
  { c: 1, q: "Which jazz musician recorded the album Kind of Blue?", a: ["Miles Davis", "John Coltrane", "Charlie Parker", "Dave Brubeck"] },
  { c: 1, q: "Who won a posthumous Oscar for playing the Joker in The Dark Knight?", a: ["Heath Ledger", "Jack Nicholson", "Joaquin Phoenix", "Cesar Romero"] },
  { c: 1, q: "Who directed Do the Right Thing?", a: ["Spike Lee", "John Singleton", "Charles Burnett", "Barry Jenkins"] },
  { c: 1, q: "The spaceship Nostromo appears in which film?", a: ["Alien", "Event Horizon", "Silent Running", "Solaris"] },
  { c: 1, q: "Who was the first Black woman to win the Academy Award for Best Actress?", a: ["Halle Berry", "Whoopi Goldberg", "Viola Davis", "Hattie McDaniel"] },
  { c: 1, q: "Which band released the album London Calling?", a: ["The Clash", "The Jam", "Sex Pistols", "The Damned"] },
  { c: 1, q: "Who directed Amélie?", a: ["Jean-Pierre Jeunet", "Luc Besson", "François Truffaut", "Michel Gondry"] },
  { c: 1, q: "Which Italian director made 8½?", a: ["Federico Fellini", "Michelangelo Antonioni", "Vittorio De Sica", "Luchino Visconti"] },
  { c: 1, q: "Who provided the voice of Darth Vader in the original Star Wars trilogy?", a: ["James Earl Jones", "David Prowse", "Peter Cushing", "Alec Guinness"] },
  { c: 1, q: "Which musical won the 2016 Pulitzer Prize for Drama?", a: ["Hamilton", "Rent", "Next to Normal", "A Strange Loop"] },
  { c: 1, q: "Who wrote and directed Get Out?", a: ["Jordan Peele", "Ryan Coogler", "Barry Jenkins", "Ava DuVernay"] },
  { c: 1, q: "Who directed Vertigo?", a: ["Alfred Hitchcock", "Billy Wilder", "Otto Preminger", "Fritz Lang"] },
  { c: 1, q: "Which singer was known as the Godfather of Soul?", a: ["James Brown", "Otis Redding", "Marvin Gaye", "Sam Cooke"] },
  { c: 1, q: "The Best Picture winner Parasite came from which country?", a: ["South Korea", "Japan", "China", "Taiwan"] },
  { c: 1, q: "Who directed Pan's Labyrinth?", a: ["Guillermo del Toro", "Alejandro González Iñárritu", "Alfonso Cuarón", "Pedro Almodóvar"] },
  { c: 1, q: "Which Beatles album cover shows the band on a zebra crossing?", a: ["Abbey Road", "Let It Be", "Revolver", "Help!"] },
  { c: 1, q: "Who played Michael Corleone in The Godfather?", a: ["Al Pacino", "Robert De Niro", "James Caan", "Robert Duvall"] },
  { c: 1, q: "The advertising agency Sterling Cooper features in which series?", a: ["Mad Men", "The Sopranos", "Suits", "Boardwalk Empire"] },
  { c: 1, q: "Who composed Rhapsody in Blue?", a: ["George Gershwin", "Aaron Copland", "Cole Porter", "Duke Ellington"] },
  { c: 1, q: "Kathryn Bigelow won Best Director for which film?", a: ["The Hurt Locker", "Zero Dark Thirty", "Point Break", "Detroit"] },
  { c: 1, q: "Which director's films include Stalker and Solaris?", a: ["Andrei Tarkovsky", "Sergei Eisenstein", "Krzysztof Kieślowski", "Béla Tarr"] },
  { c: 1, q: "Which singer released the album Blue in 1971?", a: ["Joni Mitchell", "Carole King", "Carly Simon", "Janis Joplin"] },

  // ----------------------------------------------------------------- History
  { c: 2, q: "Which treaty formally ended the First World War with Germany?", a: ["The Treaty of Versailles", "The Treaty of Trianon", "The Treaty of Brest-Litovsk", "The Treaty of Sèvres"] },
  { c: 2, q: "In which year did the Ottomans capture Constantinople?", a: ["1453", "1492", "1389", "1517"] },
  { c: 2, q: "Who was crowned Emperor of the Romans in the year 800?", a: ["Charlemagne", "Otto I", "Justinian", "Clovis"] },
  { c: 2, q: "Which battle in 1066 led to Norman rule of England?", a: ["The Battle of Hastings", "The Battle of Stamford Bridge", "The Battle of Bosworth", "The Battle of Agincourt"] },
  { c: 2, q: "Which Roman general was defeated and killed at Carrhae in 53 BC?", a: ["Crassus", "Pompey", "Mark Antony", "Sulla"] },
  { c: 2, q: "Suleiman the Magnificent ruled which empire?", a: ["The Ottoman Empire", "The Persian Empire", "The Mughal Empire", "The Byzantine Empire"] },
  { c: 2, q: "In which year did the Spanish Armada sail against England?", a: ["1588", "1571", "1600", "1492"] },
  { c: 2, q: "Who led the Haitian Revolution against French rule?", a: ["Toussaint Louverture", "Simón Bolívar", "José Martí", "Bernardo O'Higgins"] },
  { c: 2, q: "Which Chinese dynasty built the best-known sections of the Great Wall?", a: ["The Ming", "The Han", "The Qin", "The Tang"] },
  { c: 2, q: "In which year was the Soviet Union formally dissolved?", a: ["1991", "1989", "1993", "1990"] },
  { c: 2, q: "Which US president completed the Louisiana Purchase?", a: ["Thomas Jefferson", "James Madison", "John Adams", "James Monroe"] },
  { c: 2, q: "Who was the last Tsar of Russia?", a: ["Nicholas II", "Alexander III", "Nicholas I", "Peter III"] },
  { c: 2, q: "Which conflict was ended by the Treaty of Ghent?", a: ["The War of 1812", "The American Revolution", "The Mexican-American War", "The Seven Years' War"] },
  { c: 2, q: "Who was the first woman to fly solo across the Atlantic?", a: ["Amelia Earhart", "Bessie Coleman", "Amy Johnson", "Harriet Quimby"] },
  { c: 2, q: "Which Roman city was buried by Vesuvius in AD 79?", a: ["Pompeii", "Ostia", "Ravenna", "Capua"] },
  { c: 2, q: "Emperor Haile Selassie ruled which country?", a: ["Ethiopia", "Eritrea", "Sudan", "Somalia"] },
  { c: 2, q: "Who was the chancellor who engineered German unification in 1871?", a: ["Otto von Bismarck", "Wilhelm I", "Friedrich Ebert", "Paul von Hindenburg"] },
  { c: 2, q: "What was the code name for the Allied invasion of Normandy?", a: ["Operation Overlord", "Operation Market Garden", "Operation Torch", "Operation Husky"] },
  { c: 2, q: "Which Chinese leader launched the Great Leap Forward?", a: ["Mao Zedong", "Deng Xiaoping", "Zhou Enlai", "Chiang Kai-shek"] },
  { c: 2, q: "Whose assassination in Sarajevo helped trigger the First World War?", a: ["Archduke Franz Ferdinand", "Kaiser Wilhelm II", "Tsar Nicholas II", "King Peter I"] },
  { c: 2, q: "Which civilisation built Angkor Wat?", a: ["The Khmer Empire", "The Srivijaya Empire", "The Champa Kingdom", "The Majapahit Empire"] },
  { c: 2, q: "In which year did India gain independence from Britain?", a: ["1947", "1945", "1950", "1930"] },
  { c: 2, q: "What was the capital of the Byzantine Empire?", a: ["Constantinople", "Antioch", "Thessalonica", "Nicaea"] },
  { c: 2, q: "Which pharaoh is believed to have built the Great Pyramid of Giza?", a: ["Khufu", "Khafre", "Menkaure", "Ramesses II"] },
  { c: 2, q: "Who co-wrote The Communist Manifesto with Friedrich Engels?", a: ["Karl Marx", "Vladimir Lenin", "Leon Trotsky", "Pierre-Joseph Proudhon"] },
  { c: 2, q: "Which battle is regarded as the turning point of the Eastern Front in WWII?", a: ["Stalingrad", "Kursk", "Moscow", "Leningrad"] },
  { c: 2, q: "Which English king was forced to seal the Magna Carta?", a: ["King John", "Henry III", "Richard I", "Edward I"] },
  { c: 2, q: "In which year did the Berlin Airlift begin?", a: ["1948", "1945", "1953", "1961"] },
  { c: 2, q: "The Soviet Union invaded which country in 1979?", a: ["Afghanistan", "Iran", "Hungary", "Czechoslovakia"] },
  { c: 2, q: "Who was the first Secretary-General of the United Nations?", a: ["Trygve Lie", "Dag Hammarskjöld", "U Thant", "Kurt Waldheim"] },
  { c: 2, q: "Who led the first expedition to reach the South Pole?", a: ["Roald Amundsen", "Robert Falcon Scott", "Ernest Shackleton", "Richard Byrd"] },
  { c: 2, q: "Which empire did Hernán Cortés bring down?", a: ["The Aztec Empire", "The Inca Empire", "The Maya city-states", "The Zapotec kingdom"] },
  { c: 2, q: "In which year did the Wall Street Crash begin?", a: ["1929", "1931", "1927", "1933"] },
  { c: 2, q: "Who founded the Mongol Empire?", a: ["Genghis Khan", "Kublai Khan", "Tamerlane", "Ögedei Khan"] },
  { c: 2, q: "The Korean War was fought between which years?", a: ["1950 to 1953", "1948 to 1951", "1953 to 1956", "1945 to 1949"] },
  { c: 2, q: "Where did Abraham Lincoln deliver his most famous address in 1863?", a: ["Gettysburg", "Antietam", "Richmond", "Appomattox"] },
  { c: 2, q: "Which queen was the longest-reigning British monarch?", a: ["Elizabeth II", "Victoria", "Elizabeth I", "Anne"] },
  { c: 2, q: "Which 1215 rebellion-era document limited the English crown's power?", a: ["Magna Carta", "The Bill of Rights", "The Petition of Right", "The Act of Settlement"] },
  { c: 2, q: "Which ancient wonder stood on the island of Pharos?", a: ["The Lighthouse of Alexandria", "The Colossus of Rhodes", "The Temple of Artemis", "The Mausoleum at Halicarnassus"] },
  { c: 2, q: "Which US general accepted Japan's formal surrender in 1945?", a: ["Douglas MacArthur", "Dwight Eisenhower", "George Patton", "Omar Bradley"] },

  // ------------------------------------------------------- Arts & Literature
  { c: 3, q: "Who wrote Ulysses?", a: ["James Joyce", "Samuel Beckett", "Virginia Woolf", "Ezra Pound"] },
  { c: 3, q: "Which artist painted Guernica?", a: ["Pablo Picasso", "Joan Miró", "Salvador Dalí", "Francisco Goya"] },
  { c: 3, q: "Who wrote In Search of Lost Time?", a: ["Marcel Proust", "André Gide", "Albert Camus", "Gustave Flaubert"] },
  { c: 3, q: "Who painted The Garden of Earthly Delights?", a: ["Hieronymus Bosch", "Pieter Bruegel the Elder", "Jan van Eyck", "Matthias Grünewald"] },
  { c: 3, q: "Who wrote the poem The Waste Land?", a: ["T. S. Eliot", "Ezra Pound", "W. H. Auden", "William Carlos Williams"] },
  { c: 3, q: "Which sculptor created The Thinker?", a: ["Auguste Rodin", "Camille Claudel", "Antonio Canova", "Constantin Brâncuși"] },
  { c: 3, q: "Who wrote Madame Bovary?", a: ["Gustave Flaubert", "Émile Zola", "Honoré de Balzac", "Stendhal"] },
  { c: 3, q: "Which painting gave the Impressionist movement its name?", a: ["Impression, Sunrise", "Water Lilies", "Luncheon of the Boating Party", "A Bar at the Folies-Bergère"] },
  { c: 3, q: "Who wrote The Master and Margarita?", a: ["Mikhail Bulgakov", "Boris Pasternak", "Andrei Bely", "Ivan Bunin"] },
  { c: 3, q: "Who painted Las Meninas?", a: ["Diego Velázquez", "Francisco Goya", "El Greco", "Bartolomé Murillo"] },
  { c: 3, q: "Who wrote the tragic play Faust?", a: ["Johann Wolfgang von Goethe", "Friedrich Schiller", "Thomas Mann", "Heinrich Heine"] },
  { c: 3, q: "Which architect designed the Sagrada Família?", a: ["Antoni Gaudí", "Le Corbusier", "Santiago Calatrava", "Josep Lluís Sert"] },
  { c: 3, q: "Who wrote the 1952 novel Invisible Man?", a: ["Ralph Ellison", "Richard Wright", "James Baldwin", "Langston Hughes"] },
  { c: 3, q: "Who composed The Rite of Spring?", a: ["Igor Stravinsky", "Sergei Prokofiev", "Claude Debussy", "Dmitri Shostakovich"] },
  { c: 3, q: "Who painted Girl with a Pearl Earring?", a: ["Johannes Vermeer", "Rembrandt", "Frans Hals", "Pieter de Hooch"] },
  { c: 3, q: "Who wrote Wuthering Heights?", a: ["Emily Brontë", "Charlotte Brontë", "Anne Brontë", "Elizabeth Gaskell"] },
  { c: 3, q: "Who wrote The Tale of Genji, often called the first novel?", a: ["Murasaki Shikibu", "Sei Shōnagon", "Matsuo Bashō", "Yukio Mishima"] },
  { c: 3, q: "Who wrote Heart of Darkness?", a: ["Joseph Conrad", "Rudyard Kipling", "E. M. Forster", "Graham Greene"] },
  { c: 3, q: "Which Mexican painter is known for intense self-portraits with thorns and monkeys?", a: ["Frida Kahlo", "Remedios Varo", "María Izquierdo", "Leonora Carrington"] },
  { c: 3, q: "Who composed Boléro?", a: ["Maurice Ravel", "Claude Debussy", "Erik Satie", "Camille Saint-Saëns"] },
  { c: 3, q: "Who wrote the sonnet Ozymandias?", a: ["Percy Bysshe Shelley", "Lord Byron", "John Keats", "William Wordsworth"] },
  { c: 3, q: "Who wrote Lolita?", a: ["Vladimir Nabokov", "Philip Roth", "John Updike", "Saul Bellow"] },
  { c: 3, q: "Which artist submitted a urinal titled Fountain as a work of art?", a: ["Marcel Duchamp", "Man Ray", "Kurt Schwitters", "Francis Picabia"] },
  { c: 3, q: "Who wrote The Sound and the Fury?", a: ["William Faulkner", "John Steinbeck", "Sherwood Anderson", "Thomas Wolfe"] },
  { c: 3, q: "Who composed the Brandenburg Concertos?", a: ["Johann Sebastian Bach", "George Frideric Handel", "Antonio Vivaldi", "Georg Philipp Telemann"] },
  { c: 3, q: "Who wrote Middlemarch?", a: ["George Eliot", "Elizabeth Gaskell", "Thomas Hardy", "Anthony Trollope"] },
  { c: 3, q: "Which Austrian painter created the gold-leaf work The Kiss?", a: ["Gustav Klimt", "Egon Schiele", "Oskar Kokoschka", "Alphonse Mucha"] },
  { c: 3, q: "Who wrote Anna Karenina?", a: ["Leo Tolstoy", "Fyodor Dostoevsky", "Ivan Turgenev", "Nikolai Gogol"] },
  { c: 3, q: "Who wrote the play Waiting for Godot?", a: ["Samuel Beckett", "Harold Pinter", "Eugène Ionesco", "Tom Stoppard"] },
  { c: 3, q: "Who painted American Gothic?", a: ["Grant Wood", "Edward Hopper", "Thomas Hart Benton", "Andrew Wyeth"] },
  { c: 3, q: "Yossarian is the central character of which novel?", a: ["Catch-22", "Slaughterhouse-Five", "The Naked and the Dead", "From Here to Eternity"] },
  { c: 3, q: "Who wrote Doctor Zhivago?", a: ["Boris Pasternak", "Aleksandr Solzhenitsyn", "Mikhail Sholokhov", "Ivan Bunin"] },
  { c: 3, q: "Which composer died leaving his Requiem unfinished?", a: ["Wolfgang Amadeus Mozart", "Franz Schubert", "Gustav Mahler", "Anton Bruckner"] },
  { c: 3, q: "Who wrote Their Eyes Were Watching God?", a: ["Zora Neale Hurston", "Toni Morrison", "Alice Walker", "Nella Larsen"] },
  { c: 3, q: "Who painted the Vatican fresco The School of Athens?", a: ["Raphael", "Michelangelo", "Leonardo da Vinci", "Botticelli"] },
  { c: 3, q: "Who wrote Mrs Dalloway?", a: ["Virginia Woolf", "Katherine Mansfield", "E. M. Forster", "Dorothy Richardson"] },
  { c: 3, q: "Who wrote the novella The Metamorphosis?", a: ["Franz Kafka", "Thomas Mann", "Hermann Hesse", "Robert Musil"] },
  { c: 3, q: "Which architect founded the Bauhaus school?", a: ["Walter Gropius", "Mies van der Rohe", "Le Corbusier", "Marcel Breuer"] },
  { c: 3, q: "Who wrote the 1977 novel Song of Solomon?", a: ["Toni Morrison", "Maya Angelou", "Gloria Naylor", "Paule Marshall"] },
  { c: 3, q: "Who wrote the Duino Elegies?", a: ["Rainer Maria Rilke", "Paul Celan", "Stefan George", "Hugo von Hofmannsthal"] },

  // ------------------------------------------------------- Science & Nature
  { c: 4, q: "What is the most abundant element in the Earth's crust?", a: ["Oxygen", "Silicon", "Iron", "Aluminium"] },
  { c: 4, q: "Which particle carries the electromagnetic force?", a: ["The photon", "The gluon", "The W boson", "The graviton"] },
  { c: 4, q: "Roughly what is the half-life of carbon-14?", a: ["About 5,700 years", "About 1,600 years", "About 24,000 years", "About 700 million years"] },
  { c: 4, q: "Who formulated the uncertainty principle?", a: ["Werner Heisenberg", "Niels Bohr", "Erwin Schrödinger", "Max Born"] },
  { c: 4, q: "What is the chemical symbol for tungsten?", a: ["W", "Tu", "Tn", "Tg"] },
  { c: 4, q: "Which blood type is known as the universal donor?", a: ["O negative", "AB positive", "A negative", "O positive"] },
  { c: 4, q: "Which planet has the shortest day?", a: ["Jupiter", "Mercury", "Mars", "Venus"] },
  { c: 4, q: "What is the SI unit of electrical resistance?", a: ["The ohm", "The volt", "The ampere", "The farad"] },
  { c: 4, q: "Which layer of the atmosphere contains the ozone layer?", a: ["The stratosphere", "The troposphere", "The mesosphere", "The thermosphere"] },
  { c: 4, q: "Whose X-ray diffraction images were crucial to determining DNA's structure?", a: ["Rosalind Franklin", "Barbara McClintock", "Dorothy Hodgkin", "Lise Meitner"] },
  { c: 4, q: "Which mineral has a Mohs hardness of 1?", a: ["Talc", "Gypsum", "Calcite", "Quartz"] },
  { c: 4, q: "Which element is named after the Sun?", a: ["Helium", "Selenium", "Sodium", "Neon"] },
  { c: 4, q: "What is it called when a solid turns directly into a gas?", a: ["Sublimation", "Evaporation", "Condensation", "Deposition"] },
  { c: 4, q: "Which vitamin deficiency causes scurvy?", a: ["Vitamin C", "Vitamin D", "Vitamin B1", "Vitamin K"] },
  { c: 4, q: "Roughly how fast does sound travel in air at sea level?", a: ["About 340 metres per second", "About 150 metres per second", "About 1,200 metres per second", "About 30 metres per second"] },
  { c: 4, q: "Who devised the periodic table arranged by atomic mass?", a: ["Dmitri Mendeleev", "Antoine Lavoisier", "John Dalton", "Henry Moseley"] },
  { c: 4, q: "Which is the only mammal capable of true sustained flight?", a: ["The bat", "The flying squirrel", "The colugo", "The sugar glider"] },
  { c: 4, q: "What word describes animals that are most active at dawn and dusk?", a: ["Crepuscular", "Nocturnal", "Diurnal", "Matutinal"] },
  { c: 4, q: "Which planet rotates on its side, with an axial tilt of about 98 degrees?", a: ["Uranus", "Neptune", "Saturn", "Venus"] },
  { c: 4, q: "What is Avogadro's number, approximately?", a: ["6.022 x 10^23", "3.14 x 10^8", "1.602 x 10^-19", "9.109 x 10^31"] },
  { c: 4, q: "Which acid gives vinegar its sharp taste?", a: ["Acetic acid", "Citric acid", "Lactic acid", "Formic acid"] },
  { c: 4, q: "Which part of the brain governs balance and coordination?", a: ["The cerebellum", "The cerebrum", "The medulla", "The hypothalamus"] },
  { c: 4, q: "Which subatomic particle carries no electric charge?", a: ["The neutron", "The proton", "The electron", "The positron"] },
  { c: 4, q: "What is the largest moon in the solar system?", a: ["Ganymede", "Titan", "Callisto", "Europa"] },
  { c: 4, q: "Which nuclear process splits heavy nuclei to release energy?", a: ["Fission", "Fusion", "Decay", "Ionisation"] },
  { c: 4, q: "Who developed the first successful smallpox vaccine?", a: ["Edward Jenner", "Louis Pasteur", "Robert Koch", "Jonas Salk"] },
  { c: 4, q: "What is the collective noun for a group of crows?", a: ["A murder", "A parliament", "A murmuration", "A gaggle"] },
  { c: 4, q: "Which land mammal has the longest gestation period?", a: ["The elephant", "The giraffe", "The rhinoceros", "The camel"] },
  { c: 4, q: "Which gas dominates the atmosphere of Venus?", a: ["Carbon dioxide", "Nitrogen", "Methane", "Sulphur dioxide"] },
  { c: 4, q: "Which vessel carries blood from the heart to the lungs?", a: ["The pulmonary artery", "The pulmonary vein", "The aorta", "The vena cava"] },
  { c: 4, q: "What is the SI unit of frequency?", a: ["The hertz", "The becquerel", "The tesla", "The siemens"] },
  { c: 4, q: "Which theory explains the movement of the Earth's crustal plates?", a: ["Plate tectonics", "Uniformitarianism", "Isostasy", "Catastrophism"] },
  { c: 4, q: "What is the chemical formula for common table salt?", a: ["NaCl", "KCl", "NaHCO3", "CaCO3"] },
  { c: 4, q: "Which is the lightest metal on the periodic table?", a: ["Lithium", "Aluminium", "Magnesium", "Beryllium"] },
  { c: 4, q: "What is the bending of light as it passes between two media called?", a: ["Refraction", "Reflection", "Diffraction", "Dispersion"] },
  { c: 4, q: "Which came first in geological time?", a: ["The Triassic", "The Jurassic", "The Cretaceous", "The Palaeogene"] },
  { c: 4, q: "What is the term for the study of fungi?", a: ["Mycology", "Botany", "Entomology", "Herpetology"] },
  { c: 4, q: "Which scientist first measured the speed of light with reasonable accuracy in the 1670s?", a: ["Ole Rømer", "Isaac Newton", "Christiaan Huygens", "Galileo Galilei"] },
  { c: 4, q: "How many pairs of chromosomes does a typical human cell contain?", a: ["23", "46", "22", "48"] },
  { c: 4, q: "Which blood component is responsible for clotting?", a: ["Platelets", "Red blood cells", "Plasma", "Lymphocytes"] },

  // -------------------------------------------------------- Sports & Leisure
  { c: 5, q: "Which country won the first FIFA World Cup in 1930?", a: ["Uruguay", "Brazil", "Argentina", "Italy"] },
  { c: 5, q: "How many players from each team are in the water in water polo?", a: ["Seven", "Six", "Five", "Eight"] },
  { c: 5, q: "Who beat Muhammad Ali in the 1971 'Fight of the Century'?", a: ["Joe Frazier", "George Foreman", "Sonny Liston", "Ken Norton"] },
  { c: 5, q: "In cricket, what is a batter's score of zero called?", a: ["A duck", "A blob", "A love", "A goose egg"] },
  { c: 5, q: "Which golfer has won the most men's major championships?", a: ["Jack Nicklaus", "Tiger Woods", "Walter Hagen", "Ben Hogan"] },
  { c: 5, q: "How many points is a converted try worth in rugby union?", a: ["Seven", "Six", "Five", "Eight"] },
  { c: 5, q: "Which country has won the most Olympic gold medals in total?", a: ["The United States", "The Soviet Union", "China", "Germany"] },
  { c: 5, q: "What is the diameter of a basketball hoop, in inches?", a: ["18", "16", "20", "24"] },
  { c: 5, q: "Which tennis Grand Slam is played on clay?", a: ["The French Open", "Wimbledon", "The US Open", "The Australian Open"] },
  { c: 5, q: "How many players from each team are on the ice in hockey, including the goalie?", a: ["Six", "Five", "Seven", "Four"] },
  { c: 5, q: "Curling originated in which country?", a: ["Scotland", "Canada", "Sweden", "Norway"] },
  { c: 5, q: "What is the maximum number of clubs allowed in a golfer's bag?", a: ["14", "12", "16", "10"] },
  { c: 5, q: "Which horse race is billed as 'the most exciting two minutes in sports'?", a: ["The Kentucky Derby", "The Grand National", "The Melbourne Cup", "The Belmont Stakes"] },
  { c: 5, q: "In chess, what is it called when a player has no legal move but is not in check?", a: ["Stalemate", "Checkmate", "Zugzwang", "En passant"] },
  { c: 5, q: "Which country hosted the first modern Olympic Games in 1896?", a: ["Greece", "France", "Britain", "Italy"] },
  { c: 5, q: "How long is an Olympic swimming pool?", a: ["50 metres", "25 metres", "100 metres", "75 metres"] },
  { c: 5, q: "Which sport features fielding positions called 'silly point' and 'gully'?", a: ["Cricket", "Baseball", "Rounders", "Lacrosse"] },
  { c: 5, q: "How many players per team are on the field in Australian rules football?", a: ["18", "15", "13", "20"] },
  { c: 5, q: "Which tennis player completed the Golden Slam in 1988?", a: ["Steffi Graf", "Martina Navratilova", "Chris Evert", "Monica Seles"] },
  { c: 5, q: "In baseball, what is the distance between bases?", a: ["90 feet", "60 feet", "75 feet", "100 feet"] },
  { c: 5, q: "Which martial art's name translates as 'the way of the empty hand'?", a: ["Karate", "Judo", "Aikido", "Kung fu"] },
  { c: 5, q: "Which country won the 1995 Rugby World Cup?", a: ["South Africa", "New Zealand", "Australia", "England"] },
  { c: 5, q: "How long is a marathon in kilometres?", a: ["42.195", "40.000", "45.500", "38.600"] },
  { c: 5, q: "Which NBA player scored 100 points in a single game?", a: ["Wilt Chamberlain", "Michael Jordan", "Kobe Bryant", "Elgin Baylor"] },
  { c: 5, q: "How many hurdles does a runner clear in the 110 metres hurdles?", a: ["Ten", "Eight", "Twelve", "Fourteen"] },
  { c: 5, q: "In which sport does the main group of riders form a 'peloton'?", a: ["Cycling", "Marathon running", "Speed skating", "Rowing"] },
  { c: 5, q: "Which Olympic event combines fencing, swimming, riding, shooting and running?", a: ["The modern pentathlon", "The decathlon", "The heptathlon", "The triathlon"] },
  { c: 5, q: "Muay Thai originated in which country?", a: ["Thailand", "Vietnam", "Cambodia", "Myanmar"] },
  { c: 5, q: "In American football, how many points is a safety worth?", a: ["Two", "One", "Three", "Six"] },
  { c: 5, q: "Who has won the most Olympic medals of any athlete?", a: ["Michael Phelps", "Larisa Latynina", "Usain Bolt", "Carl Lewis"] },
  { c: 5, q: "Which format of cricket can last up to five days?", a: ["Test cricket", "One Day International", "Twenty20", "The Hundred"] },
  { c: 5, q: "What colour is the 8 ball in pool?", a: ["Black", "Red", "Blue", "Purple"] },
  { c: 5, q: "How many players from each team are on court in netball?", a: ["Seven", "Six", "Five", "Nine"] },
  { c: 5, q: "Which is the oldest of golf's four majors?", a: ["The Open Championship", "The Masters", "The US Open", "The PGA Championship"] },
  { c: 5, q: "Which football club plays its home games at the Camp Nou?", a: ["Barcelona", "Real Madrid", "Atlético Madrid", "Valencia"] },
  { c: 5, q: "How many minutes long is each quarter of an NBA game?", a: ["12", "10", "15", "8"] },
  { c: 5, q: "In poker, what is the nickname for a starting hand of two aces?", a: ["Pocket rockets", "Big slick", "Cowboys", "Ducks"] },
  { c: 5, q: "Which country invented the sport of badminton's forerunner, 'poona'?", a: ["India", "China", "England", "Japan"] },
  { c: 5, q: "How many points does a team need to win a standard volleyball set?", a: ["25", "21", "15", "30"] },
  { c: 5, q: "Which boxer was nicknamed 'Iron Mike'?", a: ["Mike Tyson", "Michael Spinks", "Riddick Bowe", "Evander Holyfield"] },
];

// The difficulty tag is applied here so entries above stay easy to read and edit.
module.exports = [
  ...EASY.map((q) => ({ ...q, d: 1 })),
  ...HARD.map((q) => ({ ...q, d: 2 })),
];

module.exports.EASY = EASY;
module.exports.HARD = HARD;
