'use strict';

/**
 * Question bank.
 *
 * Format: { c: <category id>, q: "<question>", a: ["correct", "wrong", "wrong", "wrong"] }
 * The first answer is always the correct one; the server shuffles before sending.
 *
 * Categories: 0 Geography | 1 Entertainment | 2 History
 *             3 Arts & Literature | 4 Science & Nature | 5 Sports & Leisure
 *
 * Add your own by appending entries here - no other changes needed.
 */

const QUESTIONS = [
  // ---------------------------------------------------------------- Geography
  { c: 0, q: "What is the capital of Australia?", a: ["Canberra", "Sydney", "Melbourne", "Perth"] },
  { c: 0, q: "Which river flows through Cairo?", a: ["The Nile", "The Congo", "The Niger", "The Zambezi"] },
  { c: 0, q: "Which is the largest country in the world by land area?", a: ["Russia", "Canada", "China", "The United States"] },
  { c: 0, q: "Mount Everest sits on the border of Nepal and which other country?", a: ["China", "India", "Bhutan", "Pakistan"] },
  { c: 0, q: "Which US state is nicknamed the Sunshine State?", a: ["Florida", "California", "Arizona", "Hawaii"] },
  { c: 0, q: "Which strait separates Spain from Morocco?", a: ["The Strait of Gibraltar", "The Bosphorus", "The Strait of Hormuz", "The Strait of Malacca"] },
  { c: 0, q: "What is the capital of Canada?", a: ["Ottawa", "Toronto", "Vancouver", "Montreal"] },
  { c: 0, q: "Which is the largest hot desert in the world?", a: ["The Sahara", "The Gobi", "The Kalahari", "The Arabian Desert"] },
  { c: 0, q: "Which is the longest river in South America?", a: ["The Amazon", "The Paraná", "The Orinoco", "The Magdalena"] },
  { c: 0, q: "The fjord-lined city of Bergen is in which country?", a: ["Norway", "Sweden", "Denmark", "Finland"] },
  { c: 0, q: "What is the smallest country in the world by area?", a: ["Vatican City", "Monaco", "Nauru", "San Marino"] },
  { c: 0, q: "Which country is entirely surrounded by South Africa?", a: ["Lesotho", "Eswatini", "Botswana", "Namibia"] },
  { c: 0, q: "Which is the deepest ocean?", a: ["The Pacific", "The Atlantic", "The Indian", "The Arctic"] },
  { c: 0, q: "Istanbul straddles which two continents?", a: ["Europe and Asia", "Asia and Africa", "Europe and Africa", "Europe and the Middle East"] },
  { c: 0, q: "What is the capital of New Zealand?", a: ["Wellington", "Auckland", "Christchurch", "Dunedin"] },
  { c: 0, q: "Which mountain range separates France from Spain?", a: ["The Pyrenees", "The Alps", "The Apennines", "The Carpathians"] },
  { c: 0, q: "Which country's flag features a red maple leaf?", a: ["Canada", "Lebanon", "Japan", "Switzerland"] },
  { c: 0, q: "Lake Baikal, the world's deepest lake, is in which country?", a: ["Russia", "Mongolia", "Kazakhstan", "China"] },
  { c: 0, q: "The Atacama Desert lies mainly in which country?", a: ["Chile", "Peru", "Argentina", "Bolivia"] },
  { c: 0, q: "What is the capital of Brazil?", a: ["Brasília", "Rio de Janeiro", "São Paulo", "Salvador"] },
  { c: 0, q: "Which US state is the largest by area?", a: ["Alaska", "Texas", "California", "Montana"] },
  { c: 0, q: "The Danube empties into which sea?", a: ["The Black Sea", "The Adriatic Sea", "The Baltic Sea", "The Caspian Sea"] },
  { c: 0, q: "Which is the largest island in the world?", a: ["Greenland", "New Guinea", "Borneo", "Madagascar"] },
  { c: 0, q: "Which country is known as the Land of the Rising Sun?", a: ["Japan", "China", "South Korea", "Thailand"] },
  { c: 0, q: "Which European capital sits at the mouth of the River Tagus?", a: ["Lisbon", "Madrid", "Seville", "Barcelona"] },
  { c: 0, q: "The Great Barrier Reef lies off the coast of which Australian state?", a: ["Queensland", "Western Australia", "New South Wales", "Victoria"] },
  { c: 0, q: "Which canal links the Mediterranean Sea to the Red Sea?", a: ["The Suez Canal", "The Panama Canal", "The Kiel Canal", "The Corinth Canal"] },
  { c: 0, q: "Which African country has the largest population?", a: ["Nigeria", "Ethiopia", "Egypt", "South Africa"] },
  { c: 0, q: "Machu Picchu is located in which country?", a: ["Peru", "Bolivia", "Ecuador", "Chile"] },
  { c: 0, q: "Which body of water has the lowest shoreline on Earth?", a: ["The Dead Sea", "The Caspian Sea", "The Great Salt Lake", "Lake Eyre"] },
  { c: 0, q: "Which of these national capitals lies furthest north?", a: ["Reykjavík", "Oslo", "Helsinki", "Stockholm"] },
  { c: 0, q: "The city of Timbuktu is in which country?", a: ["Mali", "Niger", "Chad", "Senegal"] },
  { c: 0, q: "Which two countries share the world's longest international border?", a: ["The US and Canada", "Russia and China", "Argentina and Chile", "Russia and Kazakhstan"] },
  { c: 0, q: "What is the official language of Brazil?", a: ["Portuguese", "Spanish", "French", "Brazilian"] },
  { c: 0, q: "What is the highest mountain in Africa?", a: ["Kilimanjaro", "Mount Kenya", "Mount Elgon", "Mount Toubkal"] },
  { c: 0, q: "The Yucatán Peninsula belongs mostly to which country?", a: ["Mexico", "Belize", "Guatemala", "Honduras"] },
  { c: 0, q: "In which city would you find the Brandenburg Gate?", a: ["Berlin", "Munich", "Vienna", "Hamburg"] },
  { c: 0, q: "Which strait separates Alaska from Russia?", a: ["The Bering Strait", "The Denmark Strait", "The Davis Strait", "The Cook Strait"] },
  { c: 0, q: "Which continent contains the Serengeti?", a: ["Africa", "Asia", "South America", "Australia"] },
  { c: 0, q: "Which country has the most inhabited islands, numbering over 17,000?", a: ["Indonesia", "The Philippines", "Japan", "Greece"] },

  // ----------------------------------------------------------- Entertainment
  { c: 1, q: "Who directed the 1975 film Jaws?", a: ["Steven Spielberg", "George Lucas", "Martin Scorsese", "Francis Ford Coppola"] },
  { c: 1, q: "Who played Jack in the 1997 film Titanic?", a: ["Leonardo DiCaprio", "Brad Pitt", "Matt Damon", "Johnny Depp"] },
  { c: 1, q: "\"Here's Johnny!\" is a famous line from which horror film?", a: ["The Shining", "Psycho", "Halloween", "The Exorcist"] },
  { c: 1, q: "Which band released \"Bohemian Rhapsody\"?", a: ["Queen", "The Rolling Stones", "Pink Floyd", "The Who"] },
  { c: 1, q: "Who played Neo in The Matrix?", a: ["Keanu Reeves", "Tom Cruise", "Will Smith", "Nicolas Cage"] },
  { c: 1, q: "Which Disney film features a lion cub named Simba?", a: ["The Lion King", "The Jungle Book", "Tarzan", "Brother Bear"] },
  { c: 1, q: "Which Michael Jackson album is the best-selling of all time?", a: ["Thriller", "Bad", "Off the Wall", "Dangerous"] },
  { c: 1, q: "Which TV series is set in the town of Hawkins, Indiana?", a: ["Stranger Things", "Twin Peaks", "Riverdale", "The X-Files"] },
  { c: 1, q: "In which sitcom do the characters hang out at Central Perk?", a: ["Friends", "Seinfeld", "How I Met Your Mother", "Cheers"] },
  { c: 1, q: "Which 1994 film won the Academy Award for Best Picture?", a: ["Forrest Gump", "Pulp Fiction", "The Shawshank Redemption", "Four Weddings and a Funeral"] },
  { c: 1, q: "Who is the lead singer of the band U2?", a: ["Bono", "Sting", "Chris Martin", "Michael Stipe"] },
  { c: 1, q: "What is the name of the wizarding school in the Harry Potter films?", a: ["Hogwarts", "Durmstrang", "Beauxbatons", "Ilvermorny"] },
  { c: 1, q: "Which studio produced the 1995 film Toy Story?", a: ["Pixar", "DreamWorks", "Studio Ghibli", "Blue Sky"] },
  { c: 1, q: "Who played Iron Man in the Marvel Cinematic Universe?", a: ["Robert Downey Jr.", "Chris Evans", "Mark Ruffalo", "Chris Hemsworth"] },
  { c: 1, q: "The song \"Defying Gravity\" comes from which musical?", a: ["Wicked", "Hamilton", "Rent", "Chicago"] },
  { c: 1, q: "Which musician wrote and performed \"Purple Rain\"?", a: ["Prince", "David Bowie", "Lenny Kravitz", "Stevie Wonder"] },
  { c: 1, q: "The Iron Throne appears in which television series?", a: ["Game of Thrones", "The Witcher", "Vikings", "Rome"] },
  { c: 1, q: "The Beatles formed in which English city?", a: ["Liverpool", "Manchester", "London", "Birmingham"] },
  { c: 1, q: "Who hosted The Tonight Show for 30 years until 1992?", a: ["Johnny Carson", "David Letterman", "Jay Leno", "Conan O'Brien"] },
  { c: 1, q: "\"I'll be back\" is a catchphrase from which film franchise?", a: ["The Terminator", "Die Hard", "RoboCop", "Rambo"] },
  { c: 1, q: "Who recorded the 1965 song \"Like a Rolling Stone\"?", a: ["Bob Dylan", "Neil Young", "Johnny Cash", "Bruce Springsteen"] },
  { c: 1, q: "Who directed Pulp Fiction?", a: ["Quentin Tarantino", "Robert Rodriguez", "David Fincher", "Guy Ritchie"] },
  { c: 1, q: "Michael Scott is the regional manager in which sitcom?", a: ["The Office", "Parks and Recreation", "30 Rock", "Brooklyn Nine-Nine"] },
  { c: 1, q: "Which singer is known as the Queen of Soul?", a: ["Aretha Franklin", "Diana Ross", "Tina Turner", "Whitney Houston"] },
  { c: 1, q: "Who composed the scores for Star Wars, Jaws and Jurassic Park?", a: ["John Williams", "Hans Zimmer", "Ennio Morricone", "Danny Elfman"] },
  { c: 1, q: "Which Disney princess loses a glass slipper at a ball?", a: ["Cinderella", "Snow White", "Belle", "Aurora"] },
  { c: 1, q: "The pop group ABBA came from which country?", a: ["Sweden", "Norway", "Denmark", "The Netherlands"] },
  { c: 1, q: "Which actor starred as Forrest Gump?", a: ["Tom Hanks", "Kevin Costner", "Robin Williams", "Bill Murray"] },
  { c: 1, q: "\"My Heart Will Go On\" was the theme song to which film?", a: ["Titanic", "The Bodyguard", "Ghost", "Armageddon"] },
  { c: 1, q: "Which series follows a chemistry teacher named Walter White?", a: ["Breaking Bad", "Better Call Saul", "Ozark", "Weeds"] },
  { c: 1, q: "Which rock band's drummer was John Bonham?", a: ["Led Zeppelin", "The Rolling Stones", "Deep Purple", "Black Sabbath"] },
  { c: 1, q: "Who voiced Woody in the Toy Story films?", a: ["Tom Hanks", "Tim Allen", "Billy Crystal", "John Goodman"] },
  { c: 1, q: "The Bollywood film industry is based in which country?", a: ["India", "Pakistan", "Bangladesh", "Nepal"] },
  { c: 1, q: "What is the name of Batman's butler?", a: ["Alfred", "Jarvis", "Lucius", "Bruce"] },
  { c: 1, q: "Which Best Picture winner features the character Hannibal Lecter?", a: ["The Silence of the Lambs", "Se7en", "Zodiac", "American Psycho"] },
  { c: 1, q: "Which band recorded \"Hotel California\"?", a: ["The Eagles", "Fleetwood Mac", "The Doobie Brothers", "Steely Dan"] },
  { c: 1, q: "Who created the character Mickey Mouse?", a: ["Walt Disney", "Chuck Jones", "Hanna and Barbera", "Max Fleischer"] },
  { c: 1, q: "Which film features the song \"Somewhere Over the Rainbow\"?", a: ["The Wizard of Oz", "Mary Poppins", "Singin' in the Rain", "The Sound of Music"] },
  { c: 1, q: "Which anime studio produced Spirited Away?", a: ["Studio Ghibli", "Toei Animation", "Madhouse", "Kyoto Animation"] },
  { c: 1, q: "Who played Captain Jack Sparrow in Pirates of the Caribbean?", a: ["Johnny Depp", "Orlando Bloom", "Geoffrey Rush", "Javier Bardem"] },

  // ----------------------------------------------------------------- History
  { c: 2, q: "In which year did the Second World War end?", a: ["1945", "1944", "1946", "1939"] },
  { c: 2, q: "Who was the first President of the United States?", a: ["George Washington", "Thomas Jefferson", "John Adams", "Benjamin Franklin"] },
  { c: 2, q: "Which empire built Machu Picchu?", a: ["The Inca", "The Aztec", "The Maya", "The Olmec"] },
  { c: 2, q: "In which year did the Berlin Wall fall?", a: ["1989", "1991", "1987", "1993"] },
  { c: 2, q: "Who was the first person to walk on the Moon?", a: ["Neil Armstrong", "Buzz Aldrin", "Yuri Gagarin", "Michael Collins"] },
  { c: 2, q: "Which ocean liner sank on its maiden voyage in 1912?", a: ["The Titanic", "The Lusitania", "The Britannic", "The Andrea Doria"] },
  { c: 2, q: "Who was British Prime Minister for most of the Second World War?", a: ["Winston Churchill", "Neville Chamberlain", "Clement Attlee", "Anthony Eden"] },
  { c: 2, q: "In which year did the French Revolution begin?", a: ["1789", "1776", "1799", "1804"] },
  { c: 2, q: "Who was the principal author of the US Declaration of Independence?", a: ["Thomas Jefferson", "George Washington", "John Adams", "Alexander Hamilton"] },
  { c: 2, q: "Who was assassinated in Dallas, Texas in 1963?", a: ["John F. Kennedy", "Martin Luther King Jr.", "Robert Kennedy", "Malcolm X"] },
  { c: 2, q: "Which queen reigned over Britain from 1837 to 1901?", a: ["Victoria", "Elizabeth I", "Anne", "Mary II"] },
  { c: 2, q: "In which year was the Magna Carta sealed?", a: ["1215", "1066", "1314", "1415"] },
  { c: 2, q: "Hadrian's Wall was built by which empire?", a: ["The Roman Empire", "The Byzantine Empire", "The Holy Roman Empire", "The Norman Kingdom"] },
  { c: 2, q: "Who led India's nonviolent independence movement against British rule?", a: ["Mahatma Gandhi", "Jawaharlal Nehru", "Subhas Chandra Bose", "B. R. Ambedkar"] },
  { c: 2, q: "The Cold War was primarily between the United States and which country?", a: ["The Soviet Union", "China", "Germany", "Cuba"] },
  { c: 2, q: "Whose expedition first circumnavigated the globe?", a: ["Ferdinand Magellan", "Christopher Columbus", "Vasco da Gama", "Francis Drake"] },
  { c: 2, q: "In which year was Pearl Harbor attacked?", a: ["1941", "1939", "1942", "1940"] },
  { c: 2, q: "Who was the first female Prime Minister of the United Kingdom?", a: ["Margaret Thatcher", "Theresa May", "Barbara Castle", "Nancy Astor"] },
  { c: 2, q: "Which ancient civilisation developed cuneiform writing?", a: ["The Sumerians", "The Egyptians", "The Phoenicians", "The Minoans"] },
  { c: 2, q: "Which US president issued the Emancipation Proclamation?", a: ["Abraham Lincoln", "Ulysses S. Grant", "Andrew Johnson", "James Buchanan"] },
  { c: 2, q: "In which year did the Russian Revolution overthrow the Tsar?", a: ["1917", "1905", "1921", "1914"] },
  { c: 2, q: "Which Egyptian queen was allied with Julius Caesar and Mark Antony?", a: ["Cleopatra", "Nefertiti", "Hatshepsut", "Ankhesenamun"] },
  { c: 2, q: "Which country gave the Statue of Liberty to the United States?", a: ["France", "Britain", "Spain", "Italy"] },
  { c: 2, q: "Apartheid was a system of racial segregation in which country?", a: ["South Africa", "Zimbabwe", "Namibia", "Kenya"] },
  { c: 2, q: "Who published the Ninety-five Theses in 1517?", a: ["Martin Luther", "John Calvin", "Henry VIII", "Erasmus"] },
  { c: 2, q: "Which 1815 battle ended Napoleon's rule?", a: ["Waterloo", "Trafalgar", "Austerlitz", "Borodino"] },
  { c: 2, q: "In which year was the Great Fire of London?", a: ["1666", "1605", "1712", "1580"] },
  { c: 2, q: "The Tokugawa shogunate ruled which country?", a: ["Japan", "China", "Korea", "Vietnam"] },
  { c: 2, q: "Who discovered the tomb of Tutankhamun in 1922?", a: ["Howard Carter", "Heinrich Schliemann", "Arthur Evans", "Flinders Petrie"] },
  { c: 2, q: "Which military alliance was founded in 1949?", a: ["NATO", "The Warsaw Pact", "The United Nations", "The League of Nations"] },
  { c: 2, q: "The Hundred Years' War was fought between England and which country?", a: ["France", "Spain", "Scotland", "The Netherlands"] },
  { c: 2, q: "Who was the first Emperor of Rome?", a: ["Augustus", "Julius Caesar", "Nero", "Constantine"] },
  { c: 2, q: "Which South African leader spent 27 years in prison before becoming president?", a: ["Nelson Mandela", "Desmond Tutu", "Steve Biko", "Thabo Mbeki"] },
  { c: 2, q: "In which year was the US Declaration of Independence adopted?", a: ["1776", "1781", "1783", "1774"] },
  { c: 2, q: "In which year did the Boston Tea Party take place?", a: ["1773", "1776", "1765", "1781"] },
  { c: 2, q: "Which pandemic swept Europe in the 14th century?", a: ["The Black Death", "The Spanish Flu", "Cholera", "Smallpox"] },
  { c: 2, q: "Which wall divided a German city until 1989?", a: ["The Berlin Wall", "The Iron Curtain Wall", "The Rhine Wall", "The Elbe Wall"] },
  { c: 2, q: "The Renaissance began in which country?", a: ["Italy", "France", "England", "Germany"] },
  { c: 2, q: "Who was the Macedonian king who conquered the Persian Empire?", a: ["Alexander the Great", "Philip II", "Darius III", "Xerxes"] },
  { c: 2, q: "In which year did the Chernobyl nuclear disaster occur?", a: ["1986", "1979", "1991", "1983"] },

  // ------------------------------------------------------- Arts & Literature
  { c: 3, q: "Who painted the Mona Lisa?", a: ["Leonardo da Vinci", "Michelangelo", "Raphael", "Titian"] },
  { c: 3, q: "Who wrote Romeo and Juliet?", a: ["William Shakespeare", "Christopher Marlowe", "Ben Jonson", "John Webster"] },
  { c: 3, q: "Who wrote Pride and Prejudice?", a: ["Jane Austen", "Emily Brontë", "George Eliot", "Elizabeth Gaskell"] },
  { c: 3, q: "Who painted The Persistence of Memory, with its melting clocks?", a: ["Salvador Dalí", "René Magritte", "Joan Miró", "Max Ernst"] },
  { c: 3, q: "Who wrote the novel 1984?", a: ["George Orwell", "Aldous Huxley", "Ray Bradbury", "H. G. Wells"] },
  { c: 3, q: "Which Russian author wrote War and Peace?", a: ["Leo Tolstoy", "Fyodor Dostoevsky", "Anton Chekhov", "Ivan Turgenev"] },
  { c: 3, q: "Who sculpted the marble statue of David in Florence?", a: ["Michelangelo", "Donatello", "Bernini", "Cellini"] },
  { c: 3, q: "Who wrote The Great Gatsby?", a: ["F. Scott Fitzgerald", "Ernest Hemingway", "John Steinbeck", "William Faulkner"] },
  { c: 3, q: "Who wrote the poem \"The Raven\"?", a: ["Edgar Allan Poe", "Walt Whitman", "Emily Dickinson", "Robert Frost"] },
  { c: 3, q: "Who wrote the Harry Potter novels?", a: ["J. K. Rowling", "Philip Pullman", "Suzanne Collins", "Rick Riordan"] },
  { c: 3, q: "Pablo Picasso co-founded which art movement?", a: ["Cubism", "Surrealism", "Impressionism", "Fauvism"] },
  { c: 3, q: "Which novel opens with the line \"It was the best of times, it was the worst of times\"?", a: ["A Tale of Two Cities", "Great Expectations", "Oliver Twist", "Bleak House"] },
  { c: 3, q: "Who painted The Starry Night?", a: ["Vincent van Gogh", "Claude Monet", "Paul Cézanne", "Paul Gauguin"] },
  { c: 3, q: "Who wrote Don Quixote?", a: ["Miguel de Cervantes", "Lope de Vega", "Federico García Lorca", "Gabriel García Márquez"] },
  { c: 3, q: "Which Greek epic recounts the journey home of Odysseus?", a: ["The Odyssey", "The Iliad", "The Aeneid", "Theogony"] },
  { c: 3, q: "Who wrote The Old Man and the Sea?", a: ["Ernest Hemingway", "John Steinbeck", "Jack London", "Herman Melville"] },
  { c: 3, q: "Michelangelo painted the ceiling of which chapel?", a: ["The Sistine Chapel", "The Pauline Chapel", "The Scrovegni Chapel", "King's College Chapel"] },
  { c: 3, q: "Who wrote Crime and Punishment?", a: ["Fyodor Dostoevsky", "Leo Tolstoy", "Nikolai Gogol", "Maxim Gorky"] },
  { c: 3, q: "Which Norwegian playwright wrote A Doll's House?", a: ["Henrik Ibsen", "August Strindberg", "Knut Hamsun", "Anton Chekhov"] },
  { c: 3, q: "Who wrote To Kill a Mockingbird?", a: ["Harper Lee", "Toni Morrison", "Flannery O'Connor", "Carson McCullers"] },
  { c: 3, q: "Which pop artist is famous for paintings of Campbell's soup cans?", a: ["Andy Warhol", "Roy Lichtenstein", "Jasper Johns", "Robert Rauschenberg"] },
  { c: 3, q: "Who wrote The Lord of the Rings?", a: ["J. R. R. Tolkien", "C. S. Lewis", "Terry Pratchett", "Ursula K. Le Guin"] },
  { c: 3, q: "Which museum houses the Mona Lisa?", a: ["The Louvre", "The Uffizi", "The Prado", "The Hermitage"] },
  { c: 3, q: "Who composed The Four Seasons?", a: ["Antonio Vivaldi", "Johann Sebastian Bach", "George Frideric Handel", "Joseph Haydn"] },
  { c: 3, q: "Which composer wrote the Ninth Symphony containing \"Ode to Joy\"?", a: ["Ludwig van Beethoven", "Wolfgang Amadeus Mozart", "Franz Schubert", "Johannes Brahms"] },
  { c: 3, q: "Who wrote Jane Eyre?", a: ["Charlotte Brontë", "Emily Brontë", "Anne Brontë", "Jane Austen"] },
  { c: 3, q: "Which Dutch master painted The Night Watch?", a: ["Rembrandt", "Vermeer", "Frans Hals", "Jan Steen"] },
  { c: 3, q: "Who wrote The Divine Comedy?", a: ["Dante Alighieri", "Petrarch", "Boccaccio", "Virgil"] },
  { c: 3, q: "Which author created Sherlock Holmes?", a: ["Arthur Conan Doyle", "Agatha Christie", "Wilkie Collins", "G. K. Chesterton"] },
  { c: 3, q: "Who wrote the novel Things Fall Apart?", a: ["Chinua Achebe", "Wole Soyinka", "Ngũgĩ wa Thiong'o", "Ben Okri"] },
  { c: 3, q: "Who painted The Scream?", a: ["Edvard Munch", "Gustav Klimt", "Egon Schiele", "Ernst Ludwig Kirchner"] },
  { c: 3, q: "Who wrote One Hundred Years of Solitude?", a: ["Gabriel García Márquez", "Jorge Luis Borges", "Mario Vargas Llosa", "Isabel Allende"] },
  { c: 3, q: "Who wrote the poem \"Do not go gentle into that good night\"?", a: ["Dylan Thomas", "W. B. Yeats", "T. S. Eliot", "Seamus Heaney"] },
  { c: 3, q: "Who composed the opera The Magic Flute?", a: ["Wolfgang Amadeus Mozart", "Giuseppe Verdi", "Richard Wagner", "Giacomo Puccini"] },
  { c: 3, q: "Who wrote Brave New World?", a: ["Aldous Huxley", "George Orwell", "Yevgeny Zamyatin", "Kurt Vonnegut"] },
  { c: 3, q: "Which Shakespeare play features a Prince of Denmark?", a: ["Hamlet", "Macbeth", "King Lear", "Othello"] },
  { c: 3, q: "Who wrote the novel Beloved?", a: ["Toni Morrison", "Alice Walker", "Maya Angelou", "Zora Neale Hurston"] },
  { c: 3, q: "Which American painter is known for his drip technique?", a: ["Jackson Pollock", "Willem de Kooning", "Mark Rothko", "Franz Kline"] },
  { c: 3, q: "Who wrote The Canterbury Tales?", a: ["Geoffrey Chaucer", "Thomas Malory", "John Milton", "Edmund Spenser"] },
  { c: 3, q: "Which artist painted the Water Lilies series?", a: ["Claude Monet", "Édouard Manet", "Pierre-Auguste Renoir", "Edgar Degas"] },

  // ------------------------------------------------------- Science & Nature
  { c: 4, q: "What is the chemical symbol for gold?", a: ["Au", "Ag", "Go", "Gd"] },
  { c: 4, q: "How many bones are there in the adult human body?", a: ["206", "198", "224", "186"] },
  { c: 4, q: "Which planet is known as the Red Planet?", a: ["Mars", "Venus", "Jupiter", "Mercury"] },
  { c: 4, q: "Which gas do plants absorb from the air for photosynthesis?", a: ["Carbon dioxide", "Oxygen", "Nitrogen", "Methane"] },
  { c: 4, q: "Who developed the theory of general relativity?", a: ["Albert Einstein", "Isaac Newton", "Niels Bohr", "Max Planck"] },
  { c: 4, q: "What is the hardest naturally occurring substance?", a: ["Diamond", "Quartz", "Titanium", "Corundum"] },
  { c: 4, q: "How many chambers does the human heart have?", a: ["Four", "Two", "Three", "Six"] },
  { c: 4, q: "Which is the largest planet in our solar system?", a: ["Jupiter", "Saturn", "Neptune", "Uranus"] },
  { c: 4, q: "Which type of blood cell fights infection?", a: ["White blood cells", "Red blood cells", "Platelets", "Plasma cells"] },
  { c: 4, q: "Roughly how fast does light travel in a vacuum?", a: ["300,000 km per second", "300,000 km per hour", "30,000 km per second", "3 million km per second"] },
  { c: 4, q: "Which element has atomic number 1?", a: ["Hydrogen", "Helium", "Oxygen", "Carbon"] },
  { c: 4, q: "Which organ produces insulin?", a: ["The pancreas", "The liver", "The kidney", "The spleen"] },
  { c: 4, q: "What is the largest mammal on Earth?", a: ["The blue whale", "The African elephant", "The sperm whale", "The giraffe"] },
  { c: 4, q: "Sunlight helps the body produce which vitamin?", a: ["Vitamin D", "Vitamin C", "Vitamin A", "Vitamin B12"] },
  { c: 4, q: "What is the study of fossils called?", a: ["Palaeontology", "Archaeology", "Geology", "Anthropology"] },
  { c: 4, q: "Which gas makes up about 78% of Earth's atmosphere?", a: ["Nitrogen", "Oxygen", "Carbon dioxide", "Argon"] },
  { c: 4, q: "Which organelle is known as the powerhouse of the cell?", a: ["The mitochondrion", "The nucleus", "The ribosome", "The Golgi apparatus"] },
  { c: 4, q: "Who formulated the three laws of motion?", a: ["Isaac Newton", "Galileo Galilei", "Johannes Kepler", "Robert Hooke"] },
  { c: 4, q: "How many legs does a spider have?", a: ["Eight", "Six", "Ten", "Twelve"] },
  { c: 4, q: "What is the chemical symbol for sodium?", a: ["Na", "So", "Sd", "S"] },
  { c: 4, q: "What is the closest star to Earth?", a: ["The Sun", "Proxima Centauri", "Sirius", "Alpha Centauri A"] },
  { c: 4, q: "Which is the fastest land animal?", a: ["The cheetah", "The pronghorn", "The lion", "The greyhound"] },
  { c: 4, q: "What does DNA stand for?", a: ["Deoxyribonucleic acid", "Dinucleic acid", "Deoxyribose nitrate", "Double nucleic acid"] },
  { c: 4, q: "Which planet has the most prominent ring system?", a: ["Saturn", "Jupiter", "Uranus", "Neptune"] },
  { c: 4, q: "At what temperature in Fahrenheit does water freeze?", a: ["32 degrees", "0 degrees", "48 degrees", "12 degrees"] },
  { c: 4, q: "Which metal is liquid at room temperature?", a: ["Mercury", "Lead", "Gallium", "Bromine"] },
  { c: 4, q: "What kind of animal is a Komodo dragon?", a: ["A lizard", "A snake", "A crocodile", "An amphibian"] },
  { c: 4, q: "What is the smallest unit of a chemical element?", a: ["An atom", "A molecule", "A cell", "An electron"] },
  { c: 4, q: "What is the largest organ of the human body?", a: ["The skin", "The liver", "The lungs", "The brain"] },
  { c: 4, q: "Who discovered penicillin?", a: ["Alexander Fleming", "Louis Pasteur", "Joseph Lister", "Edward Jenner"] },
  { c: 4, q: "How many teeth does a typical adult human have?", a: ["32", "28", "36", "30"] },
  { c: 4, q: "What is the approximate pH of pure water?", a: ["7", "1", "10", "14"] },
  { c: 4, q: "Which element is the main component of the Sun?", a: ["Hydrogen", "Helium", "Oxygen", "Iron"] },
  { c: 4, q: "What primarily causes ocean tides on Earth?", a: ["The Moon's gravity", "Wind patterns", "Earth's magnetic field", "Ocean currents"] },
  { c: 4, q: "Which dinosaur's name means \"tyrant lizard king\"?", a: ["Tyrannosaurus rex", "Velociraptor", "Allosaurus", "Spinosaurus"] },
  { c: 4, q: "What is the SI unit of force?", a: ["The newton", "The joule", "The watt", "The pascal"] },
  { c: 4, q: "Which scientist proposed the theory of evolution by natural selection?", a: ["Charles Darwin", "Gregor Mendel", "Jean-Baptiste Lamarck", "Alfred Nobel"] },
  { c: 4, q: "How many planets are in our solar system?", a: ["Eight", "Nine", "Seven", "Ten"] },
  { c: 4, q: "Which insect produces honey?", a: ["The bee", "The wasp", "The ant", "The hornet"] },
  { c: 4, q: "Which part of the plant conducts photosynthesis primarily?", a: ["The leaf", "The root", "The stem", "The flower"] },

  // -------------------------------------------------------- Sports & Leisure
  { c: 5, q: "How many players from each team are on the pitch in a soccer match?", a: ["Eleven", "Ten", "Twelve", "Nine"] },
  { c: 5, q: "Which country hosted the 2016 Summer Olympics?", a: ["Brazil", "China", "Britain", "Greece"] },
  { c: 5, q: "How many points is a touchdown worth in American football?", a: ["Six", "Seven", "Three", "Five"] },
  { c: 5, q: "In tennis, what term is used for a score of zero?", a: ["Love", "Nil", "Duck", "Blank"] },
  { c: 5, q: "Which sport is played with a shuttlecock?", a: ["Badminton", "Squash", "Table tennis", "Racquetball"] },
  { c: 5, q: "How many holes are played in a full round of golf?", a: ["18", "9", "20", "12"] },
  { c: 5, q: "Judo originated in which country?", a: ["Japan", "China", "Korea", "Brazil"] },
  { c: 5, q: "How often are the Summer Olympic Games held?", a: ["Every four years", "Every two years", "Every three years", "Every five years"] },
  { c: 5, q: "What is the maximum standard break in snooker?", a: ["147", "155", "180", "100"] },
  { c: 5, q: "Which sport is known as \"the sweet science\"?", a: ["Boxing", "Fencing", "Wrestling", "Archery"] },
  { c: 5, q: "How many players from each team are on the court in basketball?", a: ["Five", "Six", "Four", "Seven"] },
  { c: 5, q: "Which trophy is awarded to the NHL champion?", a: ["The Stanley Cup", "The Vince Lombardi Trophy", "The Commissioner's Trophy", "The Larry O'Brien Trophy"] },
  { c: 5, q: "The Tour de France is a competition in which sport?", a: ["Cycling", "Running", "Motor racing", "Rowing"] },
  { c: 5, q: "How many rings appear on the Olympic flag?", a: ["Five", "Four", "Six", "Seven"] },
  { c: 5, q: "Which country has won the most FIFA World Cups?", a: ["Brazil", "Germany", "Italy", "Argentina"] },
  { c: 5, q: "In baseball, how many strikes make a strikeout?", a: ["Three", "Two", "Four", "Five"] },
  { c: 5, q: "The terms \"birdie\" and \"eagle\" belong to which sport?", a: ["Golf", "Archery", "Falconry", "Cricket"] },
  { c: 5, q: "What colour jersey does the Tour de France overall leader wear?", a: ["Yellow", "Green", "Polka dot", "White"] },
  { c: 5, q: "How long is a marathon, in miles?", a: ["26.2", "24.8", "30", "20.5"] },
  { c: 5, q: "Taekwondo originated in which country?", a: ["Korea", "Japan", "China", "Thailand"] },
  { c: 5, q: "In chess, which piece moves in an L shape?", a: ["The knight", "The bishop", "The rook", "The queen"] },
  { c: 5, q: "How many squares are there on a chessboard?", a: ["64", "81", "100", "49"] },
  { c: 5, q: "Which sport is played at Wimbledon?", a: ["Tennis", "Cricket", "Golf", "Polo"] },
  { c: 5, q: "Which traditional sport is considered Japan's national sport?", a: ["Sumo wrestling", "Karate", "Baseball", "Kendo"] },
  { c: 5, q: "How many players from each team are on the court in volleyball?", a: ["Six", "Five", "Seven", "Four"] },
  { c: 5, q: "In the standard US Monopoly board, which is the most expensive property?", a: ["Boardwalk", "Park Place", "Marvin Gardens", "Pennsylvania Avenue"] },
  { c: 5, q: "The Ashes series is contested in which sport?", a: ["Cricket", "Rugby", "Rowing", "Lawn bowls"] },
  { c: 5, q: "How many cards are in a standard deck without jokers?", a: ["52", "54", "48", "60"] },
  { c: 5, q: "What is the highest possible hand in standard poker?", a: ["A royal flush", "Four of a kind", "A full house", "A straight flush to the queen"] },
  { c: 5, q: "The America's Cup is a trophy in which sport?", a: ["Sailing", "Golf", "Powerboat racing", "Rowing"] },
  { c: 5, q: "Rugby is generally said to have originated in which country?", a: ["England", "New Zealand", "Wales", "Ireland"] },
  { c: 5, q: "How many minutes are in a standard professional soccer match?", a: ["90", "80", "100", "60"] },
  { c: 5, q: "The Monaco Grand Prix is part of which racing series?", a: ["Formula 1", "NASCAR", "IndyCar", "MotoGP"] },
  { c: 5, q: "What is the highest score possible with three darts?", a: ["180", "150", "201", "170"] },
  { c: 5, q: "Which soccer player wears a different coloured jersey from teammates?", a: ["The goalkeeper", "The captain", "The striker", "The sweeper"] },
  { c: 5, q: "The Super Bowl is the championship game of which sport?", a: ["American football", "Baseball", "Basketball", "Ice hockey"] },
  { c: 5, q: "What is a perfect score in ten-pin bowling?", a: ["300", "270", "200", "350"] },
  { c: 5, q: "Which Olympic sport combines cross-country skiing and rifle shooting?", a: ["Biathlon", "Nordic combined", "Pentathlon", "Skiathlon"] },
  { c: 5, q: "How many players per team take the field in rugby union?", a: ["15", "13", "11", "17"] },
  { c: 5, q: "In which sport would you use a foil, épée or sabre?", a: ["Fencing", "Archery", "Javelin", "Shooting"] },
];

module.exports = QUESTIONS;
